Repository beclab/apps, pull requests merged in 2024-05, with the labels that each got.

#21 [UPDATE][sdwebui][0.0.4]Reduce required GPU
  sdwebui/Chart.yaml
  sdwebui/TerminusManifest.yaml
Labels: UPDATE

#22 [UPDATE][onlyoffice][0.0.6]fix entrance and update os dependencies
  onlyoffice/Chart.yaml
  onlyoffice/TerminusManifest.yaml
Labels: UPDATE

#23 [UPDATE][sdwebui][0.0.5]reduce requiredMemory
  sdwebui/Chart.yaml
  sdwebui/TerminusManifest.yaml
  sdwebui/templates/deployment.yaml
Labels: UPDATE

#24 [UPDATE][nostream][0.0.5]change db to system db
  nostream/Chart.yaml
  nostream/TerminusManifest.yaml
  nostream/templates/deployment.yaml
Labels: UPDATE

#25 [UPDATE][onlyoffice][0.0.7]Reduce required CPU
  onlyoffice/Chart.yaml
  onlyoffice/TerminusManifest.yaml
  onlyoffice/templates/deployment.yaml
Labels: waiting to submit, UPDATE

#26 [UPDATE][mastodon][0.0.6]reduce required cpu and memory
  mastodon/Chart.yaml
  mastodon/TerminusManifest.yaml
  mastodon/templates/all.yaml
Labels: UPDATE

#27 [UPDATE][bytebase][0.0.7]reduce required cpu
  bytebase/Chart.yaml
  bytebase/TerminusManifest.yaml
  bytebase/templates/proxy.yaml
Labels: UPDATE

#28 [UPDATE][jellyfin][0.0.4]reduce cpu
  jellyfin/Chart.yaml
  jellyfin/TerminusManifest.yaml
  jellyfin/templates/deployment.yaml
Labels: UPDATE

#29 [UPDATE][affine][0.0.5]reduce cpu
  affine/Chart.yaml
  affine/TerminusManifest.yaml
  affine/templates/deployment.yaml
Labels: UPDATE

#30 [UPDATE][n8n][0.0.7]reduce cpu & memory
  n8n/Chart.yaml
  n8n/TerminusManifest.yaml
  n8n/templates/n8n.yaml
Labels: UPDATE

#31 [UPDATE][r4business][0.1.24]
  r4business/Chart.yaml
  r4business/TerminusManifest.yaml
  r4business/templates/prerank.yaml
  r4business/templates/rank.yaml
Labels: UPDATE

#33 [UPDATE][r4entertainment][0.1.26]
  r4entertainment/Chart.yaml
  r4entertainment/TerminusManifest.yaml
  r4entertainment/templates/prerank.yaml
  r4entertainment/templates/rank.yaml
Labels: UPDATE

#34 [UPDATE][mastodon][0.0.20]update app version to 4.2.8
  mastodon/Chart.yaml
  mastodon/TerminusManifest.yaml
  mastodon/templates/Secret.yaml
  mastodon/templates/ServiceAccount.yaml
  mastodon/templates/all.yaml
  mastodon/templates/apache/configmap.yaml
  mastodon/templates/apache/deployment.yaml
  mastodon/templates/apache/service.yaml
  mastodon/templates/configmap-mastodon-default.yaml
  mastodon/templates/configmap-mastodon-init-scripts.yaml
  mastodon/templates/deployment-mastodon-sidekiq.yaml
  mastodon/templates/deployment-mastodon-streaming.yaml
  mastodon/templates/deployment-mastodon.yaml
  mastodon/templates/elasticsearch/service.yaml
  mastodon/templates/elasticsearch/statefulset.yaml
  mastodon/templates/job-mastodon-init.yaml
  mastodon/templates/minio/configmap.yaml
  mastodon/templates/minio/deployment.yaml
  mastodon/templates/minio/job-mastodon-minio-provisioning.yaml
  mastodon/templates/minio/pvc.yaml
  mastodon/templates/minio/service.yaml
  mastodon/templates/postgresql/service.yaml
  mastodon/templates/postgresql/statefulset.yaml
  mastodon/templates/redis/configmap.yaml
  mastodon/templates/redis/service.yaml
  mastodon/templates/redis/statefulset.yaml
  mastodon/templates/service-mastodon-streaming.yaml
  mastodon/templates/service-mastodon-web.yaml
Labels: waiting to submit, UPDATE

#35 [UPDATE][r4sport][0.1.25]
  r4sport/Chart.yaml
  r4sport/TerminusManifest.yaml
  r4sport/templates/prerank.yaml
  r4sport/templates/rank.yaml
Labels: UPDATE

#36 [UPDATE][r4tech][0.0.13]
  r4tech/Chart.yaml
  r4tech/TerminusManifest.yaml
  r4tech/templates/prerank.yaml
  r4tech/templates/rank.yaml
Labels: UPDATE

#37 [UPDATE][r4techbiz][0.1.22]
  r4techbiz/Chart.yaml
  r4techbiz/TerminusManifest.yaml
  r4techbiz/templates/prerank.yaml
  r4techbiz/templates/rank.yaml
Labels: UPDATE

#38 [UPDATE][r4world][0.1.29]
  r4world/Chart.yaml
  r4world/TerminusManifest.yaml
  r4world/templates/prerank.yaml
  r4world/templates/rank.yaml
Labels: UPDATE

#39 [UPDATE][qbittorrent][0.0.5]disable login & update io config
  qbittorrent/Chart.yaml
  qbittorrent/TerminusManifest.yaml
  qbittorrent/templates/deployment.yaml
  qbittorrent/templates/services.yaml
Labels: UPDATE

#40 [UPDATE][qbittorrent][0.0.8]save config & download progress
  qbittorrent/Chart.yaml
  qbittorrent/TerminusManifest.yaml
  qbittorrent/templates/deployment.yaml
Labels: UPDATE

#41 [UPDATE][showdoc][0.0.5]add readinessProbe
  showdoc/Chart.yaml
  showdoc/TerminusManifest.yaml
  showdoc/templates/showdoc.yaml
Labels: UPDATE

#42 [UPDATE][codeserver][0.0.11]disable login
  codeserver/Chart.yaml
  codeserver/TerminusManifest.yaml
  codeserver/templates/codeserver.yaml
Labels: UPDATE

#45 [UPDATE][nocodb][0.0.8]update entrances config & change db to system db
  nocodb/Chart.yaml
  nocodb/TerminusManifest.yaml
  nocodb/templates/deployment.yaml
Labels: UPDATE

#46 [UPDATE][nextcloud][0.0.12]change db to system db
  nextcloud/Chart.yaml
  nextcloud/TerminusManifest.yaml
  nextcloud/templates/deployment.yaml
Labels: UPDATE

#47 [UPDATE][sonarr][0.0.6]fix limit & update data config
  sonarr/Chart.yaml
  sonarr/TerminusManifest.yaml
  sonarr/templates/deployment.yaml
Labels: UPDATE

#48 [UPDATE][radarr][0.0.6]fix install
  radarr/Chart.yaml
  radarr/TerminusManifest.yaml
  radarr/templates/deployment.yaml
Labels: UPDATE

#49 [UPDATE][transmission][0.0.3]change downloads path to user home
  transmission/Chart.yaml
  transmission/TerminusManifest.yaml
  transmission/templates/deployment.yaml
Labels: UPDATE

#50 [NEW][farcasterhubble][0.0.23]new app farcasterhubble
  farcasterhubble/Chart.yaml
  farcasterhubble/TerminusManifest.yaml
  farcasterhubble/owners
  farcasterhubble/templates/deployment.yaml
  farcasterhubble/values.yaml
Labels: NEW

#51 [UPDATE][wordpress][0.0.13]update image repo, improve initial robustness
  wordpress/Chart.yaml
  wordpress/TerminusManifest.yaml
  wordpress/templates/proxy.yaml
Labels: UPDATE

#52 [UPDATE][wordpress][0.0.14]add promoteImage
  wordpress/Chart.yaml
  wordpress/TerminusManifest.yaml
Labels: UPDATE

#53 [UPDATE][novella][0.0.12]update domain
  novella/Chart.yaml
  novella/TerminusManifest.yaml
  novella/templates/deployment.yaml
Labels: UPDATE

#54 [UPDATE][gitlabpure][0.0.48]update openMethod
  gitlabpure/Chart.yaml
  gitlabpure/TerminusManifest.yaml
Labels: UPDATE

#56 [NEW][penpot][0.0.1]add penpot
  penpot/.helmignore
  penpot/Chart.yaml
  penpot/TerminusManifest.yaml
  penpot/owners
  penpot/templates/NOTES.txt
  penpot/templates/_helpers.tpl
  penpot/templates/backend/deployment.yaml
  penpot/templates/backend/service.yaml
  penpot/templates/exporter/deployment.yaml
  penpot/templates/exporter/service.yaml
  penpot/templates/frontend/deployment.yaml
  penpot/templates/frontend/service.yaml
  penpot/templates/redis/deployment.yaml
  penpot/templates/redis/service.yaml
  penpot/values.yaml
Labels: NEW

#57 [UPDATE][bytebase][0.0.8]add image and adjust required resource
  bytebase/Chart.yaml
  bytebase/TerminusManifest.yaml
  bytebase/templates/bytebase.yaml
  bytebase/templates/proxy.yaml
Labels: UPDATE

#58 [UPDATE][comfyui][0.0.15]add promoteImage
  comfyui/Chart.yaml
  comfyui/TerminusManifest.yaml
Labels: UPDATE

#59 [UPDATE][penpot][0.0.2]update penpot
  penpot/Chart.yaml
  penpot/TerminusManifest.yaml
  penpot/templates/backend/deployment.yaml
  penpot/templates/exporter/deployment.yaml
  penpot/templates/frontend/deployment.yaml
  penpot/templates/redis/deployment.yaml
Labels: waiting to submit, UPDATE

#61 [UPDATE][ghost][0.0.5]add image and adjust resources
  ghost/Chart.yaml
  ghost/TerminusManifest.yaml
  ghost/templates/deployment.yaml
Labels: UPDATE

#62 [SUSPEND][sealcaster][0.0.2]
  sealcaster/.suspend
Labels: SUSPEND

#67 [UPDATE][farcasterhubble][0.0.24]update description and add promotion images
  farcasterhubble/Chart.yaml
  farcasterhubble/TerminusManifest.yaml
Labels: UPDATE

#68 [UPDATE][gitlabfusion][0.0.99]fix domain in web & fix auto login multi user
  gitlabfusion/Chart.yaml
  gitlabfusion/TerminusManifest.yaml
  gitlabfusion/templates/clientproxy.yaml
  gitlabfusion/templates/serverproxy.yaml
Labels: UPDATE

#69 [UPDATE][gitlabfusionclient][0.0.26]fix domain in web & fix auto login multi user
  gitlabfusionclient/Chart.yaml
  gitlabfusionclient/TerminusManifest.yaml
  gitlabfusionclient/templates/clientproxy.yaml
Labels: UPDATE

#70 [SUSPEND][otmoicrelay][0.0.11]suspend
  otmoicrelay/.suspend
Labels: SUSPEND

#71 [SUSPEND][lidarr][0.0.2]suspend
  lidarr/.suspend
Labels: SUSPEND

#72 [UPDATE][sickchill][0.0.3]Configure user directory
  sickchill/Chart.yaml
  sickchill/TerminusManifest.yaml
  sickchill/templates/deployment.yaml
Labels: merged, UPDATE

#74 [UPDATE][deluge][0.0.3]update config user directory
  deluge/Chart.yaml
  deluge/TerminusManifest.yaml
  deluge/templates/deployment.yaml
Labels: UPDATE

#65 [UPDATE][codeserver][0.0.13]delete default credentials
  codeserver/Chart.yaml
  codeserver/TerminusManifest.yaml
  codeserver/templates/chartmuseum.yaml
  codeserver/templates/codeserver.yaml
Labels: UPDATE

#73 [UPDATE][chinesesubfinder][0.0.2]update config user directory
  chinesesubfinder/Chart.yaml
  chinesesubfinder/TerminusManifest.yaml
  chinesesubfinder/templates/chinesesubfinder.yaml
Labels: UPDATE

#75 [UPDATE][nzbget][0.0.7]update config user directory
  nzbget/Chart.yaml
  nzbget/TerminusManifest.yaml
  nzbget/templates/deployment.yaml
Labels: UPDATE

#66 [UPDATE][affine][0.0.6] add images
  affine/Chart.yaml
  affine/TerminusManifest.yaml
  affine/templates/deployment.yaml
Labels: UPDATE

#64 [UPDATE][onlyoffice][0.0.8]Add Promote Image and configure guide
  onlyoffice/Chart.yaml
  onlyoffice/TerminusManifest.yaml
  onlyoffice/templates/deployment.yaml
Labels: waiting to submit, UPDATE

#76 [SUSPEND][openllm][0.0.10]
  openllm/.suspend
Labels: SUSPEND

#77 [UPDATE][duplicati][0.0.3]update config user directory
  duplicati/Chart.yaml
  duplicati/TerminusManifest.yaml
  duplicati/templates/deployment.yaml
Labels: UPDATE

#78 [SUSPEND][filebrowser][0.0.1]suspend
  filebrowser/.suspend
Labels: SUSPEND

#80 [UPDATE][ghost][0.0.7]update entrances config
  ghost/Chart.yaml
  ghost/TerminusManifest.yaml
Labels: UPDATE

#79 [UPDATE][otmoiclp][0.0.17]update version to V2.1.1
  otmoiclp/Chart.yaml
  otmoiclp/TerminusManifest.yaml
  otmoiclp/templates/admin.yaml
  otmoiclp/templates/amm.yaml
  otmoiclp/templates/amm_analytics.yaml
  otmoiclp/templates/analyse.yaml
  otmoiclp/templates/dashboard.yaml
  otmoiclp/templates/dev.yaml
  otmoiclp/templates/evm_avax.yaml
  otmoiclp/templates/evm_bsc.yaml
  otmoiclp/templates/evm_eth.yaml
  otmoiclp/templates/evm_op.yaml
  otmoiclp/templates/graphql.yaml
  otmoiclp/templates/lpnode.yaml
  otmoiclp/templates/market.yaml
Labels: waiting to submit, UPDATE

#81 [UPDATE][obsidian][0.0.11]30x to /_utils & update config entrances
  obsidian/Chart.yaml
  obsidian/TerminusManifest.yaml
  obsidian/templates/deployment.yaml
Labels: UPDATE

#82 [UPDATE][obsidian][0.0.12]change entrance to private
  obsidian/Chart.yaml
  obsidian/TerminusManifest.yaml
Labels: UPDATE

#83 [UPDATE][navidrome][0.0.6]update default path
  navidrome/Chart.yaml
  navidrome/TerminusManifest.yaml
  navidrome/templates/deployment.yaml
Labels: UPDATE

#84 [UPDATE][ipfs][0.0.20]Update config directory & Add initialization process
  ipfs/Chart.yaml
  ipfs/TerminusManifest.yaml
  ipfs/templates/deployment.yaml
Labels: UPDATE

#85 [UPDATE][ipfs][0.0.28]support local
  ipfs/Chart.yaml
  ipfs/TerminusManifest.yaml
  ipfs/templates/deployment.yaml
Labels: UPDATE

#86 [UPDATE][ipfs][0.0.29]update config client_max_body_size
  ipfs/Chart.yaml
  ipfs/TerminusManifest.yaml
  ipfs/templates/deployment.yaml
Labels: UPDATE

#87 [UPDATE][codeserver][0.0.14]fix init shell
  codeserver/Chart.yaml
  codeserver/TerminusManifest.yaml
  codeserver/templates/codeserver.yaml
Labels: UPDATE

#89 [UPDATE][penpot][0.0.3]update penpot
  penpot/Chart.yaml
  penpot/TerminusManifest.yaml
  penpot/templates/backend/deployment.yaml
  penpot/templates/exporter/deployment.yaml
  penpot/templates/frontend/deployment.yaml
Labels: UPDATE
