Repository beclab/apps, pull requests merged in 2024-07, with the labels that each got.

#129 [UPDATE][r4entertainment][0.1.36]Fix featured image
  r4entertainment/Chart.yaml
  r4entertainment/TerminusManifest.yaml
Labels: UPDATE

#130 [UPDATE][r4world][0.1.36]fix: featuredImage
  r4world/Chart.yaml
  r4world/TerminusManifest.yaml
Labels: waiting to submit, UPDATE

#131 [NEW][mattermost][0.0.6]new app mattermost
  mattermost/Chart.yaml
  mattermost/TerminusManifest.yaml
  mattermost/owners
  mattermost/templates/configmap.yaml
  mattermost/templates/mattermost.yaml
  mattermost/templates/secret.yaml
  mattermost/values.yaml
Labels: NEW

#132 [UPDATE][devbox][0.0.4]update provider api
  devbox/Chart.yaml
  devbox/TerminusManifest.yaml
  devbox/templates/deployment.yaml
Labels: UPDATE

#148 [NEW][difyfusion][0.0.1]add dify funsion
  difyfusion/.helmignore
  difyfusion/Chart.yaml
  difyfusion/TerminusManifest.yaml
  difyfusion/owners
  difyfusion/templates/NOTES.txt
  difyfusion/templates/_helpers.tpl
  difyfusion/templates/deployment.yaml
  difyfusion/values.yaml
Labels: waiting to submit, NEW

#149 [NEW][difyfusionclient][0.0.1]add difyfusionclient
  difyfusionclient/.helmignore
  difyfusionclient/Chart.yaml
  difyfusionclient/TerminusManifest.yaml
  difyfusionclient/owners
  difyfusionclient/templates/NOTES.txt
  difyfusionclient/templates/_helpers.tpl
  difyfusionclient/templates/dify_fe_deploy.yaml
  difyfusionclient/values.yaml
Labels: waiting to submit, NEW

#134 [UPDATE][wordpress][0.0.15]update icon and description
  wordpress/Chart.yaml
  wordpress/TerminusManifest.yaml
  wordpress/owners
Labels: UPDATE

#135 [UPDATE][onlyoffice][0.0.9] update icon and description
  onlyoffice/Chart.yaml
  onlyoffice/TerminusManifest.yaml
  onlyoffice/owners
Labels: UPDATE

#136 [UPDATE][obsidian][0.0.14]update icon and description
  obsidian/Chart.yaml
  obsidian/README.md
  obsidian/TerminusManifest.yaml
  obsidian/owners
Labels: UPDATE

#137 [UPDATE][affine][0.0.8]update icon and description
  affine/Chart.yaml
  affine/TerminusManifest.yaml
  affine/owners
Labels: UPDATE

#142 [UPDATE][nostream][0.0.6]update icon and description
  nostream/Chart.yaml
  nostream/TerminusManifest.yaml
  nostream/owners
Labels: UPDATE

#146 [UPDATE][gitlabpure][0.0.49]update icon and description
  gitlabpure/Chart.yaml
  gitlabpure/TerminusManifest.yaml
  gitlabpure/owners
Labels: UPDATE

#141 [UPDATE][gitlabfusion][0.0.100]update icon and description
  gitlabfusion/Chart.yaml
  gitlabfusion/TerminusManifest.yaml
  gitlabfusion/owners
Labels: UPDATE

#139 [UPDATE][comfyui][0.0.16]update icon and description
  comfyui/Chart.yaml
  comfyui/TerminusManifest.yaml
  comfyui/owners
Labels: UPDATE

#140 [UPDATE][ghost][0.0.8]update icon and description
  ghost/Chart.yaml
  ghost/TerminusManifest.yaml
  ghost/owners
Labels: UPDATE

#133 [UPDATE][bytebase][0.0.11]update icon and description
  bytebase/Chart.yaml
  bytebase/TerminusManifest.yaml
  bytebase/owners
Labels: UPDATE

#145 [UPDATE][ipfs][0.0.30]update icon and description
  ipfs/Chart.yaml
  ipfs/TerminusManifest.yaml
  ipfs/owners
Labels: UPDATE

#144 [UPDATE][navidrome][0.0.7]update icon and description
  navidrome/Chart.yaml
  navidrome/TerminusManifest.yaml
  navidrome/owners
Labels: UPDATE

#143 [UPDATE][nocodb][0.0.9]update icon and description
  nocodb/Chart.yaml
  nocodb/TerminusManifest.yaml
  nocodb/owners
Labels: UPDATE

#150 [UPDATE][difyfusionclient][0.0.2]update ProviderRegistry
  difyfusionclient/Chart.yaml
  difyfusionclient/TerminusManifest.yaml
  difyfusionclient/templates/dify_fe_deploy.yaml
Labels: UPDATE

#152 [UPDATE][nextcloud][0.0.13]remove zincsearch and update description
  nextcloud/Chart.yaml
  nextcloud/TerminusManifest.yaml
  nextcloud/index0.json
  nextcloud/owners
Labels: UPDATE

#153 [UPDATE][devbox][0.0.5]update legacy_api
  devbox/Chart.yaml
  devbox/TerminusManifest.yaml
Labels: UPDATE

#156 [UPDATE][bazarr][0.0.6] add legacy provider
  bazarr/Chart.yaml
  bazarr/TerminusManifest.yaml
  bazarr/templates/deployment.yaml
Labels: UPDATE

#157 [UPDATE][readarr][0.0.5]add legacy provider
  readarr/Chart.yaml
  readarr/TerminusManifest.yaml
  readarr/templates/deployment.yaml
Labels: UPDATE

#160 [UPDATE][mastodon][0.0.45]fix k3s
  mastodon/Chart.yaml
  mastodon/TerminusManifest.yaml
  mastodon/templates/configmap-mastodon-default.yaml
  mastodon/templates/deployment-mastodon-sidekiq.yaml
  mastodon/templates/deployment-mastodon-streaming.yaml
  mastodon/templates/deployment-mastodon.yaml
  mastodon/templates/job-mastodon-init.yaml
Labels: UPDATE

#164 [UPDATE][deluge][0.0.4]add legacy provider
  deluge/Chart.yaml
  deluge/TerminusManifest.yaml
  deluge/templates/deployment.yaml
Labels: UPDATE

#165 [UPDATE][transmission][0.0.4]add legacy provider
  transmission/Chart.yaml
  transmission/TerminusManifest.yaml
  transmission/templates/deployment.yaml
Labels: UPDATE

#166 [UPDATE][qbittorrent][0.0.10]add legacy provider
  qbittorrent/Chart.yaml
  qbittorrent/TerminusManifest.yaml
  qbittorrent/templates/deployment.yaml
Labels: UPDATE

#168 [UPDATE][deluge][0.0.5]fix endpoint port
  deluge/Chart.yaml
  deluge/TerminusManifest.yaml
  deluge/templates/deployment.yaml
Labels: UPDATE

#169 [UPDATE][transmission][0.0.5]fix endpoint port
  transmission/Chart.yaml
  transmission/TerminusManifest.yaml
  transmission/templates/deployment.yaml
Labels: UPDATE

#170 [UPDATE][radarr][0.0.8]bug fix and add config guide readme
  radarr/Chart.yaml
  radarr/README.md
  radarr/TerminusManifest.yaml
Labels: UPDATE

#171 [UPDATE][sonarr][0.0.12]add readme and fix permission bug
  sonarr/Chart.yaml
  sonarr/README.md
  sonarr/TerminusManifest.yaml
Labels: UPDATE

#172 [UPDATE][readarr][0.0.6]add config readme file and fix permission bug
  readarr/Chart.yaml
  readarr/README.md
  readarr/TerminusManifest.yaml
Labels: UPDATE

#174 [NEW][perplexica][0.0.11]new app perplexica
  perplexica/Chart.yaml
  perplexica/TerminusManifest.yaml
  perplexica/owners
  perplexica/templates/backend.yaml
  perplexica/templates/frontend.yaml
  perplexica/values.yaml
Labels: NEW

#175 [NEW][ollama][0.0.6]new app ollama
  ollama/Chart.yaml
  ollama/TerminusManifest.yaml
  ollama/owners
  ollama/templates/deployment.yaml
  ollama/values.yaml
Labels: waiting to submit, NEW

#173 [NEW][searxng][0.0.13]new app searxng
  searxng/Chart.yaml
  searxng/TerminusManifest.yaml
  searxng/owners
  searxng/templates/deployment.yaml
  searxng/values.yaml
Labels: NEW

#176 [UPDATE][searxng][0.0.14]fix title
  searxng/Chart.yaml
  searxng/TerminusManifest.yaml
Labels: UPDATE

#177 [UPDATE][jellyfin][0.0.6]adjust resources limits
  jellyfin/Chart.yaml
  jellyfin/TerminusManifest.yaml
  jellyfin/templates/deployment.yaml
Labels: UPDATE

#178 [UPDATE][sonarr][0.0.13]add home directory
  sonarr/Chart.yaml
  sonarr/TerminusManifest.yaml
  sonarr/templates/deployment.yaml
Labels: UPDATE

#179 [UPDATE][ollama][0.0.12]Embed OpenWebui into Olllama
  ollama/Chart.yaml
  ollama/TerminusManifest.yaml
  ollama/templates/openwebui.yaml
Labels: UPDATE

#181 [UPDATE][n8n][0.0.8]fix open method
  n8n/Chart.yaml
  n8n/TerminusManifest.yaml
Labels: UPDATE

#182 [UPDATE][radarr][0.0.9]fix readme format bug
  radarr/Chart.yaml
  radarr/README.md
  radarr/TerminusManifest.yaml
Labels: waiting to submit, UPDATE

#183 [UPDATE][mongodb][6.0.5]fix install error on arm64
  mongodb/Chart.yaml
  mongodb/TerminusManifest.yaml
  mongodb/templates/deployment.yaml
Labels: UPDATE

#184 [UPDATE][prowlarr][0.0.11]update readme and description format
  prowlarr/Chart.yaml
  prowlarr/README.md
  prowlarr/TerminusManifest.yaml
Labels: UPDATE

#185 [UPDATE][jellyfin][0.0.11]Fix the issue of configuration loss upon restart.
  jellyfin/Chart.yaml
  jellyfin/TerminusManifest.yaml
  jellyfin/templates/deployment.yaml
Labels: UPDATE

#180 [NEW][openwebui][0.0.6]new app openwebui
  openwebui/Chart.yaml
  openwebui/TerminusManifest.yaml
  openwebui/owners
  openwebui/templates/deployment.yaml
  openwebui/values.yaml
Labels: waiting to submit, NEW

#159 [UPDATE][lidarr][0.0.3]unsuspend app, add legacy provider and fix home directory issue
  lidarr/.suspend
  lidarr/Chart.yaml
  lidarr/TerminusManifest.yaml
  lidarr/templates/deployment.yaml
  lidarr/values.yaml
Labels: UPDATE

#186 [UPDATE][farcasterhubble][0.0.25]adjust resource requirement
  farcasterhubble/Chart.yaml
  farcasterhubble/TerminusManifest.yaml
  farcasterhubble/templates/deployment.yaml
Labels: waiting to submit, UPDATE
