Repository beclab/apps, pull requests merged in 2024-08, with the labels that each got.

#187 [UPDATE][openwebui][0.0.8]add config: gaianetai api
  openwebui/Chart.yaml
  openwebui/TerminusManifest.yaml
  openwebui/templates/deployment.yaml
Labels: UPDATE

#188 [NEW][gaianetai][0.0.5]new app gaianetai
  gaianetai/.helmignore
  gaianetai/Chart.yaml
  gaianetai/TerminusManifest.yaml
  gaianetai/owners
  gaianetai/templates/deployment.yaml
  gaianetai/values.yaml
Labels: waiting to submit, NEW

#189 [UPDATE][farcasterhubble][0.0.26]fix resources setup
  farcasterhubble/Chart.yaml
  farcasterhubble/TerminusManifest.yaml
  farcasterhubble/templates/deployment.yaml
Labels: UPDATE

#190 [UPDATE][openwebui][0.0.9]add support app : whisper
  openwebui/Chart.yaml
  openwebui/TerminusManifest.yaml
Labels: UPDATE

#192 [UPDATE][openwebui][0.0.10]support app: openedai-speech
  openwebui/Chart.yaml
  openwebui/TerminusManifest.yaml
Labels: UPDATE

#194 [UPDATE][farcasterhubble][0.0.27]adjust required memory
  farcasterhubble/Chart.yaml
  farcasterhubble/TerminusManifest.yaml
  farcasterhubble/templates/deployment.yaml
Labels: UPDATE

#195 [UPDATE][r4techbiz][0.1.36]upgrade prerank to v0.0.11
  r4techbiz/Chart.yaml
  r4techbiz/TerminusManifest.yaml
  r4techbiz/templates/prerank.yaml
Labels: UPDATE

#196 [UPDATE][farcasterhubble][0.0.28]fix required disk unit
  farcasterhubble/Chart.yaml
  farcasterhubble/TerminusManifest.yaml
Labels: UPDATE

#198 [UPDATE][openwebui][0.0.12]support new api: sdwebui
  openwebui/Chart.yaml
  openwebui/TerminusManifest.yaml
Labels: UPDATE

#199 [UPDATE][r4techbiz][0.1.37]add recommend reason
  r4techbiz/Chart.yaml
  r4techbiz/TerminusManifest.yaml
  r4techbiz/templates/rank.yaml
  r4techbiz/templates/train.yaml
Labels: UPDATE

#200 [UPDATE][r4business][0.1.36]add recommend reason
  r4business/Chart.yaml
  r4business/TerminusManifest.yaml
  r4business/templates/rank.yaml
  r4business/templates/train.yaml
Labels: UPDATE

#201 [UPDATE][r4world][0.1.37]add recommend reason
  r4world/Chart.yaml
  r4world/TerminusManifest.yaml
  r4world/templates/rank.yaml
  r4world/templates/train.yaml
Labels: UPDATE

#202 [UPDATE][r4entertainment][0.1.37]add recommend reason
  r4entertainment/Chart.yaml
  r4entertainment/TerminusManifest.yaml
  r4entertainment/templates/rank.yaml
  r4entertainment/templates/train.yaml
Labels: UPDATE

#203 [UPDATE][r4sport][0.1.36]add recommend reason
  r4sport/Chart.yaml
  r4sport/TerminusManifest.yaml
  r4sport/templates/rank.yaml
  r4sport/templates/train.yaml
Labels: UPDATE

#204 [UPDATE][r4tech][0.1.36]add recommend reason
  r4tech/Chart.yaml
  r4tech/TerminusManifest.yaml
  r4tech/templates/rank.yaml
  r4tech/templates/train.yaml
Labels: UPDATE

#193 [NEW][openedaispeech][0.0.7]new app openedai-speech
  openedaispeech/Chart.yaml
  openedaispeech/TerminusManifest.yaml
  openedaispeech/owners
  openedaispeech/templates/deployment.yaml
  openedaispeech/values.yaml
Labels: waiting to submit, NEW

#191 [NEW][whisper][0.0.6]new app whisper
  whisper/Chart.yaml
  whisper/TerminusManifest.yaml
  whisper/owners
  whisper/templates/deployment.yaml
  whisper/values.yaml
Labels: waiting to submit, NEW

#205 [UPDATE][mastodon][0.0.46]support oauth
  mastodon/Chart.yaml
  mastodon/TerminusManifest.yaml
  mastodon/templates/configmap-mastodon-default.yaml
  mastodon/templates/deployment-mastodon-sidekiq.yaml
  mastodon/templates/deployment-mastodon-streaming.yaml
  mastodon/templates/deployment-mastodon.yaml
  mastodon/templates/job-mastodon-init.yaml
Labels: UPDATE

#206 [UPDATE][openwebui][0.0.13]fix svc config
  openwebui/Chart.yaml
  openwebui/TerminusManifest.yaml
Labels: UPDATE

#209 [UPDATE][affine][0.0.9]lock image
  affine/Chart.yaml
  affine/TerminusManifest.yaml
  affine/templates/deployment.yaml
Labels: UPDATE

#210 [UPDATE][astral][0.0.4]lock image
  astral/Chart.yaml
  astral/TerminusManifest.yaml
  astral/templates/deployment.yaml
Labels: UPDATE

#211 [UPDATE][bazarr][0.0.7]lock image
  bazarr/Chart.yaml
  bazarr/TerminusManifest.yaml
  bazarr/templates/deployment.yaml
Labels: UPDATE

#212 [UPDATE][bytebase][0.0.12]lock image
  bytebase/Chart.yaml
  bytebase/TerminusManifest.yaml
  bytebase/templates/bytebase.yaml
  bytebase/templates/proxy.yaml
Labels: UPDATE

#213 [UPDATE][calendar][0.0.2]lock image
  calendar/Chart.yaml
  calendar/TerminusManifest.yaml
  calendar/templates/calendar_deploy.yaml
Labels: UPDATE

#215 [UPDATE][calibre][0.0.2]lock image
  calibre/Chart.yaml
  calibre/TerminusManifest.yaml
  calibre/templates/deployment.yaml
Labels: UPDATE

#216 [UPDATE][calibreweb][0.0.3]lock image
  calibreweb/Chart.yaml
  calibreweb/TerminusManifest.yaml
  calibreweb/templates/deployment.yaml
Labels: UPDATE

#217 [UPDATE][chinesesubfinder][0.0.3]lock image
  chinesesubfinder/Chart.yaml
  chinesesubfinder/TerminusManifest.yaml
  chinesesubfinder/templates/chinesesubfinder.yaml
Labels: UPDATE

#218 [UPDATE][chromium][0.0.2]lock image
  chromium/Chart.yaml
  chromium/TerminusManifest.yaml
  chromium/templates/chromium.yaml
Labels: UPDATE

#219 [UPDATE][codeserver][0.0.15]lock image
  codeserver/Chart.yaml
  codeserver/TerminusManifest.yaml
  codeserver/templates/chartmuseum.yaml
  codeserver/templates/codeserver.yaml
Labels: UPDATE

#220 [UPDATE][comfyui][0.0.17]lock image
  comfyui/Chart.yaml
  comfyui/TerminusManifest.yaml
  comfyui/templates/deployment.yaml
Labels: UPDATE

#221 [UPDATE][deluge][0.0.6]lock image
  deluge/Chart.yaml
  deluge/TerminusManifest.yaml
  deluge/templates/deployment.yaml
Labels: UPDATE

#222 [UPDATE][devbox][0.0.6]lock image
  devbox/Chart.yaml
  devbox/TerminusManifest.yaml
  devbox/templates/deployment.yaml
Labels: UPDATE

#223 [UPDATE][difyfusion][0.0.2]lock image
  difyfusion/Chart.yaml
  difyfusion/TerminusManifest.yaml
  difyfusion/templates/deployment.yaml
Labels: UPDATE

#224 [UPDATE][difyfusionclient][0.0.3]lock image
  difyfusionclient/Chart.yaml
  difyfusionclient/TerminusManifest.yaml
  difyfusionclient/templates/dify_fe_deploy.yaml
Labels: UPDATE

#225 [UPDATE][duplicati][0.0.4]lock image
  duplicati/Chart.yaml
  duplicati/TerminusManifest.yaml
  duplicati/templates/deployment.yaml
Labels: UPDATE

#226 [UPDATE][farcasterhubble][0.0.29]lock image
  farcasterhubble/Chart.yaml
  farcasterhubble/TerminusManifest.yaml
  farcasterhubble/templates/deployment.yaml
Labels: UPDATE

#228 [UPDATE][firefox][0.0.4]lock image
  firefox/Chart.yaml
  firefox/TerminusManifest.yaml
  firefox/templates/firefox.yaml
Labels: UPDATE

#229 [UPDATE][gaianetai][0.0.6]lock image
  gaianetai/Chart.yaml
  gaianetai/TerminusManifest.yaml
  gaianetai/templates/deployment.yaml
Labels: UPDATE

#230 [UPDATE][geth][0.0.3]lock image
  geth/Chart.yaml
  geth/TerminusManifest.yaml
  geth/templates/geth.yaml
  geth/templates/traefik.yaml
Labels: UPDATE

#233 [UPDATE][gitlabfusion][0.1.0]lock image
  gitlabfusion/Chart.yaml
  gitlabfusion/TerminusManifest.yaml
  gitlabfusion/templates/clientproxy.yaml
  gitlabfusion/templates/gitlab.yaml
  gitlabfusion/templates/serverproxy.yaml
Labels: UPDATE

#234 [UPDATE][gitlabfusionclient][0.0.28]lock image
  gitlabfusionclient/Chart.yaml
  gitlabfusionclient/TerminusManifest.yaml
  gitlabfusionclient/templates/clientproxy.yaml
Labels: UPDATE

#232 [UPDATE][r4techbiz][0.1.38]change model to bert_v3
  r4techbiz/Chart.yaml
  r4techbiz/TerminusManifest.yaml
  r4techbiz/templates/embedding.yaml
  r4techbiz/templates/prerank.yaml
Labels: UPDATE

#235 [UPDATE][gitlabpure][0.0.50]lock image
  gitlabpure/Chart.yaml
  gitlabpure/TerminusManifest.yaml
  gitlabpure/templates/gitlab.yaml
Labels: UPDATE

#236 [UPDATE][r4tech][0.1.37]upgrade prerank and embedding
  r4tech/Chart.yaml
  r4tech/TerminusManifest.yaml
  r4tech/templates/embedding.yaml
  r4tech/templates/prerank.yaml
Labels: UPDATE

#237 [UPDATE][r4entertainment][0.1.38]upgrade prerank and embedding
  r4entertainment/Chart.yaml
  r4entertainment/TerminusManifest.yaml
  r4entertainment/templates/embedding.yaml
  r4entertainment/templates/prerank.yaml
Labels: UPDATE

#238 [UPDATE][r4business][0.1.37]upgrade prerank and embedding
  r4business/Chart.yaml
  r4business/TerminusManifest.yaml
  r4business/templates/embedding.yaml
  r4business/templates/prerank.yaml
Labels: UPDATE

#239 [UPDATE][r4world][0.1.38]upgrade prerank and embedding
  r4world/Chart.yaml
  r4world/TerminusManifest.yaml
  r4world/templates/embedding.yaml
  r4world/templates/prerank.yaml
Labels: UPDATE

#240 [UPDATE][r4sport][0.1.37]upgrade prerank and embedding
  r4sport/Chart.yaml
  r4sport/TerminusManifest.yaml
  r4sport/templates/embedding.yaml
  r4sport/templates/prerank.yaml
Labels: UPDATE

#241 [UPDATE][homeassistant][0.0.15]lock image
  homeassistant/Chart.yaml
  homeassistant/TerminusManifest.yaml
  homeassistant/templates/deployment.yaml
Labels: UPDATE

#242 [UPDATE][immich][0.0.16]lock image
  immich/Chart.yaml
  immich/TerminusManifest.yaml
  immich/templates/machine-learning.yaml
  immich/templates/server.yaml
Labels: UPDATE

#243 [UPDATE][ipfs][0.0.31]lock image
  ipfs/Chart.yaml
  ipfs/TerminusManifest.yaml
  ipfs/templates/deployment.yaml
Labels: UPDATE

#244 [UPDATE][jellyfin][0.0.12]lock image
  jellyfin/Chart.yaml
  jellyfin/TerminusManifest.yaml
  jellyfin/templates/deployment.yaml
Labels: UPDATE

#245 [UPDATE][lidarr][0.0.4]lock image
  lidarr/Chart.yaml
  lidarr/TerminusManifest.yaml
  lidarr/templates/deployment.yaml
Labels: UPDATE

#246 [UPDATE][mastodon][0.0.47]lock image
  mastodon/Chart.yaml
  mastodon/TerminusManifest.yaml
  mastodon/templates/apache/deployment.yaml
  mastodon/templates/deployment-mastodon-sidekiq.yaml
  mastodon/templates/deployment-mastodon-streaming.yaml
  mastodon/templates/deployment-mastodon.yaml
  mastodon/templates/elasticsearch/statefulset.yaml
  mastodon/templates/job-mastodon-init.yaml
  mastodon/templates/minio/deployment.yaml
  mastodon/templates/minio/job-mastodon-minio-provisioning.yaml
  mastodon/templates/postgresql/statefulset.yaml
  mastodon/templates/redis/statefulset.yaml
Labels: UPDATE

#247 [UPDATE][mattermost][0.0.7]lock image
  mattermost/Chart.yaml
  mattermost/TerminusManifest.yaml
  mattermost/templates/mattermost.yaml
Labels: UPDATE

#248 [UPDATE][miniflux][0.0.4]lock image
  miniflux/Chart.yaml
  miniflux/TerminusManifest.yaml
  miniflux/templates/db-deployment.yaml
  miniflux/templates/miniflux-deployment.yaml
Labels: UPDATE

#249 [UPDATE][n8n][0.0.9]lock image
  n8n/Chart.yaml
  n8n/TerminusManifest.yaml
  n8n/templates/n8n.yaml
Labels: UPDATE

#250 [UPDATE][navidrome][0.0.8]lock image
  navidrome/Chart.yaml
  navidrome/TerminusManifest.yaml
  navidrome/templates/deployment.yaml
Labels: UPDATE

#251 [UPDATE][nextcloud][0.0.14]lock image
  nextcloud/Chart.yaml
  nextcloud/TerminusManifest.yaml
  nextcloud/templates/deployment.yaml
Labels: UPDATE

#252 [UPDATE][nocodb][0.0.10]lock image
  nocodb/Chart.yaml
  nocodb/TerminusManifest.yaml
  nocodb/templates/deployment.yaml
Labels: UPDATE

#253 [UPDATE][nostream][0.0.7]lock image
  nostream/Chart.yaml
  nostream/TerminusManifest.yaml
  nostream/templates/deployment.yaml
Labels: UPDATE

#254 [UPDATE][novella][0.0.14]lock image
  novella/Chart.yaml
  novella/TerminusManifest.yaml
  novella/templates/deployment.yaml
Labels: UPDATE

#255 [UPDATE][nzbget][0.0.9]lock image
  nzbget/Chart.yaml
  nzbget/TerminusManifest.yaml
  nzbget/templates/deployment.yaml
Labels: UPDATE

#256 [UPDATE][obsidian][0.0.15]lock image
  obsidian/Chart.yaml
  obsidian/TerminusManifest.yaml
  obsidian/templates/deployment.yaml
Labels: UPDATE

#257 [UPDATE][ollama][0.0.13]lock image
  ollama/Chart.yaml
  ollama/TerminusManifest.yaml
  ollama/templates/deployment.yaml
  ollama/templates/openwebui.yaml
Labels: UPDATE

#258 [UPDATE][onlyoffice][0.0.10]lock image
  onlyoffice/Chart.yaml
  onlyoffice/TerminusManifest.yaml
  onlyoffice/templates/deployment.yaml
Labels: UPDATE

#259 [UPDATE][openedaispeech][0.0.8]lock image
  openedaispeech/Chart.yaml
  openedaispeech/TerminusManifest.yaml
  openedaispeech/templates/deployment.yaml
Labels: UPDATE

#260 [UPDATE][openwebui][0.0.14]lock image
  openwebui/Chart.yaml
  openwebui/TerminusManifest.yaml
  openwebui/templates/deployment.yaml
Labels: UPDATE

#261 [UPDATE][penpot][0.0.4]lock image
  penpot/Chart.yaml
  penpot/TerminusManifest.yaml
  penpot/templates/backend/deployment.yaml
  penpot/templates/exporter/deployment.yaml
  penpot/templates/frontend/deployment.yaml
  penpot/templates/redis/deployment.yaml
Labels: UPDATE

#262 [UPDATE][photoprism][0.0.5]lock image
  photoprism/Chart.yaml
  photoprism/TerminusManifest.yaml
  photoprism/templates/deployment.yaml
Labels: UPDATE

#263 [UPDATE][photoview][0.0.3]lock image
  photoview/Chart.yaml
  photoview/TerminusManifest.yaml
  photoview/templates/deployment.yaml
Labels: UPDATE

#264 [UPDATE][prowlarr][0.0.12]lock image
  prowlarr/Chart.yaml
  prowlarr/TerminusManifest.yaml
  prowlarr/templates/deployment.yaml
Labels: UPDATE

#265 [UPDATE][qbittorrent][0.0.11]lock image
  qbittorrent/Chart.yaml
  qbittorrent/TerminusManifest.yaml
  qbittorrent/templates/deployment.yaml
Labels: UPDATE

#266 [UPDATE][radarr][0.0.10]lock image
  radarr/Chart.yaml
  radarr/TerminusManifest.yaml
  radarr/templates/deployment.yaml
Labels: UPDATE

#267 [UPDATE][radicale][0.0.3]lock image
  radicale/Chart.yaml
  radicale/TerminusManifest.yaml
  radicale/templates/all.yaml
Labels: UPDATE

#268 [UPDATE][readarr][0.0.7]lock image
  readarr/Chart.yaml
  readarr/TerminusManifest.yaml
  readarr/templates/deployment.yaml
Labels: UPDATE

#269 [UPDATE][rsshub][0.0.2]lock image
  rsshub/Chart.yaml
  rsshub/TerminusManifest.yaml
  rsshub/templates/browser-less-deployment.yaml
  rsshub/templates/redis-deployment.yaml
  rsshub/templates/rsshub-deployment.yaml
Labels: waiting to submit, UPDATE

#270 [UPDATE][sdwebui][0.0.8]lock image
  sdwebui/Chart.yaml
  sdwebui/TerminusManifest.yaml
  sdwebui/templates/deployment.yaml
Labels: UPDATE

#272 [UPDATE][searxng][0.0.15]lock image
  searxng/Chart.yaml
  searxng/TerminusManifest.yaml
  searxng/templates/deployment.yaml
Labels: UPDATE

#273 [UPDATE][showdoc][0.0.6]lock image
  showdoc/Chart.yaml
  showdoc/TerminusManifest.yaml
  showdoc/templates/showdoc.yaml
Labels: UPDATE

#274 [UPDATE][sickchill][0.0.4]lock image
  sickchill/Chart.yaml
  sickchill/TerminusManifest.yaml
  sickchill/templates/deployment.yaml
Labels: UPDATE

#276 [UPDATE][transmission][0.0.6]lock image
  transmission/Chart.yaml
  transmission/TerminusManifest.yaml
  transmission/templates/deployment.yaml
Labels: UPDATE

#277 [UPDATE][whisper][0.0.7]lock image
  whisper/Chart.yaml
  whisper/TerminusManifest.yaml
  whisper/templates/deployment.yaml
Labels: UPDATE

#278 [UPDATE][wordpress][0.0.16]lock image
  wordpress/Chart.yaml
  wordpress/TerminusManifest.yaml
  wordpress/templates/proxy.yaml
  wordpress/templates/wordpress.yaml
Labels: UPDATE

#279 [UPDATE][devbox][0.0.7]add images manager webhook
  devbox/Chart.yaml
  devbox/TerminusManifest.yaml
  devbox/templates/deployment.yaml
Labels: UPDATE

#280 [UPDATE][immich][0.0.20]Add Redis within the application
  immich/Chart.yaml
  immich/TerminusManifest.yaml
  immich/templates/machine-learning.yaml
  immich/templates/server.yaml
Labels: UPDATE

#281 [UPDATE][onlyoffice][0.0.23]add example web
  onlyoffice/Chart.yaml
  onlyoffice/TerminusManifest.yaml
  onlyoffice/templates/deployment.yaml
Labels: UPDATE

#282 [UPDATE][immich][0.0.21]fix redis host
  immich/Chart.yaml
  immich/TerminusManifest.yaml
  immich/templates/server.yaml
Labels: UPDATE

#283 [UPDATE][onlyoffice][0.0.24]update file path
  onlyoffice/Chart.yaml
  onlyoffice/TerminusManifest.yaml
  onlyoffice/templates/deployment.yaml
Labels: UPDATE

#284 [UPDATE][r4entertainment][0.1.39]add time decay to prioritizing recent content and improve performance
  r4entertainment/Chart.yaml
  r4entertainment/TerminusManifest.yaml
  r4entertainment/owners
  r4entertainment/templates/rank.yaml
  r4entertainment/templates/train.yaml
Labels: UPDATE

#285 [UPDATE][r4techbiz][0.1.39]add time decay to prioritizing recent content and improve performance
  r4techbiz/Chart.yaml
  r4techbiz/TerminusManifest.yaml
  r4techbiz/owners
  r4techbiz/templates/rank.yaml
  r4techbiz/templates/train.yaml
Labels: UPDATE

#286 [UPDATE][r4world][0.1.39]add time decay to prioritizing recent content and improve performance
  r4world/Chart.yaml
  r4world/TerminusManifest.yaml
  r4world/owners
  r4world/templates/rank.yaml
  r4world/templates/train.yaml
Labels: UPDATE

#287 [UPDATE][r4tech][0.1.38]add time decay to prioritizing recent content and improve performance
  r4tech/Chart.yaml
  r4tech/TerminusManifest.yaml
  r4tech/owners
  r4tech/templates/rank.yaml
  r4tech/templates/train.yaml
Labels: UPDATE

#288 [UPDATE][r4sport][0.1.38]add time decay to prioritizing recent content and improve performance
  r4sport/Chart.yaml
  r4sport/TerminusManifest.yaml
  r4sport/owners
  r4sport/templates/rank.yaml
  r4sport/templates/train.yaml
Labels: UPDATE

#289 [UPDATE][r4business][0.1.38]add time decay to prioritizing recent content and improve performance
  r4business/Chart.yaml
  r4business/TerminusManifest.yaml
  r4business/owners
  r4business/templates/rank.yaml
  r4business/templates/train.yaml
Labels: waiting to submit, UPDATE
