Repository beclab/apps, pull requests merged in 2024-11, with the labels that each got.

#379 [UPDATE][comfyui][1.0.5]update version to 0.2.x
  comfyui/Chart.yaml
  comfyui/OlaresManifest.yaml
  comfyui/templates/configmap.yaml
  comfyui/templates/deployment.yaml
Labels: enhancement

#380 [UPDATE][sdwebui][1.0.1]update probe config
  sdwebui/Chart.yaml
  sdwebui/OlaresManifest.yaml
  sdwebui/templates/deployment.yaml
Labels: UPDATE

#381 [UPDATE][devbox][1.0.1]update link and change cfgfile field name
  devbox/Chart.yaml
  devbox/OlaresManifest.yaml
  devbox/i18n/en-US/OlaresManifest.yaml
  devbox/i18n/zh-CN/OlaresManifest.yaml
  devbox/templates/deployment.yaml
Labels: UPDATE

#382 [UPDATE][navidrome][1.0.1]fix dir user & group
  navidrome/Chart.yaml
  navidrome/OlaresManifest.yaml
  navidrome/templates/deployment.yaml
Labels: UPDATE

#383 [UPDATE][showdoc][1.0.1]fix dir user & group
  showdoc/Chart.yaml
  showdoc/OlaresManifest.yaml
  showdoc/templates/showdoc.yaml
Labels: UPDATE

#384 [UPDATE][nzbget][1.0.1]fix dir user & group
  nzbget/Chart.yaml
  nzbget/OlaresManifest.yaml
  nzbget/templates/deployment.yaml
Labels: UPDATE

#386 [UPDATE][photoprism][1.0.1]fix dir user & group
  photoprism/Chart.yaml
  photoprism/OlaresManifest.yaml
  photoprism/templates/deployment.yaml
Labels: UPDATE

#387 [UPDATE][affine][1.0.1]fix dir user & group
  affine/Chart.yaml
  affine/OlaresManifest.yaml
  affine/templates/deployment.yaml
Labels: UPDATE

#388 [UPDATE][bazarr][1.0.1]fix dir user & group
  bazarr/Chart.yaml
  bazarr/OlaresManifest.yaml
  bazarr/templates/deployment.yaml
Labels: UPDATE

#389 [UPDATE][chinesesubfinder][1.0.1]fix dir user & group
  chinesesubfinder/Chart.yaml
  chinesesubfinder/OlaresManifest.yaml
  chinesesubfinder/templates/chinesesubfinder.yaml
Labels: UPDATE

#390 [UPDATE][ghost][1.0.3]fix dir user & group
  ghost/Chart.yaml
  ghost/OlaresManifest.yaml
  ghost/templates/deployment.yaml
Labels: UPDATE

#391 [UPDATE][homeassistant][1.0.2]fix dir user & group
  homeassistant/Chart.yaml
  homeassistant/OlaresManifest.yaml
  homeassistant/templates/deployment.yaml
Labels: UPDATE

#392 [UPDATE][immich][1.0.2]fix dir user & group
  immich/Chart.yaml
  immich/OlaresManifest.yaml
  immich/templates/server.yaml
Labels: UPDATE

#393 [UPDATE][ipfs][1.0.1]fix dir user & group
  ipfs/Chart.yaml
  ipfs/OlaresManifest.yaml
  ipfs/templates/deployment.yaml
Labels: UPDATE

#394 [UPDATE][jellyfin][1.0.2]fix dir user & group
  jellyfin/Chart.yaml
  jellyfin/OlaresManifest.yaml
  jellyfin/templates/deployment.yaml
Labels: UPDATE

#395 [UPDATE][qbittorrent][1.0.1]fix dir user & group
  qbittorrent/Chart.yaml
  qbittorrent/OlaresManifest.yaml
  qbittorrent/templates/deployment.yaml
Labels: UPDATE

#396 [UPDATE][sickchill][1.0.1]fix dir user & group
  sickchill/Chart.yaml
  sickchill/OlaresManifest.yaml
  sickchill/templates/deployment.yaml
Labels: UPDATE

#397 [UPDATE][obsidian][1.0.1]fix dir user & group
  obsidian/Chart.yaml
  obsidian/OlaresManifest.yaml
  obsidian/templates/deployment.yaml
Labels: UPDATE

#398 [UPDATE][nextcloud][1.0.2]fix dir user & group
  nextcloud/Chart.yaml
  nextcloud/OlaresManifest.yaml
  nextcloud/templates/deployment.yaml
Labels: UPDATE

#399 [UPDATE][nocodb][1.0.1]fix dir user & group
  nocodb/Chart.yaml
  nocodb/OlaresManifest.yaml
  nocodb/templates/deployment.yaml
Labels: UPDATE

#400 [UPDATE][farcasterhubble][1.0.1]fix dir user & group
  farcasterhubble/Chart.yaml
  farcasterhubble/OlaresManifest.yaml
  farcasterhubble/templates/deployment.yaml
Labels: UPDATE

#401 [UPDATE][gaianetai][1.0.1]fix dir user & group
  gaianetai/Chart.yaml
  gaianetai/OlaresManifest.yaml
  gaianetai/templates/deployment.yaml
Labels: UPDATE

#402 [UPDATE][geth][1.0.1]fix dir user & group
  geth/Chart.yaml
  geth/OlaresManifest.yaml
  geth/templates/geth.yaml
Labels: UPDATE

#403 [UPDATE][ollama][1.0.1]fix dir user & group
  ollama/Chart.yaml
  ollama/OlaresManifest.yaml
  ollama/templates/deployment.yaml
Labels: UPDATE

#405 [UPDATE][openwebui][1.0.1]fix dir user & group
  openwebui/Chart.yaml
  openwebui/OlaresManifest.yaml
  openwebui/templates/deployment.yaml
Labels: UPDATE

#406 [UPDATE][perplexica][1.0.2]fix dir user & group
  perplexica/Chart.yaml
  perplexica/OlaresManifest.yaml
  perplexica/templates/backend.yaml
Labels: UPDATE

#407 [UPDATE][sdwebui][1.0.2]fix dir user & group
  sdwebui/Chart.yaml
  sdwebui/OlaresManifest.yaml
  sdwebui/templates/deployment.yaml
Labels: UPDATE

#408 [UPDATE][searxng][1.0.1]remove app cache dir
  searxng/Chart.yaml
  searxng/OlaresManifest.yaml
  searxng/templates/deployment.yaml
Labels: UPDATE

#409 [UPDATE][whisper][1.0.1]fix dir user & group
  whisper/Chart.yaml
  whisper/OlaresManifest.yaml
  whisper/templates/deployment.yaml
Labels: UPDATE

#410 [UPDATE][comfyui][1.0.6]config output dir
  comfyui/Chart.yaml
  comfyui/OlaresManifest.yaml
  comfyui/templates/deployment.yaml
Labels: UPDATE

#411 [UPDATE][sdwebui][1.0.3]config output dir
  sdwebui/Chart.yaml
  sdwebui/OlaresManifest.yaml
  sdwebui/templates/deployment.yaml
Labels: UPDATE

#413 [NEW][cmproxy][1.0.0]new app chatgpt-web-midjourney-proxy
  cmproxy/Chart.yaml
  cmproxy/OlaresManifest.yaml
  cmproxy/README.md
  cmproxy/i18n/en-US/OlaresManifest.yaml
  cmproxy/i18n/zh-CN/OlaresManifest.yaml
  cmproxy/owners
  cmproxy/templates/proxy.yaml
  cmproxy/values.yaml
Labels: NEW
