Repository beclab/apps, pull requests merged in 2024-12, with the labels that each got.

#416 [UPDATE][wordpress][1.0.2]fix create root dir by subPath
  wordpress/Chart.yaml
  wordpress/OlaresManifest.yaml
  wordpress/templates/wordpress.yaml
Labels: UPDATE

#418 [UPDATE][sickchill][1.0.2]fix create root dir by subPath
  sickchill/Chart.yaml
  sickchill/OlaresManifest.yaml
  sickchill/templates/deployment.yaml
Labels: UPDATE

#419 [UPDATE][transmission][1.0.2]fix create root dir by subPath
  transmission/Chart.yaml
  transmission/OlaresManifest.yaml
  transmission/templates/deployment.yaml
Labels: UPDATE

#420 [NEW][r4wechat][1.0.0]r4wechat
  r4wechat/.helmignore
  r4wechat/Chart.yaml
  r4wechat/OlaresManifest.yaml
  r4wechat/README.md
  r4wechat/i18n/en-US/OlaresManifest.yaml
  r4wechat/i18n/zh-CN/OlaresManifest.yaml
  r4wechat/owners
  r4wechat/templates/embedding.yaml
  r4wechat/templates/prerank.yaml
  r4wechat/templates/rank.yaml
  r4wechat/templates/train.yaml
  r4wechat/values.yaml
Labels: NEW

#417 [NEW][hasura][1.0.0]new app hasura
  hasura/Chart.yaml
  hasura/OlaresManifest.yaml
  hasura/i18n/en-US/OlaresManifest.yaml
  hasura/i18n/zh-CN/OlaresManifest.yaml
  hasura/owners
  hasura/templates/hasura.yaml
  hasura/values.yaml
Labels: waiting to submit, NEW

#421 [UPDATE][devbox][1.0.2]fix document link
  devbox/Chart.yaml
  devbox/OlaresManifest.yaml
  devbox/templates/deployment.yaml
Labels: UPDATE

#424 [UPDATE][openwebui][1.0.2]fix user 1000
  openwebui/Chart.yaml
  openwebui/OlaresManifest.yaml
  openwebui/templates/deployment.yaml
Labels: UPDATE

#425 [UPDATE][ollama][1.0.3]version up to 0.5.2
  ollama/Chart.yaml
  ollama/OlaresManifest.yaml
  ollama/i18n/en-US/OlaresManifest.yaml
  ollama/i18n/zh-CN/OlaresManifest.yaml
  ollama/templates/clientproxy.yaml
  ollama/templates/deployment.yaml
Labels: UPDATE

#422 [NEW][stablefast3d][1.0.5]new app stable-fast-3d
  stablefast3d/.helmignore
  stablefast3d/Chart.yaml
  stablefast3d/OlaresManifest.yaml
  stablefast3d/i18n/en-US/OlaresManifest.yaml
  stablefast3d/i18n/zh-CN/OlaresManifest.yaml
  stablefast3d/owners
  stablefast3d/templates/deployment.yaml
  stablefast3d/values.yaml
Labels: NEW

#423 [NEW][stablefast3dclient][1.0.0]new app stable-fast-3d-client
  stablefast3dclient/Chart.yaml
  stablefast3dclient/OlaresManifest.yaml
  stablefast3dclient/i18n/en-US/OlaresManifest.yaml
  stablefast3dclient/i18n/zh-CN/OlaresManifest.yaml
  stablefast3dclient/owners
  stablefast3dclient/templates/clientproxy.yaml
  stablefast3dclient/values.yaml
Labels: NEW

#427 [UPDATE][cmproxy][1.0.1]add run as user
  cmproxy/Chart.yaml
  cmproxy/OlaresManifest.yaml
Labels: UPDATE

#428 [UPDATE][hasura][1.0.1]fix os dependency version
  hasura/Chart.yaml
  hasura/OlaresManifest.yaml
Labels: UPDATE

#431 [UPDATE][comfyuiclient][1.0.1]remove header X-Frame-Options SAMEORIGIN
  comfyuiclient/Chart.yaml
  comfyuiclient/OlaresManifest.yaml
  comfyuiclient/templates/clientproxy.yaml
Labels: UPDATE

#432 [UPDATE][hasura][1.0.2]fix middleware requirement
  hasura/Chart.yaml
  hasura/OlaresManifest.yaml
Labels: UPDATE

#436 [UPDATE][comfyui][1.0.8]fix start user & plugin path
  comfyui/Chart.yaml
  comfyui/OlaresManifest.yaml
  comfyui/templates/configmap.yaml
  comfyui/templates/deployment.yaml
Labels: UPDATE

#437 [UPDATE][ollama][1.0.4]fix ollama dependencies min version
  ollama/Chart.yaml
  ollama/OlaresManifest.yaml
Labels: UPDATE

#438 [UPDATE][steamheadless][1.0.4]support sunshine
  steamheadless/Chart.yaml
  steamheadless/OlaresManifest.yaml
  steamheadless/templates/steam.yaml
Labels: UPDATE

#439 [UPDATE][comfyui][1.0.9]Change the output folder to non-root permissions.
  comfyui/Chart.yaml
  comfyui/OlaresManifest.yaml
  comfyui/templates/deployment.yaml
Labels: UPDATE

#433 [UPDATE][devbox][1.0.3]fix os dependency
  devbox/Chart.yaml
  devbox/OlaresManifest.yaml
Labels: UPDATE

#440 [UPDATE][ollama][1.0.5]support cpu
  ollama/Chart.yaml
  ollama/OlaresManifest.yaml
  ollama/templates/deployment.yaml
Labels: UPDATE

#441 [UPDATE][ollama][1.0.6]support cpu on 1.11
  ollama/Chart.yaml
  ollama/OlaresManifest.yaml
  ollama/templates/deployment.yaml
Labels: UPDATE

#442 [UPDATE][searxng][1.0.2]run as user and add engines
  searxng/Chart.yaml
  searxng/OlaresManifest.yaml
  searxng/templates/deployment.yaml
Labels: UPDATE

#443 [UPDATE][perplexica][1.0.3]change open method
  perplexica/Chart.yaml
  perplexica/OlaresManifest.yaml
Labels: UPDATE

#444 [UPDATE][openwebui][1.0.4]support arm on os version 1.10
  openwebui/Chart.yaml
  openwebui/OlaresManifest.yaml
Labels: UPDATE

#446 [UPDATE][mongodb][1.0.2]run as user
  mongodb/Chart.yaml
  mongodb/OlaresManifest.yaml
Labels: UPDATE

#445 [UPDATE][firefox][1.0.1]enhance application stability
  firefox/Chart.yaml
  firefox/OlaresManifest.yaml
  firefox/templates/firefox.yaml
Labels: UPDATE

#447 [UPDATE][wordpress][1.0.3]run as user
  wordpress/Chart.yaml
  wordpress/OlaresManifest.yaml
Labels: UPDATE

#448 [UPDATE][whisper][1.0.2]run as user
  whisper/Chart.yaml
  whisper/OlaresManifest.yaml
Labels: waiting to submit, UPDATE

#449 [UPDATE][searxngclient][1.0.1]run as user
  searxngclient/Chart.yaml
  searxngclient/OlaresManifest.yaml
Labels: UPDATE

#450 [UPDATE][codeserver][1.0.1]run as user
  codeserver/Chart.yaml
  codeserver/OlaresManifest.yaml
Labels: UPDATE

#452 [SUSPEND][difyfusionclient][1.0.0]
  difyfusionclient/.suspend
Labels: SUSPEND

#453 [SUSPEND][difyfusion][1.0.0]
  difyfusion/.suspend
Labels: waiting to submit, SUSPEND

#454 [UPDATE][wordpress][1.0.4]fix reinstall
  wordpress/Chart.yaml
  wordpress/OlaresManifest.yaml
  wordpress/templates/proxy.yaml
  wordpress/templates/wordpress.yaml
Labels: waiting to submit, UPDATE

#455 [UPDATE][jellyfin][1.0.3]change auth level to internal
  jellyfin/Chart.yaml
  jellyfin/OlaresManifest.yaml
Labels: UPDATE

#456 [UPDATE][ghost][1.0.4]run as user
  ghost/Chart.yaml
  ghost/OlaresManifest.yaml
Labels: UPDATE

#457 [UPDATE][chinesesubfinder][1.0.2]run as user
  chinesesubfinder/Chart.yaml
  chinesesubfinder/OlaresManifest.yaml
Labels: UPDATE

#458 [UPDATE][deluge][1.0.1]run as user
  deluge/Chart.yaml
  deluge/OlaresManifest.yaml
Labels: UPDATE

#459 [UPDATE][duplicati][1.0.1]run as user
  duplicati/Chart.yaml
  duplicati/OlaresManifest.yaml
Labels: UPDATE

#460 [UPDATE][n8n][1.0.1]run as user
  n8n/Chart.yaml
  n8n/OlaresManifest.yaml
Labels: UPDATE

#461 [UPDATE][navidrome][1.0.2]run as user
  navidrome/Chart.yaml
  navidrome/OlaresManifest.yaml
Labels: UPDATE

#462 [UPDATE][mattermost][1.0.1]add run as user
  mattermost/Chart.yaml
  mattermost/OlaresManifest.yaml
Labels: UPDATE

#463 [UPDATE][miniflux][1.0.1]add run as user
  miniflux/Chart.yaml
  miniflux/OlaresManifest.yaml
Labels: UPDATE

#464 [UPDATE][sickchill][1.0.3]run as user
  sickchill/Chart.yaml
  sickchill/OlaresManifest.yaml
Labels: UPDATE

#465 [UPDATE][obsidian][1.0.2]run as user
  obsidian/Chart.yaml
  obsidian/OlaresManifest.yaml
Labels: UPDATE

#466 [UPDATE][showdoc][1.0.2]run as user
  showdoc/Chart.yaml
  showdoc/OlaresManifest.yaml
Labels: UPDATE

#467 [UPDATE][rsshub][1.0.1]change auth level and run as user
  rsshub/Chart.yaml
  rsshub/OlaresManifest.yaml
Labels: UPDATE

#468 [UPDATE][nocodb][1.0.2] fix title and run as user
  nocodb/Chart.yaml
  nocodb/OlaresManifest.yaml
  nocodb/i18n/en-US/OlaresManifest.yaml
  nocodb/i18n/zh-CN/OlaresManifest.yaml
Labels: UPDATE

#469 [UPDATE][nextcloud][1.0.3]run as user
  nextcloud/Chart.yaml
  nextcloud/OlaresManifest.yaml
Labels: UPDATE

#451 [UPDATE][comfyui][1.0.13]update version to 0.3.9
  comfyui/Chart.yaml
  comfyui/OlaresManifest.yaml
  comfyui/i18n/en-US/OlaresManifest.yaml
  comfyui/i18n/zh-CN/OlaresManifest.yaml
  comfyui/templates/deployment.yaml
Labels: UPDATE

#470 [UPDATE][comfyuiclient][1.0.2]fix description
  comfyuiclient/Chart.yaml
  comfyuiclient/OlaresManifest.yaml
  comfyuiclient/i18n/en-US/OlaresManifest.yaml
  comfyuiclient/i18n/zh-CN/OlaresManifest.yaml
Labels: UPDATE

#429 [NEW][hunyuan3d][1.0.1]new app hunyuan3d
  hunyuan3d/.helmignore
  hunyuan3d/Chart.yaml
  hunyuan3d/OlaresManifest.yaml
  hunyuan3d/i18n/en-US/OlaresManifest.yaml
  hunyuan3d/i18n/zh-CN/OlaresManifest.yaml
  hunyuan3d/owners
  hunyuan3d/templates/deployment.yaml
  hunyuan3d/values.yaml
Labels: NEW

#430 [NEW][hunyuan3dclient][1.0.0]new app hunyuan3dclient
  hunyuan3dclient/Chart.yaml
  hunyuan3dclient/OlaresManifest.yaml
  hunyuan3dclient/i18n/en-US/OlaresManifest.yaml
  hunyuan3dclient/i18n/zh-CN/OlaresManifest.yaml
  hunyuan3dclient/owners
  hunyuan3dclient/templates/clientproxy.yaml
  hunyuan3dclient/values.yaml
Labels: NEW

#471 [UPDATE][hunyuan3d][1.0.2]fix entrance title
  hunyuan3d/Chart.yaml
  hunyuan3d/OlaresManifest.yaml
Labels: UPDATE

#473 [UPDATE][otmoiclp][1.0.3]update website
  otmoiclp/Chart.yaml
  otmoiclp/OlaresManifest.yaml
Labels: UPDATE

#474 [UPDATE][devbox][1.0.4]upgrade to 0.1.39
  devbox/Chart.yaml
  devbox/OlaresManifest.yaml
  devbox/templates/deployment.yaml
Labels: UPDATE
