Repository beclab/apps, pull requests merged in 2024-09, with the labels that each got.

#291 [UPDATE][photoprism][0.0.6]update AUTH_MODE to public
  photoprism/Chart.yaml
  photoprism/TerminusManifest.yaml
  photoprism/templates/deployment.yaml
Labels: UPDATE

#290 [UPDATE][devbox][0.0.8]fix application, i18n and check-chart
  devbox/Chart.yaml
  devbox/TerminusManifest.yaml
  devbox/templates/deployment.yaml
Labels: UPDATE

#299 [NEW][prometheusclient][0.0.3]add prometheusclient
  prometheusclient/.helmignore
  prometheusclient/Chart.yaml
  prometheusclient/TerminusManifest.yaml
  prometheusclient/i18n/zh/TerminusManifest.yaml
  prometheusclient/owners
  prometheusclient/templates/deployment.yaml
  prometheusclient/values.yaml
Labels: NEW

#298 [NEW][comfyuiclient][0.0.3]comfyui client release version first
  comfyuiclient/Chart.yaml
  comfyuiclient/TerminusManifest.yaml
  comfyuiclient/i18n/zh/TerminusManifest.yaml
  comfyuiclient/owners
  comfyuiclient/templates/clientproxy.yaml
  comfyuiclient/values.yaml
Labels: NEW

#296 [NEW][sdwebuiclient][0.0.8]sdwebui client release version first
  sdwebuiclient/Chart.yaml
  sdwebuiclient/TerminusManifest.yaml
  sdwebuiclient/i18n/zh/TerminusManifest.yaml
  sdwebuiclient/owners
  sdwebuiclient/templates/clientproxy.yaml
  sdwebuiclient/values.yaml
Labels: waiting to submit, NEW

#300 [UPDATE][sdwebui][0.1.13] Support local pre-installed component library and CS structure
  sdwebui/Chart.yaml
  sdwebui/TerminusManifest.yaml
  sdwebui/i18n/zh/TerminusManifest.yaml
  sdwebui/templates/deployment.yaml
Labels: enhancement

#297 [UPDATE][comfyui][0.1.7]Support pre-installed component library and CS structure
  comfyui/Chart.yaml
  comfyui/TerminusManifest.yaml
  comfyui/i18n/zh/TerminusManifest.yaml
  comfyui/templates/deployment.yaml
Labels: UPDATE

#292 [UPDATE][photoprism][0.0.7]fix deployment settings
  photoprism/Chart.yaml
  photoprism/TerminusManifest.yaml
  photoprism/i18n/zh/TerminusManifest.yaml
  photoprism/templates/deployment.yaml
Labels: UPDATE

#301 [UPDATE][ollama][0.1.3]Changed to CS structure
  ollama/Chart.yaml
  ollama/TerminusManifest.yaml
  ollama/i18n/zh/TerminusManifest.yaml
  ollama/templates/clientproxy.yaml
  ollama/templates/deployment.yaml
  ollama/templates/openwebui.yaml
Labels: UPDATE

#302 [UPDATE][searxng][0.1.3]change to CS
  searxng/Chart.yaml
  searxng/TerminusManifest.yaml
  searxng/templates/clientproxy.yaml
  searxng/templates/deployment.yaml
Labels: UPDATE

#311 [UPDATE][gaianetai][0.1.1]change to CS
  gaianetai/Chart.yaml
  gaianetai/TerminusManifest.yaml
  gaianetai/templates/deployment.yaml
Labels: UPDATE

#312 [NEW][gaianetaiclient][0.0.1]gaianetai client
  gaianetaiclient/Chart.yaml
  gaianetaiclient/TerminusManifest.yaml
  gaianetaiclient/i18n/zh/TerminusManifest.yaml
  gaianetaiclient/owners
  gaianetaiclient/templates/clientproxy.yaml
  gaianetaiclient/values.yaml
Labels: NEW

#310 [NEW][immichclient][0.0.3]new app immich client
  immichclient/Chart.yaml
  immichclient/TerminusManifest.yaml
  immichclient/i18n/zh/TerminusManifest.yaml
  immichclient/owners
  immichclient/templates/clientproxy.yaml
  immichclient/values.yaml
Labels: NEW

#309 [UPDATE][immich][0.1.0]change to CS
  immich/Chart.yaml
  immich/TerminusManifest.yaml
  immich/templates/server.yaml
Labels: UPDATE

#308 [UPDATE][openedaispeech][0.1.0]change to CS
  openedaispeech/Chart.yaml
  openedaispeech/TerminusManifest.yaml
  openedaispeech/templates/deployment.yaml
Labels: UPDATE

#307 [UPDATE][openwebui][0.1.1]change to CS
  openwebui/Chart.yaml
  openwebui/TerminusManifest.yaml
  openwebui/templates/deployment.yaml
Labels: UPDATE

#303 [NEW][searxngclient][0.0.1]client for searxng
  searxngclient/Chart.yaml
  searxngclient/TerminusManifest.yaml
  searxngclient/i18n/zh/TerminusManifest.yaml
  searxngclient/owners
  searxngclient/templates/clientproxy.yaml
  searxngclient/values.yaml
Labels: NEW

#304 [UPDATE][whisper][0.1.0]change to CS
  whisper/Chart.yaml
  whisper/TerminusManifest.yaml
  whisper/templates/deployment.yaml
Labels: UPDATE

#306 [UPDATE][perplexica][0.1.6]change to CS
  perplexica/Chart.yaml
  perplexica/TerminusManifest.yaml
  perplexica/templates/backend.yaml
  perplexica/templates/frontend.yaml
  perplexica/templates/ingress.yaml
Labels: UPDATE

#305 [NEW][whisperclient][0.0.1]client for whisper
  whisperclient/Chart.yaml
  whisperclient/TerminusManifest.yaml
  whisperclient/i18n/zh/TerminusManifest.yaml
  whisperclient/owners
  whisperclient/templates/clientproxy.yaml
  whisperclient/values.yaml
Labels: waiting to submit, NEW

#314 [UPDATE][r4tech][0.1.39]Add embedding model to image
  r4tech/Chart.yaml
  r4tech/TerminusManifest.yaml
  r4tech/templates/embedding.yaml
Labels: UPDATE

#315 [UPDATE][r4entertainment][0.1.40]Add embedding model to image
  r4entertainment/Chart.yaml
  r4entertainment/TerminusManifest.yaml
  r4entertainment/templates/embedding.yaml
Labels: UPDATE

#316 [UPDATE][r4business][0.1.39]Add embedding model to image
  r4business/Chart.yaml
  r4business/TerminusManifest.yaml
  r4business/templates/embedding.yaml
Labels: UPDATE

#317 [UPDATE][r4techbiz][0.1.40]Add embedding model to image
  r4techbiz/Chart.yaml
  r4techbiz/TerminusManifest.yaml
  r4techbiz/templates/embedding.yaml
Labels: UPDATE

#318 [UPDATE][r4world][0.1.40]Add embedding model to image
  r4world/Chart.yaml
  r4world/TerminusManifest.yaml
  r4world/templates/embedding.yaml
Labels: UPDATE

#319 [UPDATE][r4sport][0.1.39]Add embedding model to image
  r4sport/Chart.yaml
  r4sport/TerminusManifest.yaml
  r4sport/templates/embedding.yaml
Labels: waiting to submit, UPDATE

#321 [UPDATE][difyfusionclient][0.0.4]fix i18n
  difyfusionclient/Chart.yaml
  difyfusionclient/TerminusManifest.yaml
Labels: UPDATE

#322 [UPDATE][nzbget][0.0.10]fix i18n
  nzbget/Chart.yaml
  nzbget/TerminusManifest.yaml
  nzbget/i18n/zh-CN/TerminusManifest.yaml
Labels: UPDATE

#323 [UPDATE][difyfusion][0.0.3]fix i18n
  difyfusion/Chart.yaml
  difyfusion/TerminusManifest.yaml
Labels: UPDATE

#325 [UPDATE][prometheusclient][0.0.4]fix i18n title
  prometheusclient/Chart.yaml
  prometheusclient/TerminusManifest.yaml
  prometheusclient/i18n/en-US/TerminusManifest.yaml
  prometheusclient/i18n/zh-CN/TerminusManifest.yaml
Labels: UPDATE

#326 [UPDATE][gitlabpure][0.0.51]fix title
  gitlabpure/Chart.yaml
  gitlabpure/TerminusManifest.yaml
  gitlabpure/i18n/en-US/TerminusManifest.yaml
  gitlabpure/i18n/zh-CN/TerminusManifest.yaml
Labels: waiting to submit, UPDATE

#327 [UPDATE][gitlabfusionclient][0.0.29]fix title and description
  gitlabfusionclient/Chart.yaml
  gitlabfusionclient/TerminusManifest.yaml
  gitlabfusionclient/i18n/en-US/TerminusManifest.yaml
  gitlabfusionclient/i18n/zh-CN/TerminusManifest.yaml
Labels: UPDATE

#329 [UPDATE][comfyuiclient][0.0.4]change auth level to internal
  comfyuiclient/Chart.yaml
  comfyuiclient/TerminusManifest.yaml
Labels: UPDATE

#330 [UPDATE][affine][0.0.11]fix i18n
  affine/Chart.yaml
  affine/TerminusManifest.yaml
  affine/i18n/zh-CN/TerminusManifest.yaml
Labels: UPDATE

#331 [UPDATE][affine][0.0.12]fix i18n
  affine/Chart.yaml
  affine/TerminusManifest.yaml
  affine/i18n/zh-CN/TerminusManifest.yaml
Labels: UPDATE

#332 [UPDATE][affine][0.0.13]fix i18n
  affine/Chart.yaml
  affine/TerminusManifest.yaml
  affine/i18n/zh-CN/TerminusManifest.yaml
Labels: UPDATE

#333 [UPDATE][searxng][0.1.4]fix install error
  searxng/Chart.yaml
  searxng/TerminusManifest.yaml
  searxng/templates/deployment.yaml
Labels: UPDATE

#334 [UPDATE][ollama][0.1.4]add client perplexica
  ollama/Chart.yaml
  ollama/TerminusManifest.yaml
Labels: UPDATE

#335 [UPDATE][sdwebui][0.1.16]config output path to userspace
  sdwebui/Chart.yaml
  sdwebui/TerminusManifest.yaml
  sdwebui/templates/deployment.yaml
Labels: UPDATE

#336 [UPDATE][comfyui][0.1.9]config output path to userspace
  comfyui/Chart.yaml
  comfyui/TerminusManifest.yaml
  comfyui/templates/deployment.yaml
Labels: UPDATE

#337 [UPDATE][otmoiclp][0.0.20]up version to v2.2
  otmoiclp/Chart.yaml
  otmoiclp/TerminusManifest.yaml
  otmoiclp/templates/admin.yaml
  otmoiclp/templates/amm.yaml
  otmoiclp/templates/evm_bsc.yaml
  otmoiclp/templates/evm_op.yaml
  otmoiclp/templates/lpnode.yaml
  otmoiclp/templates/market.yaml
  otmoiclp/templates/solana_solana.yaml
Labels: UPDATE
