Repository beclab/apps, pull requests merged in 2024-10, with the labels that each got.

#338 [UPDATE][perplexica][0.1.7]fix api config in local net
  perplexica/Chart.yaml
  perplexica/TerminusManifest.yaml
  perplexica/templates/frontend.yaml
Labels: UPDATE

#339 [UPDATE][sdwebui][0.1.17]set restart type: Recreate
  sdwebui/Chart.yaml
  sdwebui/TerminusManifest.yaml
  sdwebui/templates/deployment.yaml
Labels: UPDATE

#340 [UPDATE][gaianetai][0.1.2]set restart type: Recreate
  gaianetai/Chart.yaml
  gaianetai/TerminusManifest.yaml
  gaianetai/templates/deployment.yaml
Labels: UPDATE

#341 [UPDATE][ollama][0.1.5]set restart type: Recreate
  ollama/Chart.yaml
  ollama/TerminusManifest.yaml
  ollama/templates/deployment.yaml
Labels: UPDATE

#342 [UPDATE][openedaispeech][0.1.1]set restart type: Recreate
  openedaispeech/Chart.yaml
  openedaispeech/TerminusManifest.yaml
  openedaispeech/templates/deployment.yaml
Labels: UPDATE

#343 [UPDATE][whisper][0.1.1]set restart type: Recreate
  whisper/Chart.yaml
  whisper/TerminusManifest.yaml
  whisper/templates/deployment.yaml
Labels: UPDATE

#344 [UPDATE][sdwebui][0.1.18]up version: 1.10.1
  sdwebui/Chart.yaml
  sdwebui/TerminusManifest.yaml
  sdwebui/templates/deployment.yaml
Labels: UPDATE

#345 [UPDATE][immichclient][0.0.4]fix remove liveness probe
  immichclient/Chart.yaml
  immichclient/TerminusManifest.yaml
  immichclient/templates/clientproxy.yaml
Labels: UPDATE

#346 [UPDATE][gaianetaiclient][0.0.2]fix categories
  gaianetaiclient/Chart.yaml
  gaianetaiclient/TerminusManifest.yaml
Labels: UPDATE

#347 [SUSPEND][immichclient][0.0.4]suspend immich client
  immichclient/.suspend
Labels: SUSPEND

#350 [UPDATE][r4techbiz][0.1.41]fix user embedding error when no internet connection
  r4techbiz/Chart.yaml
  r4techbiz/TerminusManifest.yaml
  r4techbiz/templates/embedding.yaml
Labels: UPDATE

#351 [UPDATE][r4techbiz][0.1.42]fix embedding error when upgrade
  r4techbiz/Chart.yaml
  r4techbiz/TerminusManifest.yaml
  r4techbiz/templates/embedding.yaml
Labels: UPDATE

#352 [UPDATE][r4techbiz][0.1.43]fix mount path error
  r4techbiz/Chart.yaml
  r4techbiz/TerminusManifest.yaml
  r4techbiz/templates/embedding.yaml
Labels: UPDATE

#353 [NEW][steamheadless][0.0.7]new app steamheadless
  steamheadless/Chart.yaml
  steamheadless/TerminusManifest.yaml
  steamheadless/i18n/zh/TerminusManifest.yaml
  steamheadless/owners
  steamheadless/templates/steam.yaml
  steamheadless/values.yaml
Labels: NEW

#354 [UPDATE][openwebui][0.1.2]preinstall model
  openwebui/Chart.yaml
  openwebui/TerminusManifest.yaml
  openwebui/templates/deployment.yaml
Labels: UPDATE

#355 [UPDATE][steamheadless][0.0.8]fix i18n
  steamheadless/Chart.yaml
  steamheadless/TerminusManifest.yaml
  steamheadless/i18n/en-US/TerminusManifest.yaml
  steamheadless/i18n/zh-CN/TerminusManifest.yaml
  steamheadless/i18n/zh/TerminusManifest.yaml
Labels: UPDATE

#356 [SUSPEND][calendar][0.0.2]stop listing app due to compatibility issue
  calendar/.suspend
Labels: SUSPEND

#357 [UPDATE][r4tech][0.1.40]fix userembedding
  r4tech/Chart.yaml
  r4tech/TerminusManifest.yaml
  r4tech/templates/embedding.yaml
Labels: UPDATE

#358 [UPDATE][r4world][0.1.41]fix userembedding
  r4world/Chart.yaml
  r4world/TerminusManifest.yaml
  r4world/templates/embedding.yaml
Labels: UPDATE

#359 [UPDATE][r4sport][0.1.40]fix userembedding
  r4sport/Chart.yaml
  r4sport/TerminusManifest.yaml
  r4sport/templates/embedding.yaml
Labels: UPDATE

#360 [UPDATE][r4techbiz][0.1.44]fix userembedding
  r4techbiz/Chart.yaml
  r4techbiz/TerminusManifest.yaml
  r4techbiz/templates/embedding.yaml
Labels: UPDATE

#361 [UPDATE][r4business][0.1.40]fix userembedding
  r4business/Chart.yaml
  r4business/TerminusManifest.yaml
  r4business/templates/embedding.yaml
Labels: UPDATE

#362 [UPDATE][r4entertainment][0.1.41]fix userembedding
  r4entertainment/Chart.yaml
  r4entertainment/TerminusManifest.yaml
  r4entertainment/templates/embedding.yaml
Labels: UPDATE

#364 [UPDATE][sdwebui][0.1.19]config probe
  sdwebui/Chart.yaml
  sdwebui/TerminusManifest.yaml
  sdwebui/templates/deployment.yaml
Labels: UPDATE

#365 [UPDATE][sdwebuiclient][0.0.9]config readiness probe
  sdwebuiclient/Chart.yaml
  sdwebuiclient/TerminusManifest.yaml
  sdwebuiclient/templates/clientproxy.yaml
Labels: UPDATE

#366 [UPDATE][comfyui][0.1.10]config probe
  comfyui/Chart.yaml
  comfyui/TerminusManifest.yaml
  comfyui/templates/configmap.yaml
  comfyui/templates/deployment.yaml
Labels: UPDATE

#367 [UPDATE][comfyuiclient][0.0.5]config probe
  comfyuiclient/Chart.yaml
  comfyuiclient/TerminusManifest.yaml
  comfyuiclient/templates/clientproxy.yaml
Labels: UPDATE

#368 [UPDATE][steamheadless][0.0.10]config probe
  steamheadless/Chart.yaml
  steamheadless/TerminusManifest.yaml
  steamheadless/templates/steam.yaml
Labels: UPDATE

#369 [UPDATE][firefox][0.0.7]support language cn
  firefox/Chart.yaml
  firefox/TerminusManifest.yaml
  firefox/templates/firefox.yaml
Labels: UPDATE

#370 [UPDATE][onlyoffice][0.0.36]change to cs architecture
  onlyoffice/Chart.yaml
  onlyoffice/TerminusManifest.yaml
  onlyoffice/templates/deployment.yaml
Labels: UPDATE

#371 [NEW][onlyofficeclient][0.0.19]new app onlyofice web
  onlyofficeclient/Chart.yaml
  onlyofficeclient/TerminusManifest.yaml
  onlyofficeclient/i18n/en-US/TerminusManifest.yaml
  onlyofficeclient/i18n/zh-CN/TerminusManifest.yaml
  onlyofficeclient/owners
  onlyofficeclient/templates/client.yaml
  onlyofficeclient/templates/proxy.yaml
  onlyofficeclient/values.yaml
Labels: NEW

#372 [UPDATE][onlyoffice][0.0.37]fix title
  onlyoffice/Chart.yaml
  onlyoffice/TerminusManifest.yaml
  onlyoffice/i18n/en-US/TerminusManifest.yaml
  onlyoffice/i18n/zh-CN/TerminusManifest.yaml
Labels: UPDATE
