Repository beclab/apps, pull requests merged in 2025-01, with the labels that each got.

#475 [UPDATE][ollama][1.0.7]change model save path to sharedlib
  ollama/Chart.yaml
  ollama/OlaresManifest.yaml
  ollama/templates/deployment.yaml
Labels: waiting to submit, UPDATE

#477 [UPDATE][onlyofficeclient][1.0.1]fix policies config
  onlyofficeclient/Chart.yaml
  onlyofficeclient/OlaresManifest.yaml
Labels: UPDATE

#478 [UPDATE][onlyoffice][1.0.1]config requiredMemory
  onlyoffice/Chart.yaml
  onlyoffice/OlaresManifest.yaml
Labels: UPDATE

#479 [UPDATE][devbox][1.0.5]fix: change uninstall waittime to 5 minutes
  devbox/Chart.yaml
  devbox/OlaresManifest.yaml
  devbox/i18n/en-US/OlaresManifest.yaml
  devbox/i18n/zh-CN/OlaresManifest.yaml
  devbox/templates/deployment.yaml
Labels: UPDATE

#480 [UPDATE][difyfusion][1.0.1]upgrade to 0.14.2
  difyfusion/.suspend
  difyfusion/Chart.yaml
  difyfusion/OlaresManifest.yaml
  difyfusion/templates/deployment.yaml
Labels: UPDATE

#482 [UPDATE][difyfusion][1.0.2]fix i18n
  difyfusion/Chart.yaml
  difyfusion/OlaresManifest.yaml
  difyfusion/i18n/en-US/OlaresManifest.yaml
  difyfusion/i18n/zh-CN/OlaresManifest.yaml
Labels: UPDATE

#481 [UPDATE][difyfusionclient][1.0.1]upgrade to 0.14.2
  difyfusionclient/.suspend
  difyfusionclient/Chart.yaml
  difyfusionclient/OlaresManifest.yaml
  difyfusionclient/i18n/en-US/OlaresManifest.yaml
  difyfusionclient/i18n/zh-CN/OlaresManifest.yaml
  difyfusionclient/templates/dify_fe_deploy.yaml
Labels: waiting to submit, UPDATE

#483 [UPDATE][comfyui][1.0.15]up version to 0.3.10
  comfyui/Chart.yaml
  comfyui/OlaresManifest.yaml
  comfyui/templates/deployment.yaml
Labels: UPDATE

#484 [UPDATE][sdwebui][1.0.4]config HF_ENDPOINT
  sdwebui/Chart.yaml
  sdwebui/OlaresManifest.yaml
  sdwebui/templates/deployment.yaml
Labels: UPDATE

#485 [UPDATE][openedaispeech][1.0.2]update config: new client Awesome Digital Human
  openedaispeech/Chart.yaml
  openedaispeech/OlaresManifest.yaml
  openedaispeech/templates/deployment.yaml
Labels: UPDATE

#486 [UPDATE][whisper][1.0.3]update config: new client Awesome Digital Human
  whisper/Chart.yaml
  whisper/OlaresManifest.yaml
  whisper/templates/deployment.yaml
Labels: UPDATE

#488 [UPDATE][wordpress][1.0.5]Relaxation of installation deadline
  wordpress/Chart.yaml
  wordpress/OlaresManifest.yaml
  wordpress/templates/wordpress.yaml
Labels: UPDATE

#489 [UPDATE][ollama][1.0.8]new client n8n
  ollama/Chart.yaml
  ollama/OlaresManifest.yaml
Labels: UPDATE

#490 [UPDATE][n8n][1.0.2]new service ollama
  n8n/Chart.yaml
  n8n/OlaresManifest.yaml
Labels: UPDATE

#487 [NEW][awesomedigitalhuman][1.0.2]new app Awesome Digital Human
  awesomedigitalhuman/Chart.yaml
  awesomedigitalhuman/OlaresManifest.yaml
  awesomedigitalhuman/i18n/en-US/OlaresManifest.yaml
  awesomedigitalhuman/i18n/zh-CN/OlaresManifest.yaml
  awesomedigitalhuman/owners
  awesomedigitalhuman/templates/config.yaml
  awesomedigitalhuman/templates/deployment.yaml
  awesomedigitalhuman/values.yaml
Labels: NEW

#491 [UPDATE][onlyofficeclient][1.0.2]add dependencies mandatory
  onlyofficeclient/Chart.yaml
  onlyofficeclient/OlaresManifest.yaml
Labels: UPDATE

#494 [UPDATE][comfyuiclient][1.0.3]
  comfyuiclient/Chart.yaml
  comfyuiclient/OlaresManifest.yaml
Labels: UPDATE

#495 [UPDATE][gaianetaiclient][1.0.1]add dependencies mandatory
  gaianetaiclient/Chart.yaml
  gaianetaiclient/OlaresManifest.yaml
Labels: UPDATE

#496 [UPDATE][stablefast3dclient][1.0.1]add dependencies mandatory
  stablefast3dclient/Chart.yaml
  stablefast3dclient/OlaresManifest.yaml
Labels: UPDATE

#497 [UPDATE][whisperclient][1.0.1]add dependencies mandatory
  whisperclient/Chart.yaml
  whisperclient/OlaresManifest.yaml
Labels: UPDATE

#498 [UPDATE][searxngclient][1.0.2]add dependencies mandatory
  searxngclient/Chart.yaml
  searxngclient/OlaresManifest.yaml
Labels: UPDATE

#499 [UPDATE][hunyuan3dclient][1.0.1]add dependencies mandatory
  hunyuan3dclient/Chart.yaml
  hunyuan3dclient/OlaresManifest.yaml
Labels: UPDATE

#500 [UPDATE][gitlabfusionclient][1.0.1]add dependencies mandatory
  gitlabfusionclient/Chart.yaml
  gitlabfusionclient/OlaresManifest.yaml
Labels: UPDATE

#492 [UPDATE][difyfusionclient][1.0.2]add dependencies mandatory and policy
  difyfusionclient/Chart.yaml
  difyfusionclient/OlaresManifest.yaml
Labels: UPDATE

#502 [UPDATE][difyfusion][1.0.3]fix agent publish and max connection
  difyfusion/Chart.yaml
  difyfusion/OlaresManifest.yaml
  difyfusion/templates/deployment.yaml
Labels: waiting to submit, UPDATE

#503 [UPDATE][awesomedigitalhuman][1.0.3]update description
  awesomedigitalhuman/Chart.yaml
  awesomedigitalhuman/OlaresManifest.yaml
  awesomedigitalhuman/i18n/en-US/OlaresManifest.yaml
  awesomedigitalhuman/i18n/zh-CN/OlaresManifest.yaml
Labels: UPDATE

#504 [UPDATE][n8n][1.0.3]fix config path
  n8n/Chart.yaml
  n8n/OlaresManifest.yaml
  n8n/templates/n8n.yaml
Labels: UPDATE

#505 [UPDATE][difyfusionclient][1.0.4]support external access for published agent
  difyfusionclient/Chart.yaml
  difyfusionclient/OlaresManifest.yaml
Labels: UPDATE

#506 [UPDATE][difyfusion][1.0.4]revoke policies
  difyfusion/Chart.yaml
  difyfusion/OlaresManifest.yaml
Labels: UPDATE

#507 [UPDATE][wordpress][1.0.6]update proxy cpu limit
  wordpress/Chart.yaml
  wordpress/OlaresManifest.yaml
  wordpress/templates/proxy.yaml
Labels: waiting to submit, UPDATE

#508 [SUSPEND][r4wechat][1.0.0]
  r4wechat/.suspend
Labels: SUSPEND

#509 [UPDATE][steamheadless][1.0.5]add acls for remote access
  steamheadless/Chart.yaml
  steamheadless/OlaresManifest.yaml
Labels: UPDATE

#510 [SUSPEND][hunyuan3d][1.0.2]suspend
  hunyuan3d/.suspend
Labels: SUSPEND

#511 [SUSPEND][hunyuan3dclient][1.0.1]suspend
  hunyuan3dclient/.suspend
Labels: SUSPEND

#514 [UPDATE][miniflux][1.0.2]fix default credentials
  miniflux/Chart.yaml
  miniflux/OlaresManifest.yaml
  miniflux/i18n/zh-CN/OlaresManifest.yaml
Labels: UPDATE

#512 [UPDATE][wordpress][1.0.8]made proxy support local network
  wordpress/Chart.yaml
  wordpress/OlaresManifest.yaml
  wordpress/templates/proxy.yaml
Labels: UPDATE

#515 [UPDATE][wordpress][1.0.9]Resolve the lost secret issue.
  wordpress/Chart.yaml
  wordpress/OlaresManifest.yaml
  wordpress/templates/secret.yaml
  wordpress/templates/wordpress.yaml
Labels: UPDATE

#516 [UPDATE][sdwebui][1.0.5]Update the permissions for the AI directory to 1000
  sdwebui/Chart.yaml
  sdwebui/OlaresManifest.yaml
  sdwebui/templates/deployment.yaml
Labels: UPDATE

#517 [UPDATE][comfyui][1.0.16]fix comfyui manager
  comfyui/Chart.yaml
  comfyui/OlaresManifest.yaml
  comfyui/templates/deployment.yaml
Labels: UPDATE

#525 [UPDATE][comfyui][1.0.17]fix web version
  comfyui/Chart.yaml
  comfyui/OlaresManifest.yaml
  comfyui/templates/deployment.yaml
Labels: UPDATE

#524 [UPDATE][difyfusion][1.0.5]fix connection pool config and add sys data permission
  difyfusion/Chart.yaml
  difyfusion/OlaresManifest.yaml
  difyfusion/templates/deployment.yaml
Labels: UPDATE

#526 [UPDATE][chromium][1.0.1]Support Chinese
  chromium/Chart.yaml
  chromium/OlaresManifest.yaml
  chromium/templates/chromium.yaml
Labels: UPDATE

#527 [UPDATE][ollama][1.0.9]Change Ollama Entrance to internal
  ollama/Chart.yaml
  ollama/OlaresManifest.yaml
Labels: UPDATE

#528 [NEW][windows][1.0.0]add windows
  windows/Chart.yaml
  windows/OlaresManifest.yaml
  windows/i18n/en-US/OlaresManifest.yaml
  windows/i18n/zh-CN/OlaresManifest.yaml
  windows/owners
  windows/templates/deployment.yaml
  windows/values.yaml
Labels: NEW

#523 [UPDATE][r4business][1.0.1]Change ranking algorithm
  r4business/Chart.yaml
  r4business/OlaresManifest.yaml
  r4business/templates/embedding.yaml
  r4business/templates/prerank.yaml
  r4business/templates/rank.yaml
  r4business/templates/train.yaml
Labels: UPDATE

#522 [UPDATE][r4entertainment][1.0.1]Change ranking algorithm
  r4entertainment/Chart.yaml
  r4entertainment/OlaresManifest.yaml
  r4entertainment/templates/embedding.yaml
  r4entertainment/templates/prerank.yaml
  r4entertainment/templates/rank.yaml
  r4entertainment/templates/train.yaml
Labels: UPDATE

#521 [UPDATE][r4world][1.0.1]Change ranking algorithm
  r4world/Chart.yaml
  r4world/OlaresManifest.yaml
  r4world/templates/embedding.yaml
  r4world/templates/prerank.yaml
  r4world/templates/rank.yaml
  r4world/templates/train.yaml
Labels: UPDATE

#520 [UPDATE][r4techbiz][1.0.1]Change ranking algorithm
  r4techbiz/Chart.yaml
  r4techbiz/OlaresManifest.yaml
  r4techbiz/templates/embedding.yaml
  r4techbiz/templates/prerank.yaml
  r4techbiz/templates/rank.yaml
  r4techbiz/templates/train.yaml
Labels: UPDATE

#519 [UPDATE][r4tech][1.0.1]Change ranking algorithm
  r4tech/Chart.yaml
  r4tech/OlaresManifest.yaml
  r4tech/templates/embedding.yaml
  r4tech/templates/prerank.yaml
  r4tech/templates/rank.yaml
  r4tech/templates/train.yaml
Labels: UPDATE

#518 [UPDATE][r4sport][1.0.1]Change ranking algorithm
  r4sport/Chart.yaml
  r4sport/OlaresManifest.yaml
  r4sport/templates/embedding.yaml
  r4sport/templates/prerank.yaml
  r4sport/templates/rank.yaml
  r4sport/templates/train.yaml
Labels: UPDATE

#529 [UPDATE][comfyui][1.1.0]upgrade to 0.3.12
  comfyui/Chart.yaml
  comfyui/OlaresManifest.yaml
  comfyui/i18n/en-US/OlaresManifest.yaml
  comfyui/i18n/zh-CN/OlaresManifest.yaml
  comfyui/templates/configmap.yaml
  comfyui/templates/deployment.yaml
Labels: UPDATE

#530 [UPDATE][comfyuiclient][1.0.4]
  comfyuiclient/Chart.yaml
  comfyuiclient/OlaresManifest.yaml
  comfyuiclient/i18n/en-US/OlaresManifest.yaml
  comfyuiclient/i18n/zh-CN/OlaresManifest.yaml
Labels: UPDATE

#535 [UPDATE][ollama][1.0.10]add appRef
  ollama/Chart.yaml
  ollama/OlaresManifest.yaml
Labels: UPDATE

#539 [NEW][lobechat][0.0.1]add lobechat
  lobechat/Chart.yaml
  lobechat/OlaresManifest.yaml
  lobechat/i18n/en-US/OlaresManifest.yaml
  lobechat/i18n/zh-CN/OlaresManifest.yaml
  lobechat/owners
  lobechat/templates/lobechat.yaml
  lobechat/values.yaml
Labels: waiting to submit, NEW

#540 [UPDATE][otmoiclp][1.0.6]support custom token
  otmoiclp/Chart.yaml
  otmoiclp/OlaresManifest.yaml
  otmoiclp/templates/admin.yaml
  otmoiclp/templates/amm.yaml
  otmoiclp/templates/dashboard.yaml
  otmoiclp/templates/lpnode.yaml
  otmoiclp/templates/market.yaml
Labels: UPDATE

#537 [NEW][sdwebuiforgeforcluster][1.0.3]new app sd webui forge
  sdwebuiforgeforcluster/.helmignore
  sdwebuiforgeforcluster/Chart.yaml
  sdwebuiforgeforcluster/OlaresManifest.yaml
  sdwebuiforgeforcluster/i18n/en-US/OlaresManifest.yaml
  sdwebuiforgeforcluster/i18n/zh-CN/OlaresManifest.yaml
  sdwebuiforgeforcluster/owners
  sdwebuiforgeforcluster/templates/deployment.yaml
  sdwebuiforgeforcluster/templates/entrances.yaml
  sdwebuiforgeforcluster/values.yaml
Labels: NEW

#538 [NEW][sdwebuiforge][1.0.3]new app sd webui forge
  sdwebuiforge/Chart.yaml
  sdwebuiforge/OlaresManifest.yaml
  sdwebuiforge/i18n/en-US/OlaresManifest.yaml
  sdwebuiforge/i18n/zh-CN/OlaresManifest.yaml
  sdwebuiforge/owners
  sdwebuiforge/templates/clientproxy.yaml
  sdwebuiforge/values.yaml
Labels: NEW

#541 [UPDATE][comfyuiclient][1.0.5]relax probe
  comfyuiclient/Chart.yaml
  comfyuiclient/OlaresManifest.yaml
  comfyuiclient/templates/clientproxy.yaml
Labels: UPDATE

#542 [UPDATE][comfyui][1.1.1]no envoy
  comfyui/Chart.yaml
  comfyui/OlaresManifest.yaml
  comfyui/templates/clientproxy.yaml
  comfyui/templates/deployment.yaml
Labels: UPDATE

#543 [NEW][qinglong][0.0.1]New app Qinglong
  qinglong/Chart.yaml
  qinglong/OlaresManifest.yaml
  qinglong/i18n/en-US/OlaresManifest.yaml
  qinglong/i18n/zh-CN/OlaresManifest.yaml
  qinglong/owners
  qinglong/templates/qinglong.yaml
  qinglong/values.yaml
Labels: waiting to submit, NEW

#544 [UPDATE][windows][1.0.1]fix version, resource and entrance title
  windows/Chart.yaml
  windows/OlaresManifest.yaml
  windows/templates/deployment.yaml
Labels: UPDATE

#536 [UPDATE][sdwebui][1.0.6]show cache, no envoy, add appRef
  sdwebui/Chart.yaml
  sdwebui/OlaresManifest.yaml
  sdwebui/i18n/en-US/OlaresManifest.yaml
  sdwebui/i18n/zh-CN/OlaresManifest.yaml
  sdwebui/templates/deployment.yaml
  sdwebui/templates/entrances.yaml
Labels: UPDATE

#546 [UPDATE][sdwebuiclient][1.0.3]relax probe
  sdwebuiclient/Chart.yaml
  sdwebuiclient/OlaresManifest.yaml
  sdwebuiclient/templates/clientproxy.yaml
Labels: UPDATE

#547 [UPDATE][ollama][1.0.11]Bidirectional mount
  ollama/Chart.yaml
  ollama/OlaresManifest.yaml
  ollama/templates/deployment.yaml
Labels: UPDATE

#548 [UPDATE][sdwebui][1.0.7]update config global.index-url
  sdwebui/Chart.yaml
  sdwebui/OlaresManifest.yaml
  sdwebui/templates/deployment.yaml
  sdwebui/templates/entrances.yaml
Labels: UPDATE

#549 [UPDATE][sdwebuiforgeforcluster][1.0.4]update config global.index-url
  sdwebuiforgeforcluster/Chart.yaml
  sdwebuiforgeforcluster/OlaresManifest.yaml
  sdwebuiforgeforcluster/templates/deployment.yaml
Labels: UPDATE

#550 [UPDATE][comfyui][1.1.2]update config global.index-url
  comfyui/Chart.yaml
  comfyui/OlaresManifest.yaml
  comfyui/templates/deployment.yaml
Labels: UPDATE

#551 [UPDATE][windows][1.0.2]reduce allocated disk space to 128G
  windows/Chart.yaml
  windows/OlaresManifest.yaml
  windows/templates/deployment.yaml
Labels: UPDATE

#552 [UPDATE][sdwebuiforgeforcluster][1.0.5]fix env HOME
  sdwebuiforgeforcluster/Chart.yaml
  sdwebuiforgeforcluster/OlaresManifest.yaml
  sdwebuiforgeforcluster/templates/deployment.yaml
Labels: UPDATE
