Repository beclab/apps, pull requests merged in 2025-07, with the labels that each got.

#869 [UPDATE][focalboard][1.0.2]fix description
  focalboard/Chart.yaml
  focalboard/OlaresManifest.yaml
  focalboard/i18n/en-US/OlaresManifest.yaml
  focalboard/i18n/zh-CN/OlaresManifest.yaml
  focalboard/templates/deployment.yaml
Labels: UPDATE

#871 [UPDATE][ollama][1.1.1]Upgraded version 0.9.4
  ollama/Chart.yaml
  ollama/OlaresManifest.yaml
  ollama/i18n/en-US/OlaresManifest.yaml
  ollama/i18n/zh-CN/OlaresManifest.yaml
  ollama/templates/deployment.yaml
Labels: UPDATE

#872 [UPDATE][dify][1.1.9]Modify redis permissions
  dify/Chart.yaml
  dify/OlaresManifest.yaml
  dify/templates/server/redis/redis-deployment.yaml
Labels: UPDATE

#877 [UPDATE][pdfmathtranslate][1.0.2]upgrade app versions
  pdfmathtranslate/Chart.yaml
  pdfmathtranslate/OlaresManifest.yaml
  pdfmathtranslate/templates/deployment.yaml
Labels: UPDATE

#876 [UPDATE][deerflow][1.0.2]upgrade app versions
  deerflow/Chart.yaml
  deerflow/OlaresManifest.yaml
  deerflow/i18n/en-US/OlaresManifest.yaml
  deerflow/i18n/zh-CN/OlaresManifest.yaml
  deerflow/templates/configmap.yaml
  deerflow/templates/deployment.yaml
  deerflow/templates/frontend.yaml
Labels: waiting to submit, UPDATE

#874 [UPDATE][cosyvoice][1.0.6]upgrade app versions and update down models
  cosyvoice/Chart.yaml
  cosyvoice/OlaresManifest.yaml
  cosyvoice/templates/clientproxy.yaml
  cosyvoice/templates/cosyvoice.yaml
  cosyvoice/values.yaml
Labels: waiting to submit, UPDATE

#879 [UPDATE][cloudreve][1.0.3]upgrade app versions 4.2
  cloudreve/Chart.yaml
  cloudreve/OlaresManifest.yaml
  cloudreve/templates/cloudreve.yaml
  cloudreve/templates/configmap.yaml
Labels: UPDATE

#880 [UPDATE][cmproxy][1.0.4]upgrade app versions 2.24.9
  cmproxy/Chart.yaml
  cmproxy/OlaresManifest.yaml
  cmproxy/i18n/en-US/OlaresManifest.yaml
  cmproxy/i18n/zh-CN/OlaresManifest.yaml
  cmproxy/templates/proxy.yaml
Labels: UPDATE

#883 [UPDATE][directus][1.0.5]upgrade app versions 11.9.2
  directus/Chart.yaml
  directus/OlaresManifest.yaml
  directus/i18n/en-US/OlaresManifest.yaml
  directus/i18n/zh-CN/OlaresManifest.yaml
  directus/templates/directus.yaml
  directus/templates/redis/deployment.yaml
Labels: waiting to submit, UPDATE

#885 [UPDATE][acestepv2][1.0.2]add promoteImage and fix icon
  acestepv2/Chart.yaml
  acestepv2/OlaresManifest.yaml
Labels: UPDATE

#884 [UPDATE][documenso][1.0.2]upgrade app versions 1.12.1
  documenso/Chart.yaml
  documenso/OlaresManifest.yaml
  documenso/templates/documenso.yaml
Labels: UPDATE

#886 [UPDATE][heygem][1.0.4]add image
  heygem/Chart.yaml
  heygem/OlaresManifest.yaml
Labels: UPDATE

#887 [UPDATE][acestep][1.0.7]update
  acestep/.suspend
  acestep/Chart.yaml
  acestep/OlaresManifest.yaml
Labels: UPDATE

#891 [UPDATE][halo][1.1.2]upgrade app version 2.21.3
  halo/Chart.yaml
  halo/OlaresManifest.yaml
  halo/i18n/en-US/OlaresManifest.yaml
  halo/i18n/zh-CN/OlaresManifest.yaml
  halo/templates/deployment.yaml
Labels: UPDATE

#892 [UPDATE][hoppscotch][1.0.3]upgrade app version 2025.6.0
  hoppscotch/Chart.yaml
  hoppscotch/OlaresManifest.yaml
  hoppscotch/templates/hoppscotch.yaml
Labels: UPDATE

#893 [UPDATE][odoo][1.0.2]upgrade app version 18.0-20250618
  odoo/Chart.yaml
  odoo/OlaresManifest.yaml
  odoo/templates/odoo.yaml
Labels: UPDATE

#895 [UPDATE][sonarr][1.0.1]update version.
  sonarr/Chart.yaml
  sonarr/OlaresManifest.yaml
  sonarr/templates/deployment.yaml
Labels: waiting to submit, UPDATE

#897 [UPDATE][cosyvoice][1.0.8]fix shared app config
  cosyvoice/Chart.yaml
  cosyvoice/OlaresManifest.yaml
Labels: UPDATE

#899 [NEW][jaaz][1.0.2]add new app jaaz
  jaaz/.helmignore
  jaaz/Chart.yaml
  jaaz/OlaresManifest.yaml
  jaaz/i18n/en-US/OlaresManifest.yaml
  jaaz/i18n/zh-CN/OlaresManifest.yaml
  jaaz/owners
  jaaz/templates/configmap.yaml
  jaaz/templates/deployment.yaml
  jaaz/values.yaml
Labels: waiting to submit, NEW

#908 [UPDATE][pdfmathtranslate][1.0.4]upgrade app version 1.9.11
  pdfmathtranslate/Chart.yaml
  pdfmathtranslate/OlaresManifest.yaml
  pdfmathtranslate/templates/deployment.yaml
Labels: UPDATE

#911 [UPDATE][comfyuishare][1.2.13]fix clusterScoped config
  comfyuishare/Chart.yaml
  comfyuishare/OlaresManifest.yaml
Labels: UPDATE

#912 [UPDATE][wise][1.0.6]fix annotation
  wise/Chart.yaml
  wise/OlaresManifest.yaml
  wise/knowledge/Chart.yaml
  wise/wise/Chart.yaml
  wise/wise/templates/front.yaml
Labels: UPDATE

#923 [UPDATE][acestepv2][1.0.4]fix clusterScoped config
  acestepv2/Chart.yaml
  acestepv2/OlaresManifest.yaml
Labels: UPDATE

#922 [UPDATE][cosyvoice][1.0.10]fix clusterScoped config
  cosyvoice/Chart.yaml
  cosyvoice/OlaresManifest.yaml
Labels: UPDATE

#920 [UPDATE][onlyoffice][1.0.6]fix clusterScoped config
  onlyoffice/Chart.yaml
  onlyoffice/OlaresManifest.yaml
Labels: UPDATE

#919 [UPDATE][sdwebuiforgeshare][1.0.4]fix clusterScoped config
  sdwebuiforgeshare/Chart.yaml
  sdwebuiforgeshare/OlaresManifest.yaml
Labels: UPDATE

#918 [UPDATE][sdwebuishare][1.0.10]fix clusterScoped config
  sdwebuishare/Chart.yaml
  sdwebuishare/OlaresManifest.yaml
Labels: UPDATE

#915 [UPDATE][whisperwebui][1.0.7]fix clusterScoped config
  whisperwebui/Chart.yaml
  whisperwebui/OlaresManifest.yaml
Labels: UPDATE

#917 [UPDATE][stablefast3dshare][1.0.4]fix clusterScoped config
  stablefast3dshare/Chart.yaml
  stablefast3dshare/OlaresManifest.yaml
Labels: UPDATE

#925 [UPDATE][chaosmesh][0.0.6]fix: change pause image
  chaosmesh/Chart.yaml
  chaosmesh/OlaresManifest.yaml
  chaosmesh/values.yaml
Labels: waiting to submit, UPDATE

#928 [UPDATE][openedaispeech][1.0.4]add onlyAdmin
  openedaispeech/Chart.yaml
  openedaispeech/OlaresManifest.yaml
Labels: UPDATE

#929 [SUSPEND][chaosmesh][0.0.7]
  chaosmesh/.suspend
  chaosmesh/Chart.yaml
  chaosmesh/OlaresManifest.yaml
Labels: SUSPEND
