Repository beclab/apps, pull requests merged in 2025-06, with the labels that each got.

#836 [NEW][sdwebuiforgeshare][1.0.1]new app SD-webUI-Forge-Share
  sdwebuiforgeshare/.helmignore
  sdwebuiforgeshare/Chart.yaml
  sdwebuiforgeshare/OlaresManifest.yaml
  sdwebuiforgeshare/i18n/en-US/OlaresManifest.yaml
  sdwebuiforgeshare/i18n/zh-CN/OlaresManifest.yaml
  sdwebuiforgeshare/owners
  sdwebuiforgeshare/templates/deployment.yaml
  sdwebuiforgeshare/templates/entrances.yaml
  sdwebuiforgeshare/values.yaml
Labels: NEW

#840 [UPDATE][alist][1.0.4]replace image repo
  alist/Chart.yaml
  alist/OlaresManifest.yaml
  alist/templates/alist.yaml
Labels: UPDATE

#841 [UPDATE][acestep][1.0.5] upload download
  acestep/Chart.yaml
  acestep/OlaresManifest.yaml
  acestep/templates/deployment.yaml
Labels: UPDATE

#843 [UPDATE][comfyuishare][1.2.10]up version 0.3.41
  comfyuishare/Chart.yaml
  comfyuishare/OlaresManifest.yaml
  comfyuishare/i18n/en-US/OlaresManifest.yaml
  comfyuishare/i18n/zh-CN/OlaresManifest.yaml
  comfyuishare/templates/deployment.yaml
Labels: UPDATE

#844 [UPDATE][dify][1.1.8]Dify up version 1.4.3
  dify/Chart.yaml
  dify/OlaresManifest.yaml
  dify/templates/server/api/api-deployment.yaml
  dify/templates/server/plugin/plugin-daemon-deployment.yaml
  dify/templates/server/web-deployment.yaml
  dify/templates/server/worker/worker-deployment.yaml
Labels: UPDATE

#845 [UPDATE][sdwebuiforgeshare][1.0.2]fix lora plugin & update model path config
  sdwebuiforgeshare/Chart.yaml
  sdwebuiforgeshare/OlaresManifest.yaml
  sdwebuiforgeshare/templates/deployment.yaml
Labels: UPDATE

#854 [NEW][acestepv2][1.0.1]add app acestep
  acestepv2/.helmignore
  acestepv2/Chart.yaml
  acestepv2/OlaresManifest.yaml
  acestepv2/i18n/en-US/OlaresManifest.yaml
  acestepv2/i18n/zh-CN/OlaresManifest.yaml
  acestepv2/owners
  acestepv2/templates/clientproxy.yaml
  acestepv2/templates/configmap.yaml
  acestepv2/templates/deployment.yaml
  acestepv2/values.yaml
Labels: NEW

#856 [NEW][secondme][1.0.2]add new app Secondme
  secondme/.helmignore
  secondme/Chart.yaml
  secondme/OlaresManifest.yaml
  secondme/i18n/en-US/OlaresManifest.yaml
  secondme/i18n/zh-CN/OlaresManifest.yaml
  secondme/owners
  secondme/templates/caddy.yaml
  secondme/templates/configmap.yaml
  secondme/templates/secondme.yaml
  secondme/values.yaml
Labels: waiting to submit, NEW

#855 [NEW][pdfmathtranslate][1.0.1]app new app
  pdfmathtranslate/.helmignore
  pdfmathtranslate/Chart.yaml
  pdfmathtranslate/OlaresManifest.yaml
  pdfmathtranslate/i18n/en-US/OlaresManifest.yaml
  pdfmathtranslate/i18n/zh-CN/OlaresManifest.yaml
  pdfmathtranslate/owners
  pdfmathtranslate/templates/configmap.yaml
  pdfmathtranslate/templates/deployment.yaml
  pdfmathtranslate/values.yaml
Labels: NEW

#850 [NEW][deerflow][1.0.1]add new app deerflow
  deerflow/.helmignore
  deerflow/Chart.yaml
  deerflow/OlaresManifest.yaml
  deerflow/i18n/en-US/OlaresManifest.yaml
  deerflow/i18n/zh-CN/OlaresManifest.yaml
  deerflow/owners
  deerflow/templates/clientproxy.yaml
  deerflow/templates/configmap.yaml
  deerflow/templates/deployment.yaml
  deerflow/templates/frontend.yaml
  deerflow/values.yaml
Labels: NEW

#849 [NEW][hunyuan3dv21][1.0.1]add new app hunyuan3dv21
  hunyuan3dv21/.helmignore
  hunyuan3dv21/Chart.yaml
  hunyuan3dv21/OlaresManifest.yaml
  hunyuan3dv21/i18n/en-US/OlaresManifest.yaml
  hunyuan3dv21/i18n/zh-CN/OlaresManifest.yaml
  hunyuan3dv21/owners
  hunyuan3dv21/templates/clientproxy.yaml
  hunyuan3dv21/templates/configmap.yaml
  hunyuan3dv21/templates/deployment.yaml
  hunyuan3dv21/values.yaml
Labels: NEW

#857 [UPDATE][chaosmesh][0.0.4]fix: change image registry and repo
  chaosmesh/Chart.yaml
  chaosmesh/OlaresManifest.yaml
  chaosmesh/values.yaml
Labels: UPDATE

#862 [UPDATE][audiobookshelf][1.0.1] Support data sharing between host and application
  audiobookshelf/Chart.yaml
  audiobookshelf/OlaresManifest.yaml
  audiobookshelf/templates/deployment.yaml
Labels: UPDATE
