Repository beclab/apps, pull requests merged in 2025-04, with the labels that each got.

#666 [NEW][dify][1.1.0]add dify one pack
  dify/.helmignore
  dify/Chart.yaml
  dify/OlaresManifest.yaml
  dify/i18n/en-US/OlaresManifest.yaml
  dify/i18n/zh-CN/OlaresManifest.yaml
  dify/owners
  dify/templates/client/client.yaml
  dify/templates/server/api/api-deployment.yaml
  dify/templates/server/api/api-service.yaml
  dify/templates/server/nginx/nginx-cm0-configmap.yaml
  dify/templates/server/nginx/nginx-cm1-configmap.yaml
  dify/templates/server/nginx/nginx-cm2-configmap.yaml
  dify/templates/server/nginx/nginx-cm3-configmap.yaml
  dify/templates/server/nginx/nginx-cm4-configmap.yaml
  dify/templates/server/nginx/nginx-cm5-configmap.yaml
  dify/templates/server/nginx/nginx-deployment.yaml
  dify/templates/server/nginx/nginx-service.yaml
  dify/templates/server/plugin/plugin-daemon-deployment.yaml
  dify/templates/server/plugin/plugin_daemon-service.yaml
  dify/templates/server/redis/redis-deployment.yaml
  dify/templates/server/redis/redis-service.yaml
  dify/templates/server/sandbox/sandbox-cm0-configmap.yaml
  dify/templates/server/sandbox/sandbox-cm1-configmap.yaml
  dify/templates/server/sandbox/sandbox-deployment.yaml
  dify/templates/server/sandbox/sandbox-service.yaml
  dify/templates/server/ssrf/ssrf-proxy-cm0-configmap.yaml
  dify/templates/server/ssrf/ssrf-proxy-cm1-configmap.yaml
  dify/templates/server/ssrf/ssrf-proxy-deployment.yaml
  dify/templates/server/ssrf/ssrf-proxy-service.yaml
  dify/templates/server/web-deployment.yaml
  dify/templates/server/web-service.yaml
  dify/templates/server/worker/worker-deployment.yaml
  dify/templates/server/worker/worker-service.yaml
  dify/values.yaml
Labels: waiting to submit, NEW

#668 [UPDATE][mtranserver][1.0.2] update app version and proxy
  mtranserver/Chart.yaml
  mtranserver/OlaresManifest.yaml
  mtranserver/templates/clientproxy.yaml
  mtranserver/templates/mtranserver.yaml
Labels: waiting to submit, UPDATE

#669 [NEW][redroid][1.0.1] new app redroid
  redroid/.helmignore
  redroid/Chart.yaml
  redroid/OlaresManifest.yaml
  redroid/i18n/en-US/OlaresManifest.yaml
  redroid/i18n/zh-CN/OlaresManifest.yaml
  redroid/owners
  redroid/templates/redroid.yaml
  redroid/values.yaml
Labels: waiting to submit, NEW

#671 [UPDATE][windows][1.0.8]fix: windows change tailscale acl
  windows/Chart.yaml
  windows/OlaresManifest.yaml
Labels: UPDATE

#670 [UPDATE][wewerss][1.0.2] update wewerss remove .suspend file
  wewerss/.suspend
  wewerss/Chart.yaml
  wewerss/OlaresManifest.yaml
  wewerss/i18n/en-US/OlaresManifest.yaml
  wewerss/i18n/zh-CN/OlaresManifest.yaml
  wewerss/templates/mysql/deployment.yaml
  wewerss/templates/secret.yaml
  wewerss/templates/wewerss.yaml
  wewerss/values.yaml
Labels: waiting to submit, UPDATE

#672 [NEW][seatable][1.0.1]new app sealable
  seatable/.helmignore
  seatable/Chart.yaml
  seatable/OlaresManifest.yaml
  seatable/i18n/en-US/OlaresManifest.yaml
  seatable/i18n/zh-CN/OlaresManifest.yaml
  seatable/owners
  seatable/templates/clientproxy.yaml
  seatable/templates/configmap.yaml
  seatable/templates/mariadb/deployment.yaml
  seatable/templates/mariadb/service.yaml
  seatable/templates/redis/deployment.yaml
  seatable/templates/redis/service.yaml
  seatable/templates/seatable.yaml
  seatable/values.yaml
Labels: waiting to submit, NEW

#673 [UPDATE][wewerss][1.0.3] update wewerss upgrade description
  wewerss/Chart.yaml
  wewerss/OlaresManifest.yaml
  wewerss/i18n/en-US/OlaresManifest.yaml
  wewerss/i18n/zh-CN/OlaresManifest.yaml
Labels: UPDATE

#674 [UPDATE][steamheadless][1.0.7]update acls
  steamheadless/Chart.yaml
  steamheadless/OlaresManifest.yaml
  steamheadless/owners
Labels: UPDATE

#675 [UPDATE][wewerss][1.0.4]remove SERVER_ORIGIN_URL add proxy
  wewerss/Chart.yaml
  wewerss/OlaresManifest.yaml
  wewerss/templates/clientproxy.yaml
  wewerss/templates/wewerss.yaml
Labels: UPDATE

#676 [UPDATE][seatable][1.0.2] update proxy rule
  seatable/Chart.yaml
  seatable/OlaresManifest.yaml
  seatable/templates/clientproxy.yaml
Labels: UPDATE

#677 [UPDATE][difyfusion][1.0.7]remove suspend
  difyfusion/.suspend
  difyfusion/Chart.yaml
  difyfusion/OlaresManifest.yaml
  difyfusion/i18n/en-US/OlaresManifest.yaml
  difyfusion/i18n/zh-CN/OlaresManifest.yaml
Labels: UPDATE

#678 [UPDATE][difyfusionclient][1.0.8]remove suspend
  difyfusionclient/.suspend
  difyfusionclient/Chart.yaml
  difyfusionclient/OlaresManifest.yaml
  difyfusionclient/i18n/en-US/OlaresManifest.yaml
  difyfusionclient/i18n/zh-CN/OlaresManifest.yaml
Labels: UPDATE

#680 [UPDATE][devbox][1.0.6]limit to os below 1.11.6
  devbox/Chart.yaml
  devbox/OlaresManifest.yaml
Labels: waiting to submit, UPDATE

#681 [SUSPEND][devbox][1.0.7]suspend devbox
  devbox/.suspend
  devbox/Chart.yaml
  devbox/OlaresManifest.yaml
Labels: SUSPEND

#683 [UPDATE][coder][1.0.2]add images
  coder/Chart.yaml
  coder/OlaresManifest.yaml
Labels: UPDATE

#687 [UPDATE][wewerss][1.0.5] update mysql args and authLevel
  wewerss/Chart.yaml
  wewerss/OlaresManifest.yaml
  wewerss/templates/mysql/deployment.yaml
Labels: merged, UPDATE

#688 [UPDATE][cloudreve][1.0.2]add images
  cloudreve/Chart.yaml
  cloudreve/OlaresManifest.yaml
Labels: UPDATE

#689 [UPDATE][windows][1.0.9]Add client link
  windows/Chart.yaml
  windows/OlaresManifest.yaml
Labels: UPDATE

#690 [UPDATE][windows][1.0.10]fix android client link
  windows/Chart.yaml
  windows/OlaresManifest.yaml
Labels: UPDATE

#691 [UPDATE][wewerss][1.0.6]fix description
  wewerss/Chart.yaml
  wewerss/OlaresManifest.yaml
  wewerss/i18n/en-US/OlaresManifest.yaml
  wewerss/i18n/zh-CN/OlaresManifest.yaml
Labels: UPDATE

#693 [UPDATE][n8n][1.0.4]upgrade to 1.87.2
  n8n/Chart.yaml
  n8n/OlaresManifest.yaml
  n8n/i18n/en-US/OlaresManifest.yaml
  n8n/i18n/zh-CN/OlaresManifest.yaml
  n8n/owners
  n8n/templates/configmap.yaml
  n8n/templates/n8n.yaml
Labels: waiting to submit, UPDATE

#695 [UPDATE][lobechat][0.0.3]upgrade to 1.79.4
  lobechat/Chart.yaml
  lobechat/OlaresManifest.yaml
  lobechat/owners
  lobechat/templates/lobechat.yaml
Labels: enhancement

#696 [UPDATE][ollama][1.0.17]upgrade to 0.6.5
  ollama/Chart.yaml
  ollama/OlaresManifest.yaml
  ollama/i18n/en-US/OlaresManifest.yaml
  ollama/i18n/zh-CN/OlaresManifest.yaml
  ollama/templates/deployment.yaml
Labels: UPDATE

#703 [UPDATE][mtranserver][1.0.3]change to 2.1.0 and add img >
  mtranserver/Chart.yaml
  mtranserver/OlaresManifest.yaml
  mtranserver/i18n/en-US/OlaresManifest.yaml
  mtranserver/i18n/zh-CN/OlaresManifest.yaml
  mtranserver/templates/mtranserver.yaml
Labels: waiting to submit, UPDATE

#702 [NEW][firecrawl][1.0.1]add app firecrawl
  firecrawl/.helmignore
  firecrawl/Chart.yaml
  firecrawl/OlaresManifest.yaml
  firecrawl/i18n/en-US/OlaresManifest.yaml
  firecrawl/i18n/zh-CN/OlaresManifest.yaml
  firecrawl/owners
  firecrawl/templates/api.yaml
  firecrawl/templates/clientproxy.yaml
  firecrawl/templates/configmap.yaml
  firecrawl/templates/playwright-service.yaml
  firecrawl/templates/redis/deployment.yaml
  firecrawl/templates/redis/service.yaml
  firecrawl/templates/worker.yaml
  firecrawl/values.yaml
Labels: NEW

#700 [NEW][hoppscotch][1.0.1]add app hoppscotch
  hoppscotch/.helmignore
  hoppscotch/Chart.yaml
  hoppscotch/OlaresManifest.yaml
  hoppscotch/i18n/en-US/OlaresManifest.yaml
  hoppscotch/i18n/zh-CN/OlaresManifest.yaml
  hoppscotch/owners
  hoppscotch/templates/configmap.yaml
  hoppscotch/templates/hoppscotch.yaml
  hoppscotch/values.yaml
Labels: NEW

#699 [NEW][migpttts][1.0.1]add app migpttts
  migpttts/.helmignore
  migpttts/Chart.yaml
  migpttts/OlaresManifest.yaml
  migpttts/i18n/en-US/OlaresManifest.yaml
  migpttts/i18n/zh-CN/OlaresManifest.yaml
  migpttts/owners
  migpttts/templates/clientproxy.yaml
  migpttts/templates/configmap.yaml
  migpttts/templates/migpttts.yaml
  migpttts/values.yaml
Labels: NEW

#705 [UPDATE][steamheadless][1.0.8]fix invalid download address
  steamheadless/Chart.yaml
  steamheadless/OlaresManifest.yaml
  steamheadless/i18n/en-US/OlaresManifest.yaml
  steamheadless/i18n/zh-CN/OlaresManifest.yaml
  steamheadless/templates/steam.yaml
Labels: merged, UPDATE

#706 [UPDATE][excalidraw][1.0.2]add img
  excalidraw/Chart.yaml
  excalidraw/OlaresManifest.yaml
Labels: UPDATE

#704 [UPDATE][wewerss][1.0.7]add image and upgrade description
  wewerss/Chart.yaml
  wewerss/OlaresManifest.yaml
  wewerss/i18n/en-US/OlaresManifest.yaml
  wewerss/i18n/zh-CN/OlaresManifest.yaml
Labels: waiting to submit, UPDATE

#707 [UPDATE][redroid][1.0.2]add img
  redroid/Chart.yaml
  redroid/OlaresManifest.yaml
Labels: UPDATE

#708 [UPDATE][md][1.0.2]add img
  md/Chart.yaml
  md/OlaresManifest.yaml
Labels: UPDATE

#710 [UPDATE][localai][1.0.2]add img
  localai/Chart.yaml
  localai/OlaresManifest.yaml
  localai/templates/localai.yaml
Labels: waiting to submit, UPDATE

#711 [UPDATE][firecrawl][1.0.2] update docker image and config
  firecrawl/Chart.yaml
  firecrawl/OlaresManifest.yaml
  firecrawl/templates/api.yaml
  firecrawl/templates/configmap.yaml
  firecrawl/templates/playwright-service.yaml
  firecrawl/templates/worker.yaml
Labels: UPDATE

#712 [UPDATE][steamheadless][1.0.9]fix title
  steamheadless/Chart.yaml
  steamheadless/OlaresManifest.yaml
  steamheadless/i18n/en-US/OlaresManifest.yaml
  steamheadless/i18n/zh-CN/OlaresManifest.yaml
Labels: UPDATE

#714 [UPDATE][jaegerclient][1.0.1] update app's icon
  jaegerclient/Chart.yaml
  jaegerclient/OlaresManifest.yaml
Labels: UPDATE

#715 [NEW][comfyuishare][1.2.2]Add ComfyUI with Launcher
  comfyuishare/Chart.yaml
  comfyuishare/OlaresManifest.yaml
  comfyuishare/i18n/en-US/OlaresManifest.yaml
  comfyuishare/i18n/zh-CN/OlaresManifest.yaml
  comfyuishare/owners
  comfyuishare/templates/clientproxy.yaml
  comfyuishare/templates/configmap.yaml
  comfyuishare/templates/deployment.yaml
  comfyuishare/values.yaml
Labels: NEW

#721 [UPDATE][r4business][1.0.2]fix rank bug
  r4business/Chart.yaml
  r4business/OlaresManifest.yaml
  r4business/i18n/en-US/OlaresManifest.yaml
  r4business/i18n/zh-CN/OlaresManifest.yaml
  r4business/templates/rank.yaml
  r4business/templates/train.yaml
Labels: UPDATE

#720 [UPDATE][r4techbiz][1.0.2]fix rank bug
  r4techbiz/Chart.yaml
  r4techbiz/OlaresManifest.yaml
  r4techbiz/i18n/en-US/OlaresManifest.yaml
  r4techbiz/i18n/zh-CN/OlaresManifest.yaml
  r4techbiz/templates/rank.yaml
  r4techbiz/templates/train.yaml
Labels: UPDATE

#719 [UPDATE][r4sport][1.0.2]fix rank bug
  r4sport/Chart.yaml
  r4sport/OlaresManifest.yaml
  r4sport/i18n/en-US/OlaresManifest.yaml
  r4sport/i18n/zh-CN/OlaresManifest.yaml
  r4sport/templates/rank.yaml
  r4sport/templates/train.yaml
Labels: UPDATE

#718 [UPDATE][r4world][1.0.2]Fix rank bug
  r4world/Chart.yaml
  r4world/OlaresManifest.yaml
  r4world/i18n/en-US/OlaresManifest.yaml
  r4world/i18n/zh-CN/OlaresManifest.yaml
  r4world/templates/rank.yaml
  r4world/templates/train.yaml
Labels: waiting to submit, UPDATE

#717 [UPDATE][r4tech][1.0.2]fix rank bug
  r4tech/Chart.yaml
  r4tech/OlaresManifest.yaml
  r4tech/i18n/en-US/OlaresManifest.yaml
  r4tech/i18n/zh-CN/OlaresManifest.yaml
  r4tech/templates/rank.yaml
  r4tech/templates/train.yaml
Labels: UPDATE

#716 [UPDATE][r4entertainment][1.0.2]fix rank
  r4entertainment/Chart.yaml
  r4entertainment/OlaresManifest.yaml
  r4entertainment/i18n/en-US/OlaresManifest.yaml
  r4entertainment/i18n/zh-CN/OlaresManifest.yaml
  r4entertainment/templates/rank.yaml
  r4entertainment/templates/train.yaml
Labels: UPDATE

#722 [NEW][facefusion][1.0.1]add facefusion
  facefusion/.helmignore
  facefusion/Chart.yaml
  facefusion/OlaresManifest.yaml
  facefusion/i18n/en-US/OlaresManifest.yaml
  facefusion/i18n/zh-CN/OlaresManifest.yaml
  facefusion/owners
  facefusion/templates/clientproxy.yaml
  facefusion/templates/configmap.yaml
  facefusion/templates/facefusion.yaml
  facefusion/values.yaml
Labels: waiting to submit, NEW

#723 [UPDATE][cmproxy][1.0.2]upgrade to 2.23.8
  cmproxy/Chart.yaml
  cmproxy/OlaresManifest.yaml
  cmproxy/i18n/en-US/OlaresManifest.yaml
  cmproxy/i18n/zh-CN/OlaresManifest.yaml
  cmproxy/owners
  cmproxy/templates/proxy.yaml
Labels: UPDATE

#724 [NEW][cosyvoice][1.0.1]add cosyvoice
  cosyvoice/.helmignore
  cosyvoice/Chart.yaml
  cosyvoice/OlaresManifest.yaml
  cosyvoice/i18n/en-US/OlaresManifest.yaml
  cosyvoice/i18n/zh-CN/OlaresManifest.yaml
  cosyvoice/owners
  cosyvoice/templates/clientproxy.yaml
  cosyvoice/templates/configmap.yaml
  cosyvoice/templates/cosyvoice.yaml
  cosyvoice/values.yaml
Labels: NEW

#725 [NEW][funclip][1.0.1] add funclip
  funclip/.helmignore
  funclip/Chart.yaml
  funclip/OlaresManifest.yaml
  funclip/i18n/en-US/OlaresManifest.yaml
  funclip/i18n/zh-CN/OlaresManifest.yaml
  funclip/owners
  funclip/templates/clientproxy.yaml
  funclip/templates/configmap.yaml
  funclip/templates/funclip.yaml
  funclip/values.yaml
Labels: NEW

#726 [NEW][echomimicv2][1.0.1]add echomimicv2
  echomimicv2/.helmignore
  echomimicv2/Chart.yaml
  echomimicv2/OlaresManifest.yaml
  echomimicv2/i18n/en-US/OlaresManifest.yaml
  echomimicv2/i18n/zh-CN/OlaresManifest.yaml
  echomimicv2/owners
  echomimicv2/templates/clientproxy.yaml
  echomimicv2/templates/configmap.yaml
  echomimicv2/templates/echomimicv2.yaml
  echomimicv2/values.yaml
Labels: NEW

#727 [UPDATE][cosyvoice][1.0.2]adjust resources
  cosyvoice/Chart.yaml
  cosyvoice/OlaresManifest.yaml
  cosyvoice/i18n/en-US/OlaresManifest.yaml
  cosyvoice/i18n/zh-CN/OlaresManifest.yaml
  cosyvoice/templates/clientproxy.yaml
  cosyvoice/templates/cosyvoice.yaml
Labels: waiting to submit, UPDATE

#728 [UPDATE][comfyuishare][1.2.3]add frontend in image
  comfyuishare/Chart.yaml
  comfyuishare/OlaresManifest.yaml
  comfyuishare/templates/clientproxy.yaml
  comfyuishare/templates/configmap.yaml
  comfyuishare/templates/deployment.yaml
Labels: UPDATE

#729 [UPDATE][echomimicv2][1.0.2]fix deployment config
  echomimicv2/Chart.yaml
  echomimicv2/OlaresManifest.yaml
  echomimicv2/i18n/en-US/OlaresManifest.yaml
  echomimicv2/i18n/zh-CN/OlaresManifest.yaml
  echomimicv2/templates/echomimicv2.yaml
Labels: UPDATE

#731 [UPDATE][funclip][1.0.2]fix deployment config
  funclip/Chart.yaml
  funclip/OlaresManifest.yaml
  funclip/i18n/en-US/OlaresManifest.yaml
  funclip/i18n/zh-CN/OlaresManifest.yaml
  funclip/templates/clientproxy.yaml
  funclip/templates/configmap.yaml
  funclip/templates/funclip.yaml
Labels: UPDATE

#732 [UPDATE][facefusion][1.0.2]fix deployment config
  facefusion/Chart.yaml
  facefusion/OlaresManifest.yaml
  facefusion/i18n/en-US/OlaresManifest.yaml
  facefusion/i18n/zh-CN/OlaresManifest.yaml
  facefusion/templates/clientproxy.yaml
  facefusion/templates/facefusion.yaml
Labels: UPDATE

#734 [UPDATE][seatable][1.0.4]update requiredCup 1
  seatable/Chart.yaml
  seatable/OlaresManifest.yaml
  seatable/templates/mariadb/deployment.yaml
  seatable/templates/seatable.yaml
Labels: UPDATE

#733 [UPDATE][dify][1.1.2]up version to 1.2.0
  dify/Chart.yaml
  dify/OlaresManifest.yaml
  dify/i18n/en-US/OlaresManifest.yaml
  dify/i18n/zh-CN/OlaresManifest.yaml
  dify/templates/server/api/api-deployment.yaml
  dify/templates/server/plugin/plugin-daemon-deployment.yaml
  dify/templates/server/sandbox/sandbox-deployment.yaml
  dify/templates/server/ssrf/ssrf-proxy-deployment.yaml
  dify/templates/server/web-deployment.yaml
  dify/templates/server/worker/worker-deployment.yaml
Labels: UPDATE

#736 [UPDATE][dify][1.1.3]fix version
  dify/Chart.yaml
  dify/OlaresManifest.yaml
Labels: UPDATE

#737 [UPDATE][seatable][1.0.5]remove seatable supportArch arm64
  seatable/Chart.yaml
  seatable/OlaresManifest.yaml
Labels: UPDATE

#738 [UPDATE][comfyuishare][1.2.4]fix server host in client
  comfyuishare/Chart.yaml
  comfyuishare/OlaresManifest.yaml
  comfyuishare/templates/clientproxy.yaml
Labels: UPDATE

#739 [UPDATE][dify][1.1.4]add health check interval for redis
  dify/Chart.yaml
  dify/OlaresManifest.yaml
  dify/templates/server/api/api-deployment.yaml
  dify/templates/server/ssrf/ssrf-proxy-deployment.yaml
Labels: merged, UPDATE

#746 [UPDATE][nextcloud][1.0.4]fix nextcloud bug for External Storage and Home Storage
  nextcloud/Chart.yaml
  nextcloud/OlaresManifest.yaml
  nextcloud/i18n/en-US/OlaresManifest.yaml
  nextcloud/i18n/zh-CN/OlaresManifest.yaml
  nextcloud/owners
  nextcloud/templates/clientproxy.yaml
  nextcloud/templates/configmap.yaml
  nextcloud/templates/deployment.yaml
  nextcloud/values.yaml
Labels: waiting to submit, UPDATE

#749 [UPDATE][steamheadless][1.0.10]fix gpu
  steamheadless/Chart.yaml
  steamheadless/OlaresManifest.yaml
  steamheadless/i18n/en-US/OlaresManifest.yaml
  steamheadless/i18n/zh-CN/OlaresManifest.yaml
  steamheadless/templates/steam.yaml
Labels: UPDATE

#748 [UPDATE][facefusion][1.0.3]fix config
  facefusion/Chart.yaml
  facefusion/OlaresManifest.yaml
  facefusion/i18n/en-US/OlaresManifest.yaml
  facefusion/i18n/zh-CN/OlaresManifest.yaml
  facefusion/templates/facefusion.yaml
Labels: UPDATE

#747 [UPDATE][echomimicv2][1.0.3]Fix required GPU
  echomimicv2/Chart.yaml
  echomimicv2/OlaresManifest.yaml
  echomimicv2/i18n/en-US/OlaresManifest.yaml
  echomimicv2/i18n/zh-CN/OlaresManifest.yaml
  echomimicv2/templates/clientproxy.yaml
  echomimicv2/templates/echomimicv2.yaml
Labels: UPDATE

#743 [UPDATE][funclip][1.0.3]Fix required GPU
  funclip/Chart.yaml
  funclip/OlaresManifest.yaml
  funclip/i18n/en-US/OlaresManifest.yaml
  funclip/i18n/zh-CN/OlaresManifest.yaml
  funclip/templates/funclip.yaml
Labels: UPDATE

#735 [UPDATE][cosyvoice][1.0.4]change default init model
  cosyvoice/Chart.yaml
  cosyvoice/OlaresManifest.yaml
  cosyvoice/i18n/en-US/OlaresManifest.yaml
  cosyvoice/i18n/zh-CN/OlaresManifest.yaml
  cosyvoice/templates/configmap.yaml
  cosyvoice/templates/cosyvoice.yaml
Labels: UPDATE

#751 [UPDATE][seatable][1.0.6]update cpu and memory
  seatable/Chart.yaml
  seatable/OlaresManifest.yaml
  seatable/templates/mariadb/deployment.yaml
  seatable/templates/seatable.yaml
Labels: UPDATE

#752 [UPDATE][seatable][1.0.7]fix bug:init tc-log error
  seatable/Chart.yaml
  seatable/OlaresManifest.yaml
  seatable/templates/mariadb/deployment.yaml
  seatable/templates/seatable.yaml
Labels: UPDATE

#753 [UPDATE][dify][1.1.5]upgrade to 1.3.0
  dify/Chart.yaml
  dify/OlaresManifest.yaml
  dify/i18n/en-US/OlaresManifest.yaml
  dify/i18n/zh-CN/OlaresManifest.yaml
  dify/templates/client/client.yaml
  dify/templates/server/api/api-deployment.yaml
  dify/templates/server/api/api-service.yaml
  dify/templates/server/nginx/nginx-cm0-configmap.yaml
  dify/templates/server/nginx/nginx-cm1-configmap.yaml
  dify/templates/server/nginx/nginx-cm2-configmap.yaml
  dify/templates/server/nginx/nginx-cm3-configmap.yaml
  dify/templates/server/nginx/nginx-cm4-configmap.yaml
  dify/templates/server/nginx/nginx-cm5-configmap.yaml
  dify/templates/server/nginx/nginx-deployment.yaml
  dify/templates/server/nginx/nginx-service.yaml
  dify/templates/server/plugin/plugin-daemon-deployment.yaml
  dify/templates/server/plugin/plugin_daemon-service.yaml
  dify/templates/server/redis/redis-deployment.yaml
  dify/templates/server/redis/redis-service.yaml
  dify/templates/server/sandbox/sandbox-cm0-configmap.yaml
  dify/templates/server/sandbox/sandbox-cm1-configmap.yaml
  dify/templates/server/sandbox/sandbox-deployment.yaml
  dify/templates/server/sandbox/sandbox-service.yaml
  dify/templates/server/ssrf/ssrf-proxy-cm0-configmap.yaml
  dify/templates/server/ssrf/ssrf-proxy-cm1-configmap.yaml
  dify/templates/server/ssrf/ssrf-proxy-deployment.yaml
  dify/templates/server/ssrf/ssrf-proxy-service.yaml
  dify/templates/server/web-deployment.yaml
  dify/templates/server/web-service.yaml
  dify/templates/server/worker/worker-deployment.yaml
  dify/templates/server/worker/worker-service.yaml
Labels: waiting to submit, UPDATE

#754 [UPDATE][comfyuishare][1.2.5]fix en title
  comfyuishare/Chart.yaml
  comfyuishare/OlaresManifest.yaml
  comfyuishare/i18n/en-US/OlaresManifest.yaml
Labels: UPDATE

#755 [UPDATE][immich][1.0.3]update client and app versions
  immich/Chart.yaml
  immich/OlaresManifest.yaml
  immich/owners
  immich/templates/machine-learning.yaml
  immich/templates/server.yaml
Labels: enhancement

#756 [UPDATE][immich][1.0.4]update app versions
  immich/Chart.yaml
  immich/OlaresManifest.yaml
  immich/i18n/en-US/OlaresManifest.yaml
  immich/i18n/zh-CN/OlaresManifest.yaml
  immich/templates/clientproxy.yaml
Labels: UPDATE

#697 [NEW][langbot][1.0.1]add langbot
  langbot/.helmignore
  langbot/Chart.yaml
  langbot/OlaresManifest.yaml
  langbot/i18n/en-US/OlaresManifest.yaml
  langbot/i18n/zh-CN/OlaresManifest.yaml
  langbot/owners
  langbot/templates/langbot.yaml
  langbot/values.yaml
Labels: NEW

#758 [UPDATE][immich][1.0.5]fix description and open method
  immich/Chart.yaml
  immich/OlaresManifest.yaml
  immich/i18n/en-US/OlaresManifest.yaml
  immich/i18n/zh-CN/OlaresManifest.yaml
Labels: UPDATE

#759 [UPDATE][alist][1.0.3]upgrade to 3.44.0
  alist/Chart.yaml
  alist/OlaresManifest.yaml
  alist/i18n/en-US/OlaresManifest.yaml
  alist/i18n/zh-CN/OlaresManifest.yaml
  alist/templates/alist.yaml
Labels: UPDATE

#760 [UPDATE][cmproxy][1.0.3]update app versions 2.24.1
  cmproxy/Chart.yaml
  cmproxy/OlaresManifest.yaml
  cmproxy/i18n/en-US/OlaresManifest.yaml
  cmproxy/i18n/zh-CN/OlaresManifest.yaml
  cmproxy/templates/proxy.yaml
Labels: UPDATE

#763 [UPDATE][ragflow][1.0.6]add img
  ragflow/Chart.yaml
  ragflow/OlaresManifest.yaml
  ragflow/templates/es.yaml
  ragflow/templates/infinity.yaml
  ragflow/templates/minio.yaml
  ragflow/templates/mysql.yaml
  ragflow/templates/ragflow.yaml
  ragflow/templates/redis.yaml
Labels: waiting to submit, UPDATE

#764 [UPDATE][firecrawl][1.0.3]add img
  firecrawl/Chart.yaml
  firecrawl/OlaresManifest.yaml
Labels: UPDATE

#766 [UPDATE][windows][1.0.11]add img
  windows/Chart.yaml
  windows/OlaresManifest.yaml
Labels: UPDATE

#767 [UPDATE][hoppscotch][1.0.2]add img
  hoppscotch/Chart.yaml
  hoppscotch/OlaresManifest.yaml
Labels: UPDATE

#768 [UPDATE][migpt][1.0.2]add imgs
  migpt/Chart.yaml
  migpt/OlaresManifest.yaml
Labels: waiting to submit, UPDATE

#769 [UPDATE][migpttts][1.0.2]add imgs
  migpttts/Chart.yaml
  migpttts/OlaresManifest.yaml
Labels: UPDATE
