Repository beclab/apps, pull requests merged in 2025-09, with the labels that each got.

#1016 [UPDATE][photoprism][1.0.5]update openMethod window
  photoprism/Chart.yaml
  photoprism/OlaresManifest.yaml
  photoprism/templates/deployment.yaml
Labels: UPDATE

#1017 [UPDATE][mongodb]fix: mongodb node affinity selector
  mongodb/templates/deployment.yaml
Labels: waiting to submit

#1025 [UPDATE][rsshub][1.0.3]remove image
  rsshub/Chart.yaml
  rsshub/OlaresManifest.yaml
Labels: UPDATE

#1068 [UPDATE][perplexica][1.1.3]fix init bug
  perplexica/Chart.yaml
  perplexica/OlaresManifest.yaml
  perplexica/templates/1-10-2/deployment.yaml
Labels: UPDATE

#1070 [NEW][crawl4ai][1.0.1]add app crawl4ai
  crawl4ai/.helmignore
  crawl4ai/Chart.yaml
  crawl4ai/OlaresManifest.yaml
  crawl4ai/i18n/en-US/OlaresManifest.yaml
  crawl4ai/i18n/zh-CN/OlaresManifest.yaml
  crawl4ai/owners
  crawl4ai/templates/configmap.yaml
  crawl4ai/templates/crawl4ai.yaml
  crawl4ai/values.yaml
Labels: NEW

#1043 [UPDATE][jellyfin][1.0.6]chang to rbac provider
  jellyfin/Chart.yaml
  jellyfin/OlaresManifest.yaml
  jellyfin/templates/deployment.yaml
Labels: UPDATE

#1063 [UPDATE][sickchill][1.0.5]chang to rbac provider
  sickchill/Chart.yaml
  sickchill/OlaresManifest.yaml
  sickchill/templates/deployment.yaml
Labels: UPDATE

#1062 [UPDATE][secondme][1.0.4]chang to rbac provider
  secondme/Chart.yaml
  secondme/OlaresManifest.yaml
Labels: UPDATE

#1061 [UPDATE][searxng][1.0.10]chang to rbac provider
  searxng/Chart.yaml
  searxng/OlaresManifest.yaml
  searxng/templates/deployment.yaml
Labels: UPDATE

#1057 [UPDATE][readarr][1.0.3]chang to rbac provider
  readarr/Chart.yaml
  readarr/OlaresManifest.yaml
  readarr/templates/deployment.yaml
Labels: UPDATE

#1056 [UPDATE][ragflow][1.0.10]chang to rbac provider
  ragflow/Chart.yaml
  ragflow/OlaresManifest.yaml
Labels: UPDATE

#1055 [UPDATE][radarr][1.0.3]chang to rbac provider
  radarr/Chart.yaml
  radarr/OlaresManifest.yaml
  radarr/templates/deployment.yaml
Labels: UPDATE

#1054 [UPDATE][qbittorrent][1.0.7]chang to rbac provider
  qbittorrent/Chart.yaml
  qbittorrent/OlaresManifest.yaml
  qbittorrent/templates/deployment.yaml
Labels: UPDATE

#1053 [UPDATE][prowlarr][1.0.4]chang to rbac provider
  prowlarr/Chart.yaml
  prowlarr/OlaresManifest.yaml
  prowlarr/templates/deployment.yaml
Labels: UPDATE

#1049 [UPDATE][nzbget][1.0.3]chang to rbac provider
  nzbget/Chart.yaml
  nzbget/OlaresManifest.yaml
  nzbget/templates/deployment.yaml
Labels: UPDATE

#1032 [UPDATE][anythingllm][1.0.4]chang to rbac provider
  anythingllm/Chart.yaml
  anythingllm/OlaresManifest.yaml
  anythingllm/templates/anythingllm.yaml
Labels: UPDATE

#1036 [UPDATE][deerflow][1.0.5]chang to rbac provider
  deerflow/Chart.yaml
  deerflow/OlaresManifest.yaml
Labels: UPDATE

#1047 [UPDATE][migpt][1.0.4]chang to rbac provider
  migpt/Chart.yaml
  migpt/OlaresManifest.yaml
Labels: UPDATE

#1046 [UPDATE][lobechat][1.0.1]chang to rbac provider
  lobechat/Chart.yaml
  lobechat/OlaresManifest.yaml
Labels: UPDATE

#1042 [UPDATE][jaegerclient][1.0.4]chang to rbac provider
  jaegerclient/Chart.yaml
  jaegerclient/OlaresManifest.yaml
  jaegerclient/templates/deployment.yaml
Labels: UPDATE

#1072 [NEW][studio][1.0.12]Add app Studio >
  studio/Chart.yaml
  studio/OlaresManifest.yaml
  studio/i18n/en-US/OlaresManifest.yaml
  studio/i18n/zh-CN/OlaresManifest.yaml
  studio/owners
  studio/studio/Chart.yaml
  studio/studio/templates/front.yaml
  studio/studio/values.yaml
  studio/studioserver/Chart.yaml
  studio/studioserver/templates/studio_server_deploy.yaml
  studio/studioserver/values.yaml
  studio/templates/keep
  studio/values.yaml
Labels: NEW

#1071 [UPDATE][comfyuishare][1.2.21]update to 0.3.60
  comfyuishare/Chart.yaml
  comfyuishare/OlaresManifest.yaml
  comfyuishare/i18n/en-US/OlaresManifest.yaml
  comfyuishare/i18n/zh-CN/OlaresManifest.yaml
  comfyuishare/templates/deployment.yaml
Labels: UPDATE

#1073 [UPDATE][comfyuishare][1.2.22]fix description
  comfyuishare/Chart.yaml
  comfyuishare/OlaresManifest.yaml
  comfyuishare/i18n/en-US/OlaresManifest.yaml
Labels: UPDATE

#1074 [UPDATE][bisheng][1.0.4]update image upgrade version 2.1.1
  bisheng/Chart.yaml
  bisheng/OlaresManifest.yaml
  bisheng/templates/deployment.yaml
Labels: waiting to submit, UPDATE
