Repository beclab/apps, pull requests merged in 2025-05, with the labels that each got.

#771 [UPDATE][dify][1.1.6]fix: dify image image pull policy
  dify/Chart.yaml
  dify/OlaresManifest.yaml
  dify/templates/server/nginx/nginx-deployment.yaml
  dify/templates/server/ssrf/ssrf-proxy-deployment.yaml
Labels: UPDATE

#772 [UPDATE][chaosmesh]fix: change image latest pullpolicy to ifnotpresent
  affine/Chart.yaml
  affine/OlaresManifest.yaml
  affine/templates/deployment.yaml
  astral/Chart.yaml
  astral/OlaresManifest.yaml
  astral/templates/deployment.yaml
  bazarr/Chart.yaml
  bazarr/OlaresManifest.yaml
  bazarr/templates/deployment.yaml
  chaosmesh/Chart.yaml
  chaosmesh/OlaresManifest.yaml
  chaosmesh/templates/prometheus-deployment.yaml
  duplicati/Chart.yaml
  duplicati/OlaresManifest.yaml
  duplicati/templates/deployment.yaml
  geth/Chart.yaml
  geth/OlaresManifest.yaml
  geth/templates/website.yaml
  mongodb/Chart.yaml
  mongodb/OlaresManifest.yaml
  mongodb/templates/deployment.yaml
  navidrome/Chart.yaml
  navidrome/OlaresManifest.yaml
  navidrome/templates/deployment.yaml
  prowlarr/Chart.yaml
  prowlarr/OlaresManifest.yaml
  prowlarr/templates/deployment.yaml
  wordpress/Chart.yaml
  wordpress/OlaresManifest.yaml
  wordpress/templates/wordpress.yaml
Labels: enhancement

#777 [UPDATE][searxng][1.0.4]update app version and fix bug
  searxng/Chart.yaml
  searxng/OlaresManifest.yaml
  searxng/i18n/en-US/OlaresManifest.yaml
  searxng/i18n/zh-CN/OlaresManifest.yaml
  searxng/owners
  searxng/templates/clientproxy.yaml
  searxng/templates/deployment.yaml
Labels: enhancement

#762 [UPDATE][onlyoffice][1.0.2]upgrade and merge one pack
  onlyoffice/Chart.yaml
  onlyoffice/OlaresManifest.yaml
  onlyoffice/i18n/en-US/OlaresManifest.yaml
  onlyoffice/i18n/zh-CN/OlaresManifest.yaml
  onlyoffice/owners
  onlyoffice/templates/client.yaml
  onlyoffice/templates/deployment.yaml
  onlyoffice/templates/proxy.yaml
  onlyoffice/values.yaml
Labels: UPDATE

#775 [UPDATE][openwebui][1.0.6]up version to v0.6.6
  openwebui/Chart.yaml
  openwebui/OlaresManifest.yaml
  openwebui/i18n/en-US/OlaresManifest.yaml
  openwebui/i18n/zh-CN/OlaresManifest.yaml
  openwebui/owners
  openwebui/templates/deployment.yaml
Labels: waiting to submit, UPDATE

#779 [UPDATE][onlyoffice][1.0.3]fix imagePullPolicy
  onlyoffice/Chart.yaml
  onlyoffice/OlaresManifest.yaml
  onlyoffice/templates/client.yaml
  onlyoffice/templates/deployment.yaml
  onlyoffice/templates/proxy.yaml
Labels: UPDATE

#781 [UPDATE][onlyoffice][1.0.4]update deployment name
  onlyoffice/Chart.yaml
  onlyoffice/OlaresManifest.yaml
  onlyoffice/templates/deployment.yaml
  onlyoffice/templates/proxy.yaml
Labels: UPDATE

#782 [UPDATE][affine][1.0.3]update app versions
  .idea/.gitignore
  .idea/apps.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  affine/Chart.yaml
  affine/OlaresManifest.yaml
  affine/i18n/en-US/OlaresManifest.yaml
  affine/i18n/zh-CN/OlaresManifest.yaml
  affine/templates/deployment.yaml
Labels: enhancement

#784 [UPDATE][homeassistant][1.0.4]fix description
  homeassistant/Chart.yaml
  homeassistant/OlaresManifest.yaml
  homeassistant/i18n/en-US/OlaresManifest.yaml
  homeassistant/i18n/zh-CN/OlaresManifest.yaml
  homeassistant/templates/deployment.yaml
Labels: waiting to submit, UPDATE

#780 [NEW][stablefast3dshare][1.0.1]add stable fast 3d
  stablefast3dshare/.helmignore
  stablefast3dshare/Chart.yaml
  stablefast3dshare/OlaresManifest.yaml
  stablefast3dshare/i18n/en-US/OlaresManifest.yaml
  stablefast3dshare/i18n/zh-CN/OlaresManifest.yaml
  stablefast3dshare/owners
  stablefast3dshare/templates/client/clientproxy.yaml
  stablefast3dshare/templates/server/deployment.yaml
  stablefast3dshare/values.yaml
Labels: waiting to submit, NEW

#785 [UPDATE][obsidian][1.0.3]update app versions
  obsidian/Chart.yaml
  obsidian/OlaresManifest.yaml
  obsidian/README.md
  obsidian/i18n/en-US/OlaresManifest.yaml
  obsidian/i18n/zh-CN/OlaresManifest.yaml
  obsidian/templates/deployment.yaml
Labels: waiting to submit, UPDATE

#786 [SUSPEND][stablefast3d][1.0.5]
  stablefast3d/.suspend
Labels: SUSPEND

#787 [SUSPEND][stablefast3dclient][1.0.1]
  stablefast3dclient/.suspend
Labels: SUSPEND

#789 [UPDATE][steamheadless][1.0.11]fix auto discovery
  steamheadless/Chart.yaml
  steamheadless/OlaresManifest.yaml
  steamheadless/templates/steam.yaml
Labels: UPDATE

#790 [UPDATE][jaegerclient][1.0.2]fix image policy
  jaegerclient/Chart.yaml
  jaegerclient/OlaresManifest.yaml
  jaegerclient/i18n/en-US/OlaresManifest.yaml
  jaegerclient/i18n/zh-CN/OlaresManifest.yaml
  jaegerclient/templates/deployment.yaml
Labels: UPDATE

#791 [UPDATE][sdwebuishare][1.0.4]fix directory
  sdwebuishare/Chart.yaml
  sdwebuishare/OlaresManifest.yaml
  sdwebuishare/templates/server/deployment.yaml
Labels: UPDATE

#792 [UPDATE][sdwebuishare][1.0.5]fix load model
  sdwebuishare/Chart.yaml
  sdwebuishare/OlaresManifest.yaml
  sdwebuishare/templates/ client/clientproxy.yaml
  sdwebuishare/templates/server/deployment.yaml
  sdwebuishare/templates/server/entrances.yaml
Labels: UPDATE

#793 [UPDATE][sdwebuishare][1.0.6]fix cacheforstartup path
  sdwebuishare/Chart.yaml
  sdwebuishare/OlaresManifest.yaml
  sdwebuishare/templates/server/deployment.yaml
Labels: UPDATE

#795 [UPDATE][astral][1.0.2]change category
  astral/Chart.yaml
  astral/OlaresManifest.yaml
Labels: UPDATE

#796 [UPDATE][nostream][1.0.1]change categories
  nostream/Chart.yaml
  nostream/OlaresManifest.yaml
Labels: UPDATE

#797 [UPDATE][halo][1.1.1]change categories
  halo/Chart.yaml
  halo/OlaresManifest.yaml
  halo/templates/deployment.yaml
Labels: waiting to submit, UPDATE

#799 [NEW][acestep][1.0.1]add app acestep
  acestep/.helmignore
  acestep/Chart.yaml
  acestep/OlaresManifest.yaml
  acestep/i18n/en-US/OlaresManifest.yaml
  acestep/i18n/zh-CN/OlaresManifest.yaml
  acestep/owners
  acestep/templates/clientproxy.yaml
  acestep/templates/configmap.yaml
  acestep/templates/deployment.yaml
  acestep/values.yaml
Labels: NEW

#800 [UPDATE][n8n][1.0.5]upgrade to 1.93.0
  n8n/Chart.yaml
  n8n/OlaresManifest.yaml
  n8n/i18n/en-US/OlaresManifest.yaml
  n8n/i18n/zh-CN/OlaresManifest.yaml
  n8n/templates/n8n.yaml
Labels: UPDATE

#803 [UPDATE][acestep][1.0.2]fix bugs
  acestep/Chart.yaml
  acestep/OlaresManifest.yaml
  acestep/i18n/en-US/OlaresManifest.yaml
  acestep/templates/configmap.yaml
  acestep/templates/deployment.yaml
Labels: UPDATE

#804 [UPDATE][comfyuishare][1.2.6]launcher up version
  comfyuishare/Chart.yaml
  comfyuishare/OlaresManifest.yaml
  comfyuishare/i18n/en-US/OlaresManifest.yaml
  comfyuishare/i18n/zh-CN/OlaresManifest.yaml
  comfyuishare/templates/deployment.yaml
Labels: UPDATE

#807 [UPDATE][searxng][1.0.5] upgrade app versions and resource limit
  searxng/Chart.yaml
  searxng/OlaresManifest.yaml
  searxng/i18n/en-US/OlaresManifest.yaml
  searxng/i18n/zh-CN/OlaresManifest.yaml
  searxng/templates/deployment.yaml
Labels: UPDATE

#808 [UPDATE][obsidian][1.0.4]upgrade app versions and add resource limit
  obsidian/Chart.yaml
  obsidian/OlaresManifest.yaml
  obsidian/templates/deployment.yaml
Labels: UPDATE

#820 [UPDATE][steamheadless][1.0.12]add gpu-inject
  steamheadless/Chart.yaml
  steamheadless/OlaresManifest.yaml
  steamheadless/i18n/en-US/OlaresManifest.yaml
  steamheadless/i18n/zh-CN/OlaresManifest.yaml
  steamheadless/templates/steam.yaml
Labels: waiting to submit, UPDATE

#818 [UPDATE][sdwebuishare][1.0.7]add gpu-inject
  sdwebuishare/Chart.yaml
  sdwebuishare/OlaresManifest.yaml
  sdwebuishare/i18n/en-US/OlaresManifest.yaml
  sdwebuishare/i18n/zh-CN/OlaresManifest.yaml
  sdwebuishare/templates/server/deployment.yaml
Labels: waiting to submit, UPDATE

#817 [UPDATE][ollama][1.0.18]add gpu-inject
  ollama/Chart.yaml
  ollama/OlaresManifest.yaml
  ollama/i18n/en-US/OlaresManifest.yaml
  ollama/i18n/zh-CN/OlaresManifest.yaml
  ollama/templates/deployment.yaml
Labels: waiting to submit, UPDATE

#816 [UPDATE][maxkb][1.0.3]add gpu-inject
  maxkb/Chart.yaml
  maxkb/OlaresManifest.yaml
  maxkb/i18n/en-US/OlaresManifest.yaml
  maxkb/i18n/zh-CN/OlaresManifest.yaml
  maxkb/templates/maxkb.yaml
Labels: waiting to submit, UPDATE

#821 [UPDATE][xinference][1.0.11]add gpu-inject
  xinference/Chart.yaml
  xinference/OlaresManifest.yaml
  xinference/i18n/en-US/OlaresManifest.yaml
  xinference/i18n/zh-CN/OlaresManifest.yaml
  xinference/templates/deployment.yaml
Labels: waiting to submit, UPDATE

#815 [UPDATE][localai][1.0.3]add gpu-inject
  localai/Chart.yaml
  localai/OlaresManifest.yaml
  localai/i18n/en-US/OlaresManifest.yaml
  localai/i18n/zh-CN/OlaresManifest.yaml
  localai/templates/localai.yaml
Labels: waiting to submit, UPDATE

#814 [UPDATE][llamafactory][1.0.6]add gpu-inject
  llamafactory/Chart.yaml
  llamafactory/OlaresManifest.yaml
  llamafactory/i18n/en-US/OlaresManifest.yaml
  llamafactory/i18n/zh-CN/OlaresManifest.yaml
  llamafactory/templates/deployment.yaml
Labels: waiting to submit, UPDATE

#812 [UPDATE][funclip][1.0.4]add gpu-inject
  funclip/Chart.yaml
  funclip/OlaresManifest.yaml
  funclip/i18n/en-US/OlaresManifest.yaml
  funclip/i18n/zh-CN/OlaresManifest.yaml
  funclip/templates/funclip.yaml
Labels: waiting to submit, UPDATE

#811 [UPDATE][facefusion][1.0.4]add gpu-inject
  facefusion/Chart.yaml
  facefusion/OlaresManifest.yaml
  facefusion/i18n/en-US/OlaresManifest.yaml
  facefusion/i18n/zh-CN/OlaresManifest.yaml
  facefusion/templates/facefusion.yaml
Labels: waiting to submit, UPDATE

#810 [UPDATE][echomimicv2][1.0.4]add gpu-inject
  echomimicv2/Chart.yaml
  echomimicv2/OlaresManifest.yaml
  echomimicv2/i18n/en-US/OlaresManifest.yaml
  echomimicv2/i18n/zh-CN/OlaresManifest.yaml
  echomimicv2/templates/echomimicv2.yaml
Labels: waiting to submit, UPDATE

#809 [UPDATE][cosyvoice][1.0.5]add gpu inject
  cosyvoice/Chart.yaml
  cosyvoice/OlaresManifest.yaml
  cosyvoice/i18n/en-US/OlaresManifest.yaml
  cosyvoice/i18n/zh-CN/OlaresManifest.yaml
  cosyvoice/templates/cosyvoice.yaml
Labels: waiting to submit, UPDATE

#813 [UPDATE][heygem][1.0.3]add gpu-inject
  heygem/Chart.yaml
  heygem/OlaresManifest.yaml
  heygem/i18n/en-US/OlaresManifest.yaml
  heygem/i18n/zh-CN/OlaresManifest.yaml
  heygem/templates/heygem.yaml
  heygem/templates/heygemasr.yaml
  heygem/templates/heygemgenvideo.yaml
Labels: waiting to submit, UPDATE

#822 [UPDATE][sdwebuishare][1.0.8]add input directory
  sdwebuishare/Chart.yaml
  sdwebuishare/OlaresManifest.yaml
  sdwebuishare/i18n/en-US/OlaresManifest.yaml
  sdwebuishare/i18n/zh-CN/OlaresManifest.yaml
  sdwebuishare/templates/server/deployment.yaml
Labels: UPDATE

#823 [UPDATE][dify][1.1.7]up version to 1.4.0
  dify/Chart.yaml
  dify/OlaresManifest.yaml
  dify/i18n/en-US/OlaresManifest.yaml
  dify/i18n/zh-CN/OlaresManifest.yaml
  dify/templates/client/client.yaml
  dify/templates/server/api/api-deployment.yaml
  dify/templates/server/api/api-service.yaml
  dify/templates/server/nginx/nginx-cm0-configmap.yaml
  dify/templates/server/nginx/nginx-cm1-configmap.yaml
  dify/templates/server/nginx/nginx-cm2-configmap.yaml
  dify/templates/server/nginx/nginx-cm3-configmap.yaml
  dify/templates/server/nginx/nginx-cm4-configmap.yaml
  dify/templates/server/nginx/nginx-cm5-configmap.yaml
  dify/templates/server/nginx/nginx-deployment.yaml
  dify/templates/server/nginx/nginx-service.yaml
  dify/templates/server/plugin/plugin-daemon-deployment.yaml
  dify/templates/server/plugin/plugin_daemon-service.yaml
  dify/templates/server/redis/redis-deployment.yaml
  dify/templates/server/redis/redis-service.yaml
  dify/templates/server/sandbox/sandbox-cm0-configmap.yaml
  dify/templates/server/sandbox/sandbox-cm1-configmap.yaml
  dify/templates/server/sandbox/sandbox-deployment.yaml
  dify/templates/server/sandbox/sandbox-service.yaml
  dify/templates/server/ssrf/ssrf-proxy-cm0-configmap.yaml
  dify/templates/server/ssrf/ssrf-proxy-cm1-configmap.yaml
  dify/templates/server/ssrf/ssrf-proxy-deployment.yaml
  dify/templates/server/ssrf/ssrf-proxy-service.yaml
  dify/templates/server/weaviate/weaviate-deployment.yaml
  dify/templates/server/weaviate/weaviate-service.yaml
  dify/templates/server/web-deployment.yaml
  dify/templates/server/web-service.yaml
  dify/templates/server/worker/worker-deployment.yaml
  dify/templates/server/worker/worker-service.yaml
Labels: UPDATE

#824 [UPDATE][comfyuishare][1.2.7]up version to v0.3.34
  comfyuishare/Chart.yaml
  comfyuishare/OlaresManifest.yaml
  comfyuishare/i18n/en-US/OlaresManifest.yaml
  comfyuishare/i18n/zh-CN/OlaresManifest.yaml
  comfyuishare/templates/deployment.yaml
Labels: UPDATE

#826 [UPDATE][redroid][1.0.3]remove default app yyb
  redroid/Chart.yaml
  redroid/OlaresManifest.yaml
  redroid/templates/redroid.yaml
Labels: UPDATE

#830 [UPDATE][nocodb][1.0.3] add smtp config update app versions
  nocodb/Chart.yaml
  nocodb/OlaresManifest.yaml
  nocodb/i18n/en-US/OlaresManifest.yaml
  nocodb/i18n/zh-CN/OlaresManifest.yaml
  nocodb/templates/deployment.yaml
Labels: waiting to submit, UPDATE

#833 [UPDATE][acestep][1.0.4] upload download and share mode
  acestep/Chart.yaml
  acestep/OlaresManifest.yaml
  acestep/i18n/en-US/OlaresManifest.yaml
  acestep/i18n/zh-CN/OlaresManifest.yaml
  acestep/templates/clientproxy.yaml
  acestep/templates/configmap.yaml
  acestep/templates/deployment.yaml
  acestep/values.yaml
Labels: waiting to submit, UPDATE

#835 [UPDATE][funclip][1.0.5]upload download models and share mode
  funclip/Chart.yaml
  funclip/OlaresManifest.yaml
  funclip/i18n/en-US/OlaresManifest.yaml
  funclip/i18n/zh-CN/OlaresManifest.yaml
  funclip/templates/clientproxy.yaml
  funclip/templates/configmap.yaml
  funclip/templates/funclip.yaml
  funclip/values.yaml
Labels: UPDATE
