Repository beclab/apps, pull requests merged in 2025-03, with the labels that each got.

#615 [SUSPEND][gitlabfusionclient][1.0.2]suspend
  gitlabfusionclient/.suspend
Labels: SUSPEND

#616 [SUSPEND][gitlabfusion][1.0.4]suspend
  gitlabfusion/.suspend
Labels: SUSPEND

#617 [UPDATE][windows][1.0.6]fix: disable igpu passthrouth
  windows/Chart.yaml
  windows/OlaresManifest.yaml
  windows/templates/deployment.yaml
Labels: UPDATE

#618 [UPDATE][ollama][1.0.13]Allow Cross-Origin Access and upgrade to 0.5.12
  ollama/Chart.yaml
  ollama/OlaresManifest.yaml
  ollama/i18n/en-US/OlaresManifest.yaml
  ollama/i18n/zh-CN/OlaresManifest.yaml
  ollama/templates/deployment.yaml
Labels: UPDATE

#619 [UPDATE][lobechat][0.0.2]upgrade to 1.68.1
  lobechat/Chart.yaml
  lobechat/OlaresManifest.yaml
  lobechat/i18n/en-US/OlaresManifest.yaml
  lobechat/i18n/zh-CN/OlaresManifest.yaml
  lobechat/templates/lobechat.yaml
Labels: UPDATE

#622 [UPDATE][windows][1.0.7]fix: igpu enable
  windows/Chart.yaml
  windows/OlaresManifest.yaml
  windows/templates/deployment.yaml
Labels: UPDATE

#613 [NEW][uptimekuma][1.0.1]new app uptimekuma
  uptimekuma/.helmignore
  uptimekuma/Chart.yaml
  uptimekuma/OlaresManifest.yaml
  uptimekuma/i18n/en-US/OlaresManifest.yaml
  uptimekuma/i18n/zh-CN/OlaresManifest.yaml
  uptimekuma/owners
  uptimekuma/templates/uptimekuma.yaml
  uptimekuma/values.yaml
Labels: NEW

#624 [UPDATE][xinference][1.0.10]add promoteImage
  xinference/Chart.yaml
  xinference/OlaresManifest.yaml
Labels: UPDATE

#625 [UPDATE][listmonk][1.0.3]add promoteImage
  listmonk/Chart.yaml
  listmonk/OlaresManifest.yaml
Labels: UPDATE

#626 [UPDATE][docmost][1.0.2]add promoteImage
  docmost/Chart.yaml
  docmost/OlaresManifest.yaml
Labels: UPDATE

#627 [UPDATE][directus][1.0.4]add promoteImage
  directus/Chart.yaml
  directus/OlaresManifest.yaml
Labels: UPDATE

#623 [NEW][documenso][1.0.1]new app documenso
  documenso/.helmignore
  documenso/Chart.yaml
  documenso/OlaresManifest.yaml
  documenso/i18n/en-US/OlaresManifest.yaml
  documenso/i18n/zh-CN/OlaresManifest.yaml
  documenso/owners
  documenso/templates/configmap.yaml
  documenso/templates/documenso.yaml
  documenso/templates/secret.yaml
  documenso/values.yaml
Labels: NEW

#621 [NEW][netdata][1.0.1]new app netdata
  netdata/.helmignore
  netdata/Chart.yaml
  netdata/OlaresManifest.yaml
  netdata/i18n/en-US/OlaresManifest.yaml
  netdata/i18n/zh-CN/OlaresManifest.yaml
  netdata/owners
  netdata/templates/configmap.yaml
  netdata/templates/netdata.yaml
  netdata/values.yaml
Labels: NEW

#620 [NEW][coder][1.0.1]new app coder
  coder/.helmignore
  coder/Chart.yaml
  coder/OlaresManifest.yaml
  coder/i18n/en-US/OlaresManifest.yaml
  coder/i18n/zh-CN/OlaresManifest.yaml
  coder/owners
  coder/templates/coder.yaml
  coder/values.yaml
Labels: NEW

#629 [UPDATE][comfyui][1.1.5]support wan video
  comfyui/Chart.yaml
  comfyui/OlaresManifest.yaml
  comfyui/i18n/en-US/OlaresManifest.yaml
  comfyui/i18n/zh-CN/OlaresManifest.yaml
  comfyui/templates/deployment.yaml
Labels: UPDATE

#631 [UPDATE][halo][1.0.7]support smtp
  halo/Chart.yaml
  halo/OlaresManifest.yaml
Labels: UPDATE

#632 [UPDATE][teable][1.0.2]support smtp
  teable/Chart.yaml
  teable/OlaresManifest.yaml
Labels: UPDATE

#633 [UPDATE][prometheusclient][1.0.1]bump version
  prometheusclient/Chart.yaml
  prometheusclient/OlaresManifest.yaml
Labels: UPDATE

#635 [UPDATE][ollama][1.0.14]add shell entrance
  ollama/Chart.yaml
  ollama/OlaresManifest.yaml
  ollama/i18n/en-US/OlaresManifest.yaml
  ollama/i18n/zh-CN/OlaresManifest.yaml
  ollama/owners
  ollama/templates/clientproxy.yaml
  ollama/templates/deployment.yaml
  ollama/templates/terminal.yaml
Labels: UPDATE

#636 [UPDATE][comfyui][1.1.6]no restart
  comfyui/Chart.yaml
  comfyui/OlaresManifest.yaml
  comfyui/templates/deployment.yaml
Labels: UPDATE

#638 [UPDATE][teable][1.0.3]fix upload files
  teable/Chart.yaml
  teable/OlaresManifest.yaml
  teable/templates/configmap.yaml
  teable/templates/teable.yaml
Labels: waiting to submit, UPDATE

#628 [NEW][metabase][1.0.1]add app metabase
  metabase/.helmignore
  metabase/Chart.yaml
  metabase/OlaresManifest.yaml
  metabase/i18n/en-US/OlaresManifest.yaml
  metabase/i18n/zh-CN/OlaresManifest.yaml
  metabase/owners
  metabase/templates/configmap.yaml
  metabase/templates/metabase.yaml
  metabase/values.yaml
Labels: NEW

#630 [NEW][appsmith][1.0.1]new app Appsmith
  appsmith/.helmignore
  appsmith/Chart.yaml
  appsmith/OlaresManifest.yaml
  appsmith/i18n/en-US/OlaresManifest.yaml
  appsmith/i18n/zh-CN/OlaresManifest.yaml
  appsmith/owners
  appsmith/templates/appsmith.yaml
  appsmith/templates/redis/deployment.yaml
  appsmith/templates/redis/service.yaml
  appsmith/values.yaml
Labels: NEW

#640 [UPDATE][comfyui][1.1.7]fix python repo config
  comfyui/Chart.yaml
  comfyui/OlaresManifest.yaml
  comfyui/templates/deployment.yaml
Labels: UPDATE

#641 [UPDATE][comfyuiclient][1.0.7]made readiness be faster
  comfyuiclient/Chart.yaml
  comfyuiclient/OlaresManifest.yaml
  comfyuiclient/templates/clientproxy.yaml
Labels: UPDATE

#639 [UPDATE][halo][1.0.8] upgrade to 2.20.16
  halo/Chart.yaml
  halo/OlaresManifest.yaml
  halo/i18n/en-US/OlaresManifest.yaml
  halo/i18n/zh-CN/OlaresManifest.yaml
  halo/templates/deployment.yaml
Labels: UPDATE

#644 [UPDATE][ollama][1.0.16]upgrade to 0.6.0
  ollama/Chart.yaml
  ollama/OlaresManifest.yaml
  ollama/i18n/en-US/OlaresManifest.yaml
  ollama/i18n/zh-CN/OlaresManifest.yaml
  ollama/templates/deployment.yaml
Labels: UPDATE

#645 [UPDATE][mindmap][1.0.3]add promote image and description
  mindmap/Chart.yaml
  mindmap/OlaresManifest.yaml
  mindmap/i18n/en-US/OlaresManifest.yaml
  mindmap/i18n/zh-CN/OlaresManifest.yaml
Labels: UPDATE

#647 [UPDATE][halo][1.0.9] upgrade to 2.20.17 and fix permission
  halo/Chart.yaml
  halo/OlaresManifest.yaml
  halo/templates/deployment.yaml
Labels: UPDATE

#648 [UPDATE][halo][1.1.0] fix app permission
  halo/Chart.yaml
  halo/OlaresManifest.yaml
  halo/templates/deployment.yaml
Labels: UPDATE

#649 [UPDATE][docmost][1.0.3]upgrade to 0.8.4
  docmost/Chart.yaml
  docmost/OlaresManifest.yaml
  docmost/i18n/en-US/OlaresManifest.yaml
  docmost/i18n/zh-CN/OlaresManifest.yaml
  docmost/templates/docmost.yaml
Labels: UPDATE

#646 [NEW][anythingllm][1.0.1]add app anythingllm
  anythingllm/.helmignore
  anythingllm/Chart.yaml
  anythingllm/OlaresManifest.yaml
  anythingllm/i18n/en-US/OlaresManifest.yaml
  anythingllm/i18n/zh-CN/OlaresManifest.yaml
  anythingllm/owners
  anythingllm/templates/anythingllm.yaml
  anythingllm/templates/configmap.yaml
  anythingllm/templates/secret.yaml
  anythingllm/values.yaml
Labels: NEW

#650 [UPDATE][sdwebui][1.0.10]auto download openai clip vit large patch14
  sdwebui/Chart.yaml
  sdwebui/OlaresManifest.yaml
  sdwebui/templates/deployment.yaml
Labels: UPDATE

#643 [NEW][maxkb][1.0.1]add app maxkb
  maxkb/.helmignore
  maxkb/Chart.yaml
  maxkb/OlaresManifest.yaml
  maxkb/i18n/en-US/OlaresManifest.yaml
  maxkb/i18n/zh-CN/OlaresManifest.yaml
  maxkb/owners
  maxkb/templates/maxkb.yaml
  maxkb/values.yaml
Labels: NEW

#651 [UPDATE][sdwebui][1.0.11]use aria2c download
  sdwebui/Chart.yaml
  sdwebui/OlaresManifest.yaml
  sdwebui/templates/deployment.yaml
Labels: waiting to submit, UPDATE

#642 [NEW][alist][1.0.1]new app Alist
  alist/.helmignore
  alist/Chart.yaml
  alist/OlaresManifest.yaml
  alist/i18n/en-US/OlaresManifest.yaml
  alist/i18n/zh-CN/OlaresManifest.yaml
  alist/owners
  alist/templates/alist.yaml
  alist/values.yaml
Labels: NEW

#652 [NEW][fastgpt][1.0.1]add app fastgpt
  fastgpt/.helmignore
  fastgpt/Chart.yaml
  fastgpt/OlaresManifest.yaml
  fastgpt/i18n/en-US/OlaresManifest.yaml
  fastgpt/i18n/zh-CN/OlaresManifest.yaml
  fastgpt/owners
  fastgpt/templates/aiproxy.yaml
  fastgpt/templates/appconfig.yaml
  fastgpt/templates/baseconfig.yaml
  fastgpt/templates/fastgpt.yaml
  fastgpt/templates/mongo.yaml
  fastgpt/templates/secret.yaml
  fastgpt/values.yaml
Labels: NEW

#653 [NEW][odoo][1.0.1] add app odoo
  odoo/.helmignore
  odoo/Chart.yaml
  odoo/OlaresManifest.yaml
  odoo/i18n/en-US/OlaresManifest.yaml
  odoo/i18n/zh-CN/OlaresManifest.yaml
  odoo/owners
  odoo/templates/configmap.yaml
  odoo/templates/odoo.yaml
  odoo/values.yaml
Labels: NEW

#657 [UPDATE][novella][1.0.1]fix chart format
  novella/Chart.yaml
  novella/OlaresManifest.yaml
  novella/i18n/en-US/OlaresManifest.yaml
  novella/i18n/zh-CN/OlaresManifest.yaml
Labels: UPDATE

#659 [NEW][wewerss][1.0.1]new app sewers
  wewerss/.helmignore
  wewerss/Chart.yaml
  wewerss/OlaresManifest.yaml
  wewerss/i18n/en-US/OlaresManifest.yaml
  wewerss/i18n/zh-CN/OlaresManifest.yaml
  wewerss/owners
  wewerss/templates/mysql/deployment.yaml
  wewerss/templates/wewerss.yaml
  wewerss/values.yaml
Labels: waiting to submit, NEW

#660 [SUSPEND][wewerss][1.0.1]suspend
  wewerss/.suspend
Labels: SUSPEND

#661 [UPDATE][jellyfin][1.0.4]upgrade to 10.10.6
  jellyfin/Chart.yaml
  jellyfin/OlaresManifest.yaml
  jellyfin/i18n/en-US/OlaresManifest.yaml
  jellyfin/i18n/zh-CN/OlaresManifest.yaml
  jellyfin/templates/deployment.yaml
Labels: UPDATE

#662 [SUSPEND][difyfusion][1.0.6]
  difyfusion/.suspend
Labels: SUSPEND

#663 [SUSPEND][difyfusionclient][1.0.7]
  difyfusionclient/.suspend
Labels: SUSPEND

#658 [NEW][cloudreve][1.0.1]new app cloudreve
  cloudreve/.helmignore
  cloudreve/Chart.yaml
  cloudreve/OlaresManifest.yaml
  cloudreve/i18n/en-US/OlaresManifest.yaml
  cloudreve/i18n/zh-CN/OlaresManifest.yaml
  cloudreve/owners
  cloudreve/templates/cloudreve.yaml
  cloudreve/templates/configmap.yaml
  cloudreve/values.yaml
Labels: NEW

#656 [NEW][md][1.0.1] add app md
  md/.helmignore
  md/Chart.yaml
  md/OlaresManifest.yaml
  md/i18n/en-US/OlaresManifest.yaml
  md/i18n/zh-CN/OlaresManifest.yaml
  md/owners
  md/templates/md.yaml
  md/values.yaml
Labels: NEW

#655 [NEW][mtranserver][1.0.1] add app mtranserver
  mtranserver/.helmignore
  mtranserver/Chart.yaml
  mtranserver/OlaresManifest.yaml
  mtranserver/i18n/en-US/OlaresManifest.yaml
  mtranserver/i18n/zh-CN/OlaresManifest.yaml
  mtranserver/owners
  mtranserver/templates/configmap.yaml
  mtranserver/templates/mtranserver.yaml
  mtranserver/values.yaml
Labels: NEW

#654 [NEW][localai][1.0.1] add app LocalAI
  localai/.helmignore
  localai/Chart.yaml
  localai/OlaresManifest.yaml
  localai/i18n/en-US/OlaresManifest.yaml
  localai/i18n/zh-CN/OlaresManifest.yaml
  localai/owners
  localai/templates/configmap.yaml
  localai/templates/localai.yaml
  localai/values.yaml
Labels: waiting to submit, NEW

#664 [NEW][flowise][1.0.1] add app flowise
  flowise/.helmignore
  flowise/Chart.yaml
  flowise/OlaresManifest.yaml
  flowise/i18n/en-US/OlaresManifest.yaml
  flowise/i18n/zh-CN/OlaresManifest.yaml
  flowise/owners
  flowise/templates/configmap.yaml
  flowise/templates/flowise.yaml
  flowise/values.yaml
Labels: NEW

#665 [UPDATE][anythingllm][1.0.2]remove api timeout limit
  anythingllm/Chart.yaml
  anythingllm/OlaresManifest.yaml
Labels: UPDATE
