Repository beclab/apps, pull requests merged in 2025-08, with the labels that each got.

#930 [UPDATE][wise][1.0.9]upgrade to 1.3.119
  wise/Chart.yaml
  wise/OlaresManifest.yaml
  wise/wise/templates/front.yaml
Labels: UPDATE

#935 [UPDATE][wise][1.0.11]add batch collect
  wise/Chart.yaml
  wise/OlaresManifest.yaml
  wise/knowledge/Chart.yaml
  wise/wise/Chart.yaml
  wise/wise/templates/front.yaml
Labels: waiting to submit, UPDATE

#932 [UPDATE][whisperwebui][1.0.8]upgrade app version 1.0.5
  whisperwebui/Chart.yaml
  whisperwebui/OlaresManifest.yaml
  whisperwebui/templates/clientproxy.yaml
  whisperwebui/templates/deployment.yaml
  whisperwebui/values.yaml
Labels: UPDATE

#936 [UPDATE][wise][1.0.12]upgrade to 1.3.126
  wise/Chart.yaml
  wise/OlaresManifest.yaml
  wise/knowledge/Chart.yaml
  wise/wise/Chart.yaml
  wise/wise/templates/front.yaml
Labels: UPDATE

#938 [UPDATE][wise][1.0.13]change to CS structure
  wise/Chart.yaml
  wise/OlaresManifest.yaml
  wise/knowledge/Chart.yaml
  wise/wise/Chart.yaml
Labels: UPDATE

#950 [UPDATE][sdwebuishare][1.0.11]fix syntax
  sdwebuishare/Chart.yaml
  sdwebuishare/OlaresManifest.yaml
Labels: UPDATE

#942 [UPDATE][sdwebuiforgeshare][1.0.5]fix syntax
  sdwebuiforgeshare/Chart.yaml
  sdwebuiforgeshare/OlaresManifest.yaml
Labels: waiting to submit, UPDATE

#943 [UPDATE][hunyuan3dv21][1.0.4]fix syntax
  hunyuan3dv21/Chart.yaml
  hunyuan3dv21/OlaresManifest.yaml
Labels: UPDATE

#948 [UPDATE][whisperwebui][1.0.9]fix syntax
  whisperwebui/Chart.yaml
  whisperwebui/OlaresManifest.yaml
Labels: UPDATE

#946 [UPDATE][stablefast3dshare][1.0.5]fix syntax
  stablefast3dshare/Chart.yaml
  stablefast3dshare/OlaresManifest.yaml
  stablefast3dshare/templates/client/clientproxy.yaml
Labels: UPDATE

#953 [UPDATE][wise][1.0.14]add batch collect
  wise/Chart.yaml
  wise/OlaresManifest.yaml
  wise/knowledge/Chart.yaml
  wise/knowledge/templates/knowledge_deployment.yaml
  wise/wise/Chart.yaml
  wise/wise/templates/front.yaml
Labels: UPDATE

#954 [UPDATE][nocodb][1.0.5]upgrade app version 0.263.8
  nocodb/Chart.yaml
  nocodb/OlaresManifest.yaml
  nocodb/i18n/en-US/OlaresManifest.yaml
  nocodb/i18n/zh-CN/OlaresManifest.yaml
  nocodb/templates/deployment.yaml
Labels: UPDATE

#955 [UPDATE][wise][1.0.15]adjust resource
  wise/Chart.yaml
  wise/OlaresManifest.yaml
  wise/knowledge/Chart.yaml
  wise/knowledge/templates/knowledge_deployment.yaml
  wise/wise/Chart.yaml
Labels: UPDATE

#956 [UPDATE][wise][1.0.16]update backend
  wise/Chart.yaml
  wise/OlaresManifest.yaml
  wise/knowledge/Chart.yaml
  wise/knowledge/templates/knowledge_deployment.yaml
  wise/wise/Chart.yaml
Labels: UPDATE

#957 [UPDATE][wise][1.0.17]fix feed search
  wise/Chart.yaml
  wise/OlaresManifest.yaml
  wise/knowledge/Chart.yaml
  wise/knowledge/templates/knowledge_deployment.yaml
  wise/wise/Chart.yaml
Labels: UPDATE

#961 [UPDATE][comfyuishare][1.2.15]fix i18n description
  comfyuishare/Chart.yaml
  comfyuishare/OlaresManifest.yaml
  comfyuishare/i18n/zh-CN/OlaresManifest.yaml
Labels: UPDATE

#962 [UPDATE][wise][1.0.18]fix download progress
  wise/Chart.yaml
  wise/OlaresManifest.yaml
  wise/knowledge/Chart.yaml
  wise/wise/Chart.yaml
  wise/wise/templates/front.yaml
Labels: UPDATE

#963 [UPDATE][comfyuishare][1.2.16]fix upgrade
  comfyuishare/Chart.yaml
  comfyuishare/OlaresManifest.yaml
  comfyuishare/templates/deployment.yaml
Labels: UPDATE

#980 [UPDATE][dify][1.1.13]fix invalid dependencies
  dify/Chart.yaml
  dify/OlaresManifest.yaml
Labels: UPDATE

#983 [SUSPEND][wise][1.0.18]temporary stop listing
  wise/.suspend
Labels: SUSPEND

#984 [UPDATE][n8n][1.0.7]upgrade to 1.107.4
  n8n/Chart.yaml
  n8n/OlaresManifest.yaml
  n8n/i18n/en-US/OlaresManifest.yaml
  n8n/i18n/zh-CN/OlaresManifest.yaml
  n8n/templates/n8n.yaml
Labels: UPDATE

#985 [UPDATE][comfyuishare][1.2.17]up version to 0.3.51
  comfyuishare/Chart.yaml
  comfyuishare/OlaresManifest.yaml
  comfyuishare/i18n/en-US/OlaresManifest.yaml
  comfyuishare/i18n/zh-CN/OlaresManifest.yaml
  comfyuishare/templates/deployment.yaml
Labels: UPDATE

#989 [SUSPEND][echomimicv2][1.0.6]
  echomimicv2/.suspend
Labels: SUSPEND

#986 [NEW][refly][1.0.1]add app refly
  refly/.helmignore
  refly/Chart.yaml
  refly/OlaresManifest.yaml
  refly/i18n/en-US/OlaresManifest.yaml
  refly/i18n/zh-CN/OlaresManifest.yaml
  refly/owners
  refly/templates/nginx-config.yaml
  refly/templates/redis/deployment.yaml
  refly/templates/redis/service.yaml
  refly/templates/refly.yaml
  refly/templates/shared-config.yaml
  refly/values.yaml
Labels: NEW

#987 [NEW][rallly][1.0.1]add app
  rallly/.helmignore
  rallly/Chart.yaml
  rallly/OlaresManifest.yaml
  rallly/i18n/en-US/OlaresManifest.yaml
  rallly/i18n/zh-CN/OlaresManifest.yaml
  rallly/owners
  rallly/templates/configmap.yaml
  rallly/templates/rallly.yaml
  rallly/values.yaml
Labels: NEW

#990 [UPDATE][mindmap][1.0.7]fix supportArch
  mindmap/Chart.yaml
  mindmap/OlaresManifest.yaml
Labels: UPDATE

#991 [UPDATE][rallly][1.0.2]add install guide
  rallly/Chart.yaml
  rallly/OlaresManifest.yaml
  rallly/i18n/en-US/OlaresManifest.yaml
  rallly/i18n/zh-CN/OlaresManifest.yaml
Labels: UPDATE

#992 [NEW][langfuse][1.0.0]add app Langfuse
  langfuse/Chart.yaml
  langfuse/OlaresManifest.yaml
  langfuse/i18n/en-US/OlaresManifest.yaml
  langfuse/i18n/zh-CN/OlaresManifest.yaml
  langfuse/owners
  langfuse/templates/deployment.yaml
  langfuse/templates/redis/deployment.yaml
  langfuse/templates/redis/service.yaml
  langfuse/values.yaml
Labels: NEW

#993 [UPDATE][showdoc][1.0.4] update resource limit
  showdoc/Chart.yaml
  showdoc/OlaresManifest.yaml
  showdoc/templates/showdoc.yaml
Labels: waiting to submit, UPDATE

#994 [UPDATE][mtranserver][1.0.5]upgrade version 3.0.4
  mtranserver/Chart.yaml
  mtranserver/OlaresManifest.yaml
  mtranserver/i18n/en-US/OlaresManifest.yaml
  mtranserver/i18n/zh-CN/OlaresManifest.yaml
  mtranserver/templates/configmap.yaml
  mtranserver/templates/mtranserver.yaml
Labels: UPDATE

#995 [UPDATE][gitea][1.0.3] upgrade version 1.24.5 and add arm64
  gitea/Chart.yaml
  gitea/OlaresManifest.yaml
  gitea/templates/deployment.yaml
Labels: UPDATE

#998 [UPDATE][md][1.0.4]upgrade version 2.0.4
  md/Chart.yaml
  md/OlaresManifest.yaml
  md/templates/md.yaml
Labels: UPDATE

#1005 [UPDATE][jaaz][1.0.4]upgrade version 1.0.7 and add arm64 arch
  jaaz/Chart.yaml
  jaaz/OlaresManifest.yaml
  jaaz/templates/deployment.yaml
Labels: UPDATE

#1015 [UPDATE][astrbot][1.0.1]upgrade version 3.5.26 add supportArch arm64
  astrbot/Chart.yaml
  astrbot/OlaresManifest.yaml
  astrbot/templates/deployment.yaml
Labels: UPDATE

#1011 [UPDATE][cmproxy][1.0.6]upgrade version 2.25.3 add supportArch arm64
  cmproxy/Chart.yaml
  cmproxy/OlaresManifest.yaml
  cmproxy/i18n/en-US/OlaresManifest.yaml
  cmproxy/i18n/zh-CN/OlaresManifest.yaml
  cmproxy/templates/proxy.yaml
Labels: UPDATE

#1012 [UPDATE][hasura][1.0.4]upgrade version 2.48.4 add supportArch arm64
  hasura/Chart.yaml
  hasura/OlaresManifest.yaml
  hasura/i18n/en-US/OlaresManifest.yaml
  hasura/i18n/zh-CN/OlaresManifest.yaml
  hasura/templates/hasura.yaml
Labels: UPDATE
