Repository beclab/apps, pull requests merged in 2025-02, with the labels that each got.

#554 [UPDATE][ollama][1.0.12]upgrade to 0.5.7
  ollama/Chart.yaml
  ollama/OlaresManifest.yaml
  ollama/i18n/en-US/OlaresManifest.yaml
  ollama/i18n/zh-CN/OlaresManifest.yaml
  ollama/templates/deployment.yaml
Labels: UPDATE

#555 [UPDATE][ragflow][1.0.5]add system data requirement
  ragflow/Chart.yaml
  ragflow/OlaresManifest.yaml
Labels: UPDATE

#556 [UPDATE][sdwebui][1.0.8]Improve the robustness of initcache phase commands
  sdwebui/Chart.yaml
  sdwebui/OlaresManifest.yaml
  sdwebui/templates/deployment.yaml
Labels: UPDATE

#557 [UPDATE][difyfusion][1.0.6]upgrade to 0.15.3
  difyfusion/Chart.yaml
  difyfusion/OlaresManifest.yaml
  difyfusion/i18n/en-US/OlaresManifest.yaml
  difyfusion/i18n/zh-CN/OlaresManifest.yaml
  difyfusion/templates/deployment.yaml
Labels: UPDATE

#558 [UPDATE][difyfusionclient][1.0.6]bump version to 0.15.3
  difyfusionclient/Chart.yaml
  difyfusionclient/OlaresManifest.yaml
  difyfusionclient/i18n/en-US/OlaresManifest.yaml
  difyfusionclient/i18n/zh-CN/OlaresManifest.yaml
Labels: waiting to submit, UPDATE

#559 [UPDATE][wordpress][1.0.10]fix plugin use http
  wordpress/Chart.yaml
  wordpress/OlaresManifest.yaml
  wordpress/templates/proxy.yaml
Labels: UPDATE

#560 [NEW][memos][1.0.1]new app memos
  memos/.helmignore
  memos/Chart.yaml
  memos/OlaresManifest.yaml
  memos/i18n/en-US/OlaresManifest.yaml
  memos/i18n/zh-CN/OlaresManifest.yaml
  memos/owners
  memos/templates/memos.yaml
  memos/values.yaml
Labels: waiting to submit, NEW

#561 [UPDATE][gitlabfusion][1.0.4]fix create account
  gitlabfusion/Chart.yaml
  gitlabfusion/OlaresManifest.yaml
  gitlabfusion/templates/clientproxy.yaml
  gitlabfusion/templates/entrances.yaml
  gitlabfusion/templates/gitlab.yaml
  gitlabfusion/templates/serverproxy.yaml
Labels: UPDATE

#563 [UPDATE][difyfusionclient][1.0.7]fix client install on other user
  difyfusionclient/Chart.yaml
  difyfusionclient/OlaresManifest.yaml
  difyfusionclient/templates/dify_fe_deploy.yaml
Labels: UPDATE

#565 [UPDATE][memos][1.0.3]add featured image
  memos/Chart.yaml
  memos/OlaresManifest.yaml
  memos/i18n/en-US/OlaresManifest.yaml
  memos/i18n/zh-CN/OlaresManifest.yaml
Labels: UPDATE

#566 [UPDATE][sdwebui][1.0.9]update output path
  sdwebui/Chart.yaml
  sdwebui/OlaresManifest.yaml
  sdwebui/templates/deployment.yaml
Labels: UPDATE

#570 [NEW][xinference][1.0.8]new app xinference
  xinference/Chart.yaml
  xinference/OlaresManifest.yaml
  xinference/i18n/en-US/OlaresManifest.yaml
  xinference/i18n/zh-CN/OlaresManifest.yaml
  xinference/owners
  xinference/templates/clientproxy.yaml
  xinference/templates/deployment.yaml
  xinference/values.yaml
Labels: NEW

#564 [NEW][docmost][1.0.1]new app docmost
  docmost/.helmignore
  docmost/Chart.yaml
  docmost/OlaresManifest.yaml
  docmost/i18n/en-US/OlaresManifest.yaml
  docmost/i18n/zh-CN/OlaresManifest.yaml
  docmost/owners
  docmost/templates/docmost.yaml
  docmost/templates/redis/deployment.yaml
  docmost/templates/redis/service.yaml
  docmost/templates/secret.yaml
  docmost/values.yaml
Labels: waiting to submit, NEW

#569 [NEW][listmonk][1.0.1] new app listmonk
  listmonk/.helmignore
  listmonk/Chart.yaml
  listmonk/OlaresManifest.yaml
  listmonk/i18n/en-US/OlaresManifest.yaml
  listmonk/i18n/zh-CN/OlaresManifest.yaml
  listmonk/owners
  listmonk/templates/listmonk.yaml
  listmonk/values.yaml
Labels: NEW

#572 [NEW][excalidraw][1.0.1]new app excalidraw
  excalidraw/.helmignore
  excalidraw/Chart.yaml
  excalidraw/OlaresManifest.yaml
  excalidraw/i18n/en-US/OlaresManifest.yaml
  excalidraw/i18n/zh-CN/OlaresManifest.yaml
  excalidraw/owners
  excalidraw/templates/excalidraw.yaml
  excalidraw/values.yaml
Labels: NEW

#571 [UPDATE][openwebui][1.0.5]support xinference
  openwebui/Chart.yaml
  openwebui/OlaresManifest.yaml
  openwebui/templates/deployment.yaml
Labels: UPDATE

#574 [UPDATE][xinference][1.0.9]fix entrance auth level
  xinference/Chart.yaml
  xinference/OlaresManifest.yaml
Labels: UPDATE

#573 [NEW][directus][1.0.1]new app directus
  directus/.helmignore
  directus/Chart.yaml
  directus/OlaresManifest.yaml
  directus/i18n/en-US/OlaresManifest.yaml
  directus/i18n/zh-CN/OlaresManifest.yaml
  directus/owners
  directus/templates/directus.yaml
  directus/templates/redis/deployment.yaml
  directus/templates/redis/service.yaml
  directus/values.yaml
Labels: waiting to submit, NEW

#576 [SUSPEND][awesomedigitalhuman][1.0.3]suspend
  awesomedigitalhuman/.suspend
Labels: SUSPEND

#577 [UPDATE][comfyui][1.1.3]fix protobuf version
  comfyui/Chart.yaml
  comfyui/OlaresManifest.yaml
  comfyui/templates/deployment.yaml
Labels: UPDATE

#584 [UPDATE][directus][1.0.2]update default admin user
  directus/Chart.yaml
  directus/OlaresManifest.yaml
  directus/i18n/en-US/OlaresManifest.yaml
  directus/i18n/zh-CN/OlaresManifest.yaml
  directus/templates/directus.yaml
Labels: UPDATE

#585 [UPDATE][windows][1.0.3]fix: support igpu passthrough;iso use cdn url
  windows/Chart.yaml
  windows/OlaresManifest.yaml
  windows/templates/deployment.yaml
Labels: UPDATE

#586 [NEW][llamafactory][1.0.4]new app llamafactory
  llamafactory/Chart.yaml
  llamafactory/OlaresManifest.yaml
  llamafactory/i18n/en-US/OlaresManifest.yaml
  llamafactory/i18n/zh-CN/OlaresManifest.yaml
  llamafactory/owners
  llamafactory/templates/clientproxy.yaml
  llamafactory/templates/deployment.yaml
  llamafactory/values.yaml
Labels: waiting to submit, NEW

#587 [UPDATE][windows][1.0.4]fix: add tailscale acls
  windows/Chart.yaml
  windows/OlaresManifest.yaml
Labels: UPDATE

#583 [NEW][halo][1.0.2]new app halo
  halo/.helmignore
  halo/Chart.yaml
  halo/OlaresManifest.yaml
  halo/i18n/en-US/OlaresManifest.yaml
  halo/i18n/zh-CN/OlaresManifest.yaml
  halo/owners
  halo/templates/deployment.yaml
  halo/values.yaml
Labels: NEW

#579 [NEW][mindmap][1.0.1]new app Mindmap
  mindmap/.helmignore
  mindmap/Chart.yaml
  mindmap/OlaresManifest.yaml
  mindmap/i18n/en-US/OlaresManifest.yaml
  mindmap/i18n/zh-CN/OlaresManifest.yaml
  mindmap/owners
  mindmap/templates/deployment.yaml
  mindmap/values.yaml
Labels: NEW

#590 [UPDATE][halo][1.0.4]update app name
  halo/Chart.yaml
  halo/OlaresManifest.yaml
  halo/i18n/en-US/OlaresManifest.yaml
  halo/i18n/zh-CN/OlaresManifest.yaml
Labels: waiting to submit, UPDATE

#593 [UPDATE][mindmap][1.0.2]update app name
  mindmap/Chart.yaml
  mindmap/OlaresManifest.yaml
  mindmap/i18n/en-US/OlaresManifest.yaml
  mindmap/i18n/zh-CN/OlaresManifest.yaml
Labels: UPDATE

#594 [UPDATE][halo][1.0.5]update versions and policies
  halo/Chart.yaml
  halo/OlaresManifest.yaml
  halo/templates/deployment.yaml
Labels: UPDATE

#596 [UPDATE][halo][1.0.6]update version
  halo/Chart.yaml
  halo/OlaresManifest.yaml
Labels: UPDATE

#601 [UPDATE][directus][1.0.3] update title
  directus/Chart.yaml
  directus/OlaresManifest.yaml
  directus/i18n/en-US/OlaresManifest.yaml
  directus/i18n/zh-CN/OlaresManifest.yaml
Labels: UPDATE

#602 [UPDATE][listmonk][1.0.2] update title
  listmonk/Chart.yaml
  listmonk/OlaresManifest.yaml
  listmonk/i18n/en-US/OlaresManifest.yaml
  listmonk/i18n/zh-CN/OlaresManifest.yaml
Labels: UPDATE

#603 [UPDATE][memos][1.0.4] update title and openMethod
  memos/Chart.yaml
  memos/OlaresManifest.yaml
Labels: waiting to submit, UPDATE

#606 [UPDATE][windows][1.0.5]fix: change windows iso
  windows/Chart.yaml
  windows/OlaresManifest.yaml
  windows/templates/deployment.yaml
Labels: UPDATE

#605 [NEW][teable][1.0.1]new app
  teable/.helmignore
  teable/Chart.yaml
  teable/OlaresManifest.yaml
  teable/i18n/en-US/OlaresManifest.yaml
  teable/i18n/zh-CN/OlaresManifest.yaml
  teable/owners
  teable/templates/configmap.yaml
  teable/templates/redis/deployment.yaml
  teable/templates/redis/service.yaml
  teable/templates/secret.yaml
  teable/templates/teable.yaml
  teable/values.yaml
Labels: NEW

#608 [UPDATE][llamafactory][1.0.5]fix description and entrance auth level
  llamafactory/Chart.yaml
  llamafactory/OlaresManifest.yaml
  llamafactory/i18n/en-US/OlaresManifest.yaml
  llamafactory/i18n/zh-CN/OlaresManifest.yaml
Labels: UPDATE

#607 [NEW][stirlingpdf][1.0.1] new app stirlingpdf
  stirlingpdf/.helmignore
  stirlingpdf/Chart.yaml
  stirlingpdf/OlaresManifest.yaml
  stirlingpdf/i18n/en-US/OlaresManifest.yaml
  stirlingpdf/i18n/zh-CN/OlaresManifest.yaml
  stirlingpdf/owners
  stirlingpdf/templates/configmap.yaml
  stirlingpdf/templates/stirlingpdf.yaml
  stirlingpdf/values.yaml
Labels: NEW

#609 [UPDATE][stirlingpdf][1.0.2] update title
  stirlingpdf/Chart.yaml
  stirlingpdf/OlaresManifest.yaml
  stirlingpdf/i18n/zh-CN/OlaresManifest.yaml
Labels: UPDATE

#610 [UPDATE][photoview][1.0.1]fix launch permissions
  photoview/Chart.yaml
  photoview/OlaresManifest.yaml
  photoview/templates/deployment.yaml
Labels: UPDATE

#611 [UPDATE][comfyui][1.1.4]Update the image pull strategy and image repository prefix
  comfyui/Chart.yaml
  comfyui/OlaresManifest.yaml
  comfyui/i18n/en-US/OlaresManifest.yaml
  comfyui/i18n/zh-CN/OlaresManifest.yaml
  comfyui/templates/clientproxy.yaml
  comfyui/templates/configmap.yaml
  comfyui/templates/deployment.yaml
Labels: UPDATE
